/**
 * Embedded Prompt 227e migration SQL for Vercel runtime apply.
 * Generated from supabase/migrations. Do not hand-edit SQL here.
 */

export const PROMPT_227E_MIGRATIONS: ReadonlyArray<{ file: string; sql: string }> = [
  {
    "file": "20260821260000_prompt_227e_retraction_watch.sql",
    "sql": "-- Prompt 227e: retraction and trial-status watch columns (Collection 14).\n\nALTER TABLE public.kb_publications\n  ADD COLUMN IF NOT EXISTS is_retracted boolean NOT NULL DEFAULT false;\n\nALTER TABLE public.kb_publications\n  ADD COLUMN IF NOT EXISTS retraction_kind text\n    CHECK (\n      retraction_kind IS NULL\n      OR retraction_kind IN (\n        'retracted',\n        'retraction_of',\n        'expression_of_concern',\n        'erratum'\n      )\n    );\n\nALTER TABLE public.kb_publications\n  ADD COLUMN IF NOT EXISTS retraction_notice_pmid text;\n\nALTER TABLE public.kb_publications\n  ADD COLUMN IF NOT EXISTS retracted_detected_at timestamptz;\n\nALTER TABLE public.kb_publications\n  ADD COLUMN IF NOT EXISTS last_retraction_check_at timestamptz;\n\nCREATE INDEX IF NOT EXISTS kb_publications_retracted_idx\n  ON public.kb_publications (is_retracted)\n  WHERE is_retracted = true;\n\nALTER TABLE public.kb_trials\n  ADD COLUMN IF NOT EXISTS prior_status text;\n\nALTER TABLE public.kb_trials\n  ADD COLUMN IF NOT EXISTS status_changed_at timestamptz;\n\nALTER TABLE public.kb_trials\n  ADD COLUMN IF NOT EXISTS last_status_check_at timestamptz;\n\nALTER TABLE public.kb_peptide_evidence_links\n  ADD COLUMN IF NOT EXISTS support_flagged boolean NOT NULL DEFAULT false;\n\nALTER TABLE public.kb_peptide_evidence_links\n  ADD COLUMN IF NOT EXISTS support_flag_reason text;\n\nINSERT INTO public.curation_field_class_map (target_table, target_field, change_class, notes)\nVALUES\n  ('kb_publications', 'is_retracted', 1, 'Retraction flag; Thanos writes, Class 1 cascade'),\n  ('kb_trials', 'status', 1, 'Trial status transitions; Thanos watch upsert')\nON CONFLICT (target_table, target_field) DO UPDATE SET\n  change_class = EXCLUDED.change_class,\n  notes = EXCLUDED.notes;\n\nCOMMENT ON COLUMN public.kb_publications.is_retracted IS\n  'Prompt 227e: true when PubMed marks retracted or expression of concern.';\nCOMMENT ON COLUMN public.kb_peptide_evidence_links.support_flagged IS\n  'Prompt 227e: evidence link flagged when supporting pub/trial is retracted or safety-terminated.';\n"
  }
];
