-- ============================================================
-- Migration: Add tables required by Edge Functions
-- Tables: genetic_variants, supplement_logs, recommendations,
--         device_tokens, achievements, subscriptions
-- Applied: 2026-03-20
-- ============================================================

-- 1. Genetic variants (individual SNP results from genotyping)
CREATE TABLE IF NOT EXISTS public.genetic_variants (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  genetic_profile_id uuid NOT NULL REFERENCES public.genetic_profiles(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  rsid text NOT NULL,
  gene text,
  genotype text NOT NULL,
  chromosome text,
  position bigint,
  risk_level text CHECK (risk_level IN ('none', 'low', 'moderate', 'high')),
  clinical_significance text,
  pathway text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.genetic_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own variants" ON public.genetic_variants
  FOR SELECT USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_genetic_variants_profile ON public.genetic_variants(genetic_profile_id);
CREATE INDEX IF NOT EXISTS idx_genetic_variants_user ON public.genetic_variants(user_id);
CREATE INDEX IF NOT EXISTS idx_genetic_variants_rsid ON public.genetic_variants(rsid);

-- 2. Supplement logs (daily adherence tracking, triggers token awards)
CREATE TABLE IF NOT EXISTS public.supplement_logs (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  product_id uuid REFERENCES public.products(id),
  supplement_name text NOT NULL,
  dosage text,
  taken_at timestamptz NOT NULL DEFAULT now(),
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.supplement_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own logs" ON public.supplement_logs
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own logs" ON public.supplement_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_supplement_logs_user_date ON public.supplement_logs(user_id, log_date);

-- 3. Recommendations (generated by generate-protocol edge function)
CREATE TABLE IF NOT EXISTS public.recommendations (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  genetic_profile_id uuid REFERENCES public.genetic_profiles(id),
  assessment_id uuid REFERENCES public.clinical_assessments(id),
  pathway text NOT NULL,
  product_id uuid REFERENCES public.products(id),
  product_sku text,
  product_name text NOT NULL,
  dosing text,
  rationale text,
  priority integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'approved', 'rejected', 'active', 'completed')),
  reviewed_by uuid REFERENCES public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own recommendations" ON public.recommendations
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Practitioners can view patient recommendations" ON public.recommendations
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('practitioner', 'admin'))
  );
CREATE INDEX IF NOT EXISTS idx_recommendations_user ON public.recommendations(user_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON public.recommendations(status);

-- 4. Device tokens (for push notifications via Expo)
CREATE TABLE IF NOT EXISTS public.device_tokens (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  expo_push_token text NOT NULL,
  device_type text CHECK (device_type IN ('ios', 'android', 'web')),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, expo_push_token)
);

ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own tokens" ON public.device_tokens
  FOR ALL USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_device_tokens_user ON public.device_tokens(user_id);

-- 5. Achievements (milestone tracking for gamification)
CREATE TABLE IF NOT EXISTS public.achievements (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  achievement_type text NOT NULL,
  achievement_name text NOT NULL,
  description text,
  tokens_awarded integer NOT NULL DEFAULT 0,
  achieved_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, achievement_type)
);

ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own achievements" ON public.achievements
  FOR SELECT USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_achievements_user ON public.achievements(user_id);

-- 6. Subscriptions (Stripe subscription state)
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  stripe_customer_id text,
  stripe_subscription_id text UNIQUE,
  plan_id text NOT NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'past_due', 'canceled', 'incomplete', 'trialing')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  hsa_fsa_eligible boolean NOT NULL DEFAULT false,
  truemed_qualification_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own subscriptions" ON public.subscriptions
  FOR SELECT USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe ON public.subscriptions(stripe_subscription_id);
