// Seed 110 supplement brands + aliases + top products
// Run via: npx tsx src/scripts/seed-brand-registry.ts

function n(s: string): string { return s.toLowerCase().replace(/[^a-z0-9]/g, "").trim(); }
function np(s: string): string { return s.toLowerCase().replace(/[^a-z0-9 ]/g, "").replace(/\s+/g, " ").trim(); }

interface Brand { name: string; tier: number; label: string; country: string; cats: string[]; certs: string[]; skus: number; url: string; practOnly: boolean; aliases: string[] }
interface Product { brand: string; name: string; cat: string; serving: string; count: number; method: string; bio: number }

export const BRANDS: Brand[] = [
  // TIER 1: Premium Practitioner
  { name:"Thorne Research",tier:1,label:"Premium Practitioner",country:"USA",cats:["multivitamins","minerals","sports","hormones"],certs:["NSF","TGA","GMP"],skus:180,url:"https://thorne.com",practOnly:false,aliases:["Thorne","Thorne Supplements"] },
  { name:"Pure Encapsulations",tier:1,label:"Premium Practitioner",country:"USA",cats:["hypoallergenic vitamins","minerals","amino acids"],certs:["GMP","USP"],skus:250,url:"https://pureencapsulations.com",practOnly:false,aliases:["Pure Encap","PE"] },
  { name:"Metagenics",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner supplements","medical foods","probiotics"],certs:["NSF","GMP","TGA"],skus:200,url:"https://metagenics.com",practOnly:true,aliases:["Metagenics Inc"] },
  { name:"Ortho Molecular Products",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner vitamins","immune","GI"],certs:["GMP"],skus:150,url:"https://orthomolecularproducts.com",practOnly:true,aliases:["Ortho Molecular","OMP"] },
  { name:"Integrative Therapeutics",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner supplements","enzymes","botanicals"],certs:["GMP"],skus:120,url:"https://integrativetherapeutics.com",practOnly:false,aliases:["Integrative Therapeutics Inc"] },
  { name:"Designs for Health",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner vitamins","proteins","omega-3"],certs:["GMP"],skus:200,url:"https://designsforhealth.com",practOnly:false,aliases:["DFH","Designs For Health"] },
  { name:"Klaire Labs",tier:1,label:"Premium Practitioner",country:"USA",cats:["probiotics","hypoallergenic vitamins","enzymes"],certs:["GMP"],skus:100,url:"https://klairelabs.com",practOnly:false,aliases:["Klaire","Klaire Laboratories"] },
  { name:"Xymogen",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner exclusive","metabolic","GI","neuro"],certs:["GMP","NSF"],skus:150,url:"https://xymogen.com",practOnly:true,aliases:["XYMOGEN"] },
  { name:"Douglas Laboratories",tier:1,label:"Premium Practitioner",country:"USA",cats:["vitamins","minerals","specialty nutrients"],certs:["GMP","TGA"],skus:200,url:"https://douglaslabs.com",practOnly:false,aliases:["Douglas Labs"] },
  { name:"Vital Nutrients",tier:1,label:"Premium Practitioner",country:"USA",cats:["practitioner grade","third party tested"],certs:["GMP"],skus:150,url:"https://vitalnutrients.net",practOnly:false,aliases:["Vital Nutrients Inc"] },
  { name:"Life Extension",tier:1,label:"Premium Practitioner",country:"USA",cats:["longevity","anti-aging","research-backed"],certs:["GMP","ConsumerLab"],skus:300,url:"https://lifeextension.com",practOnly:false,aliases:["Life Extension Foundation","LEF"] },
  { name:"Nordic Naturals",tier:1,label:"Premium Practitioner",country:"USA",cats:["omega-3","fish oil","prenatal DHA"],certs:["NSF","Friend of the Sea"],skus:150,url:"https://nordicnaturals.com",practOnly:false,aliases:["Nordic Naturals Inc"] },
  { name:"Jarrow Formulas",tier:1,label:"Premium Practitioner",country:"USA",cats:["probiotics","CoQ10","vitamins","amino acids"],certs:["GMP"],skus:200,url:"https://jarrow.com",practOnly:false,aliases:["Jarrow"] },
  { name:"Doctor's Best",tier:1,label:"Premium Practitioner",country:"USA",cats:["science-based vitamins","minerals","specialty"],certs:["GMP","USP"],skus:200,url:"https://drbvitamins.com",practOnly:false,aliases:["Doctors Best","Dr Best"] },
  { name:"Protocol for Life Balance",tier:1,label:"Premium Practitioner",country:"USA",cats:["professional grade vitamins"],certs:["GMP"],skus:100,url:"https://protocolforlife.com",practOnly:false,aliases:["Protocol","PFLB"] },
  { name:"Allergy Research Group",tier:1,label:"Premium Practitioner",country:"USA",cats:["hypoallergenic","specialty nutrients"],certs:["GMP"],skus:150,url:"https://allergyresearchgroup.com",practOnly:false,aliases:["ARG","Allergy Research"] },
  { name:"Standard Process",tier:1,label:"Premium Practitioner",country:"USA",cats:["whole-food supplements"],certs:["GMP"],skus:100,url:"https://standardprocess.com",practOnly:true,aliases:["Standard Process Inc"] },
  { name:"Quicksilver Scientific",tier:1,label:"Premium Practitioner",country:"USA",cats:["liposomal","detox","glutathione"],certs:["GMP"],skus:60,url:"https://quicksilverscientific.com",practOnly:false,aliases:["Quicksilver","QS"] },
  { name:"Codeage",tier:1,label:"Premium Practitioner",country:"USA",cats:["premium vitamins","collagen","keto","liposomal"],certs:["GMP"],skus:150,url:"https://codeage.com",practOnly:false,aliases:["Codeage LLC"] },
  { name:"Seeking Health",tier:1,label:"Premium Practitioner",country:"USA",cats:["methylation","genetic-targeted nutrients"],certs:["GMP"],skus:100,url:"https://seekinghealth.com",practOnly:false,aliases:["Seeking Health Inc","Dr Ben Lynch"] },
  // TIER 2: Premium DTC
  { name:"AG1",tier:2,label:"Premium DTC",country:"USA",cats:["greens powder"],certs:["NSF Certified for Sport"],skus:5,url:"https://drinkag1.com",practOnly:false,aliases:["Athletic Greens","AG1 Athletic Greens"] },
  { name:"Ritual",tier:2,label:"Premium DTC",country:"USA",cats:["multivitamins","prenatal","protein"],certs:["USP"],skus:20,url:"https://ritual.com",practOnly:false,aliases:["Ritual Inc","Ritual Vitamins"] },
  { name:"Seed",tier:2,label:"Premium DTC",country:"USA",cats:["synbiotic","probiotic"],certs:["GMP"],skus:5,url:"https://seed.com",practOnly:false,aliases:["Seed Health","Seed DS-01"] },
  { name:"Momentous",tier:2,label:"Premium DTC",country:"USA",cats:["sports performance","sleep","cognition"],certs:["NSF Certified for Sport"],skus:30,url:"https://livemomentous.com",practOnly:false,aliases:["Momentous Supplements","Live Momentous"] },
  { name:"OLLY",tier:2,label:"Premium DTC",country:"USA",cats:["gummy vitamins","sleep","stress","beauty"],certs:["GMP"],skus:50,url:"https://olly.com",practOnly:false,aliases:["Olly Nutrition"] },
  { name:"Hum Nutrition",tier:2,label:"Premium DTC",country:"USA",cats:["beauty supplements","gut health","mood"],certs:["GMP"],skus:30,url:"https://humnutrition.com",practOnly:false,aliases:["HUM","Hum"] },
  { name:"Moon Juice",tier:2,label:"Premium DTC",country:"USA",cats:["adaptogens","nootropics","beauty"],certs:["GMP"],skus:20,url:"https://moonjuice.com",practOnly:false,aliases:["Moon Juice Inc"] },
  { name:"Nutrafol",tier:2,label:"Premium DTC",country:"USA",cats:["hair growth"],certs:["GMP"],skus:10,url:"https://nutrafol.com",practOnly:false,aliases:["Nutrafol Inc"] },
  { name:"Care/of",tier:2,label:"Premium DTC",country:"USA",cats:["personalized vitamins"],certs:["GMP"],skus:50,url:"https://takecareof.com",practOnly:false,aliases:["Care Of","Careof"] },
  { name:"Persona Nutrition",tier:2,label:"Premium DTC",country:"USA",cats:["personalized vitamins"],certs:["GMP"],skus:80,url:"https://personanutrition.com",practOnly:false,aliases:["Persona"] },
  { name:"Primal Harvest",tier:2,label:"Premium DTC",country:"USA",cats:["multivitamins","collagen","greens"],certs:["GMP"],skus:30,url:"https://primalharvest.com",practOnly:false,aliases:["Primal Harvest LLC"] },
  { name:"Bloom Nutrition",tier:2,label:"Premium DTC",country:"USA",cats:["greens powders","energy","beauty"],certs:["GMP"],skus:20,url:"https://bloomnu.com",practOnly:false,aliases:["Bloom","Bloom Nu"] },
  { name:"Cymbiotika",tier:2,label:"Premium DTC",country:"USA",cats:["liposomal vitamins","omega-3","collagen"],certs:["GMP"],skus:30,url:"https://cymbiotika.com",practOnly:false,aliases:["Cymbiotika LLC"] },
  { name:"Onnit",tier:2,label:"Premium DTC",country:"USA",cats:["Alpha Brain","mushrooms","sports"],certs:["GMP"],skus:40,url:"https://onnit.com",practOnly:false,aliases:["Onnit Labs"] },
  { name:"Ancient Nutrition",tier:2,label:"Premium DTC",country:"USA",cats:["multi-collagen","bone broth","supergreens"],certs:["GMP"],skus:50,url:"https://ancientnutrition.com",practOnly:false,aliases:["Ancient Nutrition LLC","Dr Axe"] },
  { name:"Sports Research",tier:2,label:"Premium DTC",country:"USA",cats:["omega-3","collagen","vitamins"],certs:["Non-GMO"],skus:40,url:"https://sportsresearch.com",practOnly:false,aliases:["SR","Sports Research Corp"] },
  { name:"Four Sigmatic",tier:2,label:"Premium DTC",country:"USA",cats:["mushroom coffee","adaptogens"],certs:["USDA Organic"],skus:20,url:"https://foursigmatic.com",practOnly:false,aliases:["Four Sigmatic Inc"] },
  { name:"Transparent Labs",tier:2,label:"Premium DTC",country:"USA",cats:["sports nutrition","nootropics","vitamins"],certs:["GMP"],skus:50,url:"https://transparentlabs.com",practOnly:false,aliases:["TL","Transparent Labs LLC"] },
  { name:"Legion Athletics",tier:2,label:"Premium DTC",country:"USA",cats:["sports supplements","pre-workout"],certs:["GMP"],skus:30,url:"https://legionathletics.com",practOnly:false,aliases:["Legion","Legion Athletics Inc"] },
  { name:"Vital Proteins",tier:2,label:"Premium DTC",country:"USA",cats:["collagen peptides","beauty"],certs:["GMP"],skus:30,url:"https://vitalproteins.com",practOnly:false,aliases:["Vital Proteins LLC"] },
  { name:"IM8 Health",tier:2,label:"Premium DTC",country:"UK",cats:["superfood powder"],certs:["NSF Certified for Sport"],skus:3,url:"https://im8health.com",practOnly:false,aliases:["IM8","Inter Miami"] },
  // TIER 3: Mass Market
  { name:"Nature Made",tier:3,label:"Mass Market",country:"USA",cats:["multivitamins","D3","omega-3","minerals"],certs:["USP Verified"],skus:200,url:"https://naturemade.com",practOnly:false,aliases:["Nature Made Vitamins"] },
  { name:"Nature's Bounty",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals","herbs","fish oil"],certs:["GMP"],skus:300,url:"https://naturesbounty.com",practOnly:false,aliases:["Natures Bounty"] },
  { name:"Centrum",tier:3,label:"Mass Market",country:"USA",cats:["multivitamins"],certs:["USP"],skus:50,url:"https://centrum.com",practOnly:false,aliases:["Centrum Vitamins","Centrum Adults"] },
  { name:"One A Day",tier:3,label:"Mass Market",country:"USA",cats:["multivitamins"],certs:["GMP"],skus:30,url:"https://oneaday.com",practOnly:false,aliases:["One-A-Day","Bayer One A Day"] },
  { name:"NOW Foods",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals","herbs","sports","essential oils"],certs:["GMP"],skus:1400,url:"https://nowfoods.com",practOnly:false,aliases:["NOW","Now Foods","NOW Supplements"] },
  { name:"Garden of Life",tier:3,label:"Mass Market",country:"USA",cats:["organic whole-food vitamins","probiotics","protein"],certs:["USDA Organic","Non-GMO"],skus:200,url:"https://gardenoflife.com",practOnly:false,aliases:["Garden Of Life","GOL"] },
  { name:"New Chapter",tier:3,label:"Mass Market",country:"USA",cats:["whole-food fermented vitamins","herbs"],certs:["Certified B Corp"],skus:80,url:"https://newchapter.com",practOnly:false,aliases:["New Chapter Inc"] },
  { name:"Nature's Way",tier:3,label:"Mass Market",country:"USA",cats:["herbal supplements","vitamins","probiotics"],certs:["GMP"],skus:400,url:"https://naturesway.com",practOnly:false,aliases:["Natures Way"] },
  { name:"Kirkland Signature",tier:3,label:"Mass Market",country:"USA",cats:["multivitamins","omega-3","D3"],certs:["USP"],skus:30,url:"https://costco.com",practOnly:false,aliases:["Kirkland","Costco Kirkland"] },
  { name:"Solgar",tier:3,label:"Mass Market",country:"USA",cats:["premium vitamins","minerals","herbs"],certs:["GMP"],skus:300,url:"https://solgar.com",practOnly:false,aliases:["Solgar Inc","Solgar Vitamins"] },
  { name:"MegaFood",tier:3,label:"Mass Market",country:"USA",cats:["farm-to-tablet","whole-food vitamins"],certs:["Certified B Corp","Non-GMO"],skus:60,url:"https://megafood.com",practOnly:false,aliases:["Mega Food"] },
  { name:"SmartyPants",tier:3,label:"Mass Market",country:"USA",cats:["gummy vitamins","kids","prenatal"],certs:["Non-GMO"],skus:20,url:"https://smartypantsvitamins.com",practOnly:false,aliases:["Smarty Pants"] },
  { name:"Natrol",tier:3,label:"Mass Market",country:"USA",cats:["melatonin","biotin","vitamins"],certs:["GMP"],skus:80,url:"https://natrol.com",practOnly:false,aliases:["Natrol Inc"] },
  { name:"Swanson Health",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","herbs","specialty"],certs:["GMP"],skus:1000,url:"https://swansonvitamins.com",practOnly:false,aliases:["Swanson","Swanson Vitamins"] },
  { name:"GNC",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","sports nutrition","herbs"],certs:["GMP"],skus:500,url:"https://gnc.com",practOnly:false,aliases:["GNC Holdings","GNC Live Well"] },
  { name:"Puritan's Pride",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals","herbs"],certs:["GMP"],skus:500,url:"https://puritan.com",practOnly:false,aliases:["Puritans Pride"] },
  { name:"Rainbow Light",tier:3,label:"Mass Market",country:"USA",cats:["whole-food multivitamins","prenatal"],certs:["Non-GMO"],skus:30,url:"https://rainbowlight.com",practOnly:false,aliases:["Rainbow Light Nutrition"] },
  { name:"Sundown Naturals",tier:3,label:"Mass Market",country:"USA",cats:["Non-GMO vitamins","minerals"],certs:["Non-GMO"],skus:100,url:"https://sundownnaturals.com",practOnly:false,aliases:["Sundown"] },
  { name:"Bluebonnet",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals","herbs"],certs:["GMP","Kosher"],skus:200,url:"https://bluebonnetnutrition.com",practOnly:false,aliases:["Bluebonnet Nutrition"] },
  { name:"Solaray",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","herbs","specialty"],certs:["GMP"],skus:400,url:"https://solaray.com",practOnly:false,aliases:["Solaray Inc"] },
  { name:"Source Naturals",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","herbs","amino acids"],certs:["GMP"],skus:400,url:"https://sourcenaturals.com",practOnly:false,aliases:["Source Naturals Inc"] },
  { name:"Country Life",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals"],certs:["GMP","Kosher"],skus:200,url:"https://country-life.com",practOnly:false,aliases:["Country Life Vitamins"] },
  { name:"KAL",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","minerals"],certs:["GMP"],skus:200,url:"https://kalvitamins.com",practOnly:false,aliases:["KAL Vitamins"] },
  { name:"Nature's Plus",tier:3,label:"Mass Market",country:"USA",cats:["whole-food vitamins","amino acids"],certs:["GMP"],skus:150,url:"https://naturesplus.com",practOnly:false,aliases:["Natures Plus"] },
  { name:"Spring Valley",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","herbs"],certs:["GMP"],skus:100,url:"https://walmart.com",practOnly:false,aliases:["Spring Valley Walmart"] },
  { name:"Equate",tier:3,label:"Mass Market",country:"USA",cats:["store-brand vitamins"],certs:["USP"],skus:40,url:"https://walmart.com",practOnly:false,aliases:["Equate Walmart"] },
  { name:"21st Century",tier:3,label:"Mass Market",country:"USA",cats:["budget vitamins","minerals"],certs:["GMP"],skus:100,url:"https://21stcenturyvitamins.com",practOnly:false,aliases:["21st Century Vitamins"] },
  { name:"The Vitamin Shoppe",tier:3,label:"Mass Market",country:"USA",cats:["house-brand vitamins"],certs:["GMP"],skus:200,url:"https://vitaminshoppe.com",practOnly:false,aliases:["Vitamin Shoppe","Vthrive"] },
  { name:"Piping Rock",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","herbs","essential oils"],certs:["GMP"],skus:500,url:"https://pipingrock.com",practOnly:false,aliases:["Piping Rock Health"] },
  { name:"Member's Mark",tier:3,label:"Mass Market",country:"USA",cats:["vitamins","omega-3"],certs:["GMP"],skus:25,url:"https://samsclub.com",practOnly:false,aliases:["Members Mark","Sam's Club"] },
  { name:"Youtheory",tier:3,label:"Mass Market",country:"USA",cats:["collagen","turmeric"],certs:["GMP"],skus:20,url:"https://youtheory.com",practOnly:false,aliases:["Youtheory LLC"] },
  // TIER 4: Specialty / Herbal / Functional
  { name:"Gaia Herbs",tier:4,label:"Specialty Herbal",country:"USA",cats:["herbal supplements","adaptogens","mushrooms"],certs:["Certified B Corp"],skus:100,url:"https://gaiaherbs.com",practOnly:false,aliases:["Gaia","Gaia Herbs Inc"] },
  { name:"Herb Pharm",tier:4,label:"Specialty Herbal",country:"USA",cats:["liquid herbal extracts","tinctures"],certs:["Certified Organic"],skus:200,url:"https://herb-pharm.com",practOnly:false,aliases:["Herb Pharm LLC","HerbPharm"] },
  { name:"Host Defense",tier:4,label:"Specialty Herbal",country:"USA",cats:["mushroom supplements"],certs:["USDA Organic"],skus:30,url:"https://fungi.com",practOnly:false,aliases:["Host Defense Mushrooms","Fungi Perfecti","Paul Stamets"] },
  { name:"Oregon's Wild Harvest",tier:4,label:"Specialty Herbal",country:"USA",cats:["organic herbal supplements"],certs:["Certified Organic"],skus:80,url:"https://oregonswildharvest.com",practOnly:false,aliases:["Oregons Wild Harvest"] },
  { name:"Organic India",tier:4,label:"Specialty Herbal",country:"India",cats:["tulsi teas","herbal supplements"],certs:["USDA Organic","Fair Trade"],skus:60,url:"https://organicindia.com",practOnly:false,aliases:["Organic India USA"] },
  { name:"Enzymedica",tier:4,label:"Specialty Herbal",country:"USA",cats:["digestive enzymes","probiotics"],certs:["GMP"],skus:40,url:"https://enzymedica.com",practOnly:false,aliases:["Enzymedica Inc"] },
  { name:"Renew Life",tier:4,label:"Specialty Herbal",country:"USA",cats:["probiotics","digestive enzymes","fiber"],certs:["GMP"],skus:30,url:"https://renewlife.com",practOnly:false,aliases:["Renew Life Probiotics"] },
  { name:"Culturelle",tier:4,label:"Specialty Herbal",country:"USA",cats:["probiotics"],certs:["GMP"],skus:15,url:"https://culturelle.com",practOnly:false,aliases:["Culturelle Probiotics"] },
  { name:"Align",tier:4,label:"Specialty Herbal",country:"USA",cats:["probiotics"],certs:["GMP"],skus:10,url:"https://alignprobiotics.com",practOnly:false,aliases:["Align Probiotics","Align P&G"] },
  { name:"Florastor",tier:4,label:"Specialty Herbal",country:"France",cats:["yeast probiotic"],certs:["GMP"],skus:5,url:"https://florastor.com",practOnly:false,aliases:["Florastor Probiotics"] },
  { name:"Kyolic",tier:4,label:"Specialty Herbal",country:"Japan",cats:["aged garlic extract","cardiovascular"],certs:["GMP"],skus:30,url:"https://kyolic.com",practOnly:false,aliases:["Kyolic Garlic","Wakunaga"] },
  { name:"Terry Naturally",tier:4,label:"Specialty Herbal",country:"USA",cats:["curcumin","herbal specialties"],certs:["GMP"],skus:100,url:"https://terrynaturally.com",practOnly:false,aliases:["Terry Naturally EuroPharma","EuroPharma"] },
  { name:"Planetary Herbals",tier:4,label:"Specialty Herbal",country:"USA",cats:["ayurvedic","chinese herbal formulas"],certs:["GMP"],skus:80,url:"https://planetaryherbals.com",practOnly:false,aliases:["Planetary Herbals Inc"] },
  { name:"Himalaya",tier:4,label:"Specialty Herbal",country:"India",cats:["ayurvedic herbal supplements"],certs:["Certified Organic"],skus:60,url:"https://himalayausa.com",practOnly:false,aliases:["Himalaya Herbal","Himalaya Wellness"] },
  { name:"Gundry MD",tier:4,label:"Specialty Herbal",country:"USA",cats:["polyphenol","gut health","metabolic"],certs:["GMP"],skus:20,url:"https://gundrymd.com",practOnly:false,aliases:["Dr Gundry","Gundry MD LLC"] },
  { name:"Amy Myers MD",tier:4,label:"Specialty Herbal",country:"USA",cats:["autoimmune","gut","thyroid"],certs:["GMP"],skus:20,url:"https://amymyersmd.com",practOnly:false,aliases:["Amy Myers","Dr Amy Myers"] },
  { name:"Real Mushrooms",tier:4,label:"Specialty Herbal",country:"Canada",cats:["mushroom extracts"],certs:["USDA Organic"],skus:15,url:"https://realmushrooms.com",practOnly:false,aliases:["Real Mushrooms Inc"] },
  { name:"Om Mushroom Superfood",tier:4,label:"Specialty Herbal",country:"USA",cats:["mushroom powders","capsules"],certs:["Certified Organic"],skus:20,url:"https://ommushrooms.com",practOnly:false,aliases:["Om Mushroom","OM"] },
  { name:"Laird Superfood",tier:4,label:"Specialty Herbal",country:"USA",cats:["mushroom coffee","creamers"],certs:["GMP"],skus:20,url:"https://lairdsuperfood.com",practOnly:false,aliases:["Laird","Laird Hamilton"] },
  { name:"Bulletproof",tier:4,label:"Specialty Herbal",country:"USA",cats:["MCT oil","collagen","nootropics"],certs:["GMP"],skus:30,url:"https://bulletproof.com",practOnly:false,aliases:["Bulletproof Inc","Dave Asprey"] },
  // TIER 5: Canadian / International
  { name:"Organika",tier:5,label:"Canadian/International",country:"Canada",cats:["magnesium","collagen","mushrooms","enzymes"],certs:["NHP","GMP"],skus:100,url:"https://organika.com",practOnly:false,aliases:["Organika Health","Organika Products"] },
  { name:"Natural Factors",tier:5,label:"Canadian/International",country:"Canada",cats:["vitamins","minerals","herbs","enzymes"],certs:["NHP","GMP"],skus:400,url:"https://naturalfactors.com",practOnly:false,aliases:["Natural Factors Nutritional","NF"] },
  { name:"Jamieson",tier:5,label:"Canadian/International",country:"Canada",cats:["vitamins","minerals","omega-3","probiotics"],certs:["NHP","GMP"],skus:300,url:"https://jamiesonvitamins.com",practOnly:false,aliases:["Jamieson Vitamins","Jamieson Laboratories"] },
  { name:"Webber Naturals",tier:5,label:"Canadian/International",country:"Canada",cats:["vitamins","minerals","specialty"],certs:["NHP","GMP"],skus:300,url:"https://webbernaturals.com",practOnly:false,aliases:["Webber","Webber Naturals Ltd"] },
  { name:"CanPrev",tier:5,label:"Canadian/International",country:"Canada",cats:["practitioner-grade","women's health","minerals"],certs:["NHP","GMP"],skus:80,url:"https://canprev.ca",practOnly:false,aliases:["CanPrev Natural Health"] },
  { name:"AOR",tier:5,label:"Canadian/International",country:"Canada",cats:["research-grade","innovative formulations"],certs:["NHP","GMP"],skus:100,url:"https://aor.ca",practOnly:false,aliases:["Advanced Orthomolecular Research","AOR Inc"] },
  { name:"Genuine Health",tier:5,label:"Canadian/International",country:"Canada",cats:["fermented proteins","greens","gut health"],certs:["NHP"],skus:50,url:"https://genuinehealth.com",practOnly:false,aliases:["Genuine Health Inc"] },
  { name:"Progressive Nutritional",tier:5,label:"Canadian/International",country:"Canada",cats:["multivitamins","greens","protein"],certs:["NHP"],skus:40,url:"https://progressivenutritional.com",practOnly:false,aliases:["Progressive","Progressive Nutritional Therapies"] },
  { name:"SISU",tier:5,label:"Canadian/International",country:"Canada",cats:["Ester-C","vitamins","minerals"],certs:["NHP","GMP"],skus:80,url:"https://sfrx.com",practOnly:false,aliases:["SISU Inc","Sisu Vitamins"] },
  { name:"St. Francis Herb Farm",tier:5,label:"Canadian/International",country:"Canada",cats:["herbal tinctures","adaptogens"],certs:["Certified Organic","NHP"],skus:80,url:"https://stfrancisherbfarm.com",practOnly:false,aliases:["St Francis","SFHF"] },
  { name:"Orange Naturals",tier:5,label:"Canadian/International",country:"Canada",cats:["homeopathic","herbal","kids"],certs:["NHP"],skus:40,url:"https://orangenaturals.com",practOnly:false,aliases:["Orange Naturals Inc"] },
  { name:"Enerex",tier:5,label:"Canadian/International",country:"Canada",cats:["specialty nutrients","greens","enzymes"],certs:["NHP"],skus:30,url:"https://enerex.ca",practOnly:false,aliases:["Enerex Botanicals"] },
  { name:"Blackmores",tier:5,label:"Canadian/International",country:"Australia",cats:["vitamins","fish oil","joint health"],certs:["TGA","GMP"],skus:200,url:"https://blackmores.com.au",practOnly:false,aliases:["Blackmores Ltd"] },
  { name:"Solgar EU",tier:5,label:"Canadian/International",country:"USA",cats:["premium vitamins","minerals","herbs"],certs:["GMP"],skus:300,url:"https://solgar.com",practOnly:false,aliases:["Solgar Europe"] },
  { name:"Pharmako Biotechnologies",tier:5,label:"Canadian/International",country:"Australia",cats:["liposomal technology","specialty delivery"],certs:["GMP","TGA"],skus:30,url:"https://pharmako.com.au",practOnly:false,aliases:["Pharmako","Pharmako Biotech"] },
];

// Export for use in other scripts
export { BRANDS as SEED_BRANDS };
