// Testing & Diagnostics product info, content for the
// TestingProductInfoButtons accordion shown on each Testing
// category card in /shop. Hardcoded per Prompt #49h.
//
// `sku` is the canonical lookup key (matches MASTER_SKUS).
// `slug` is preserved per the prompt spec for any future routing.

export interface TestInfoItem {
  title: string;
  detail: string;
}

export interface TestInfoSection {
  id: string;
  label: string;
  icon: string; // Lucide icon name, see ICON_MAP in TestingProductInfoButtons
  items: TestInfoItem[];
}

export interface TestingProductInfo {
  sku: string;
  slug: string;
  name: string;
  subtitle: string;
  icon: string;
  badge?: string;
  marketingDescription: string;
  sections: TestInfoSection[];
}

export const TESTING_DIAGNOSTICS_INFO: TestingProductInfo[] = [
  // ── 1. GeneX360™ Complete Genetic Panel (SKU 61) ─────────────
  {
    sku: '61',
    slug: 'genex360-complete',
    name: 'GeneX360™ Complete Genetic Panel',
    subtitle: 'Combined Panels 2 to 7',
    icon: 'Dna',
    badge: 'MOST COMPREHENSIVE',
    marketingDescription:
      `The ultimate precision wellness blueprint, GeneX360™ combines all six of FarmCeutica's targeted genetic panels, GeneX-M, NutrigenDX, HormoneIQ, EpigenHQ, PeptideIQ, and CannabisIQ, into a single comprehensive test analyzing over 100 clinically relevant SNPs across methylation, nutrient metabolism, hormonal pathways, biological aging, peptide response, and cannabinoid sensitivity. GeneX360™ feeds directly into FarmCeutica's Ultrathink™ AI engine, generating a fully personalized supplement and peptide protocol calibrated to your unique genome, transforming generic wellness guesswork into precision-targeted, genetically informed formulations built for your biology alone.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'Methylation Pathway SNPs (20)', detail: 'MTHFR, COMT, CBS, MTR, MTRR, BHMT, MAOA, ACHY, ACAT, VDR, DAO, GST, SOD, NOS, SUOX, NAT, TCN2, RFC1, SHMT, ADO, complete methylation cycle mapping' },
          { title: 'Nutrient Metabolism Variants', detail: 'Vitamin D receptor sensitivity, omega-3 conversion capacity, iron absorption, fat-soluble vitamin transport, mineral utilization genetics' },
          { title: 'Hormonal Pathway Genetics', detail: 'Testosterone/estrogen metabolism, cortisol stress response, thyroid T4-to-T3 conversion, insulin sensitivity, reproductive hormone clearance' },
          { title: 'Epigenetic Aging Markers', detail: 'Telomere maintenance variants, DNA methylation clock markers, mitochondrial function SNPs, oxidative stress defense, cellular senescence pathways' },
          { title: 'Peptide Response Profile', detail: 'Peptide receptor density, GLP-1 pathway sensitivity, growth hormone secretagogue response, BPC-157 tissue repair capacity, neuropeptide metabolism' },
          { title: 'Cannabinoid Sensitivity Panel', detail: 'CB1/CB2 receptor density, FAAH enzyme activity, cytochrome P450 THC metabolism speed, COMT-mediated cannabis anxiety sensitivity' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'First-Time Genetic Testing', detail: 'Individuals who want the most complete picture of their genetic wellness profile in a single test, no need to purchase panels separately' },
          { title: 'Complex Health Histories', detail: 'Those with multiple overlapping health concerns spanning methylation, hormonal, digestive, neurological, and inflammatory domains' },
          { title: 'Precision Protocol Seekers', detail: 'Anyone ready to replace generic supplementation with a fully genome-matched protocol powered by Ultrathink™ AI' },
          { title: 'Practitioners & Naturopaths', detail: 'Clinicians who want comprehensive SNP data to build evidence-based, personalized treatment plans for their patients' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample, no blood draw required. Prepaid return shipping included. Results in 3 to 4 weeks.' },
          { title: 'Full 100+ SNP Genetic Report', detail: 'Detailed report covering all six panel domains with variant classification (homozygous, heterozygous, wild-type) and clinical significance ratings' },
          { title: 'Ultrathink™ AI Protocol', detail: `Personalized supplement and peptide recommendations generated by FarmCeutica's AI engine, matched to your exact genetic profile` },
          { title: 'Practitioner Consultation Prep', detail: 'Formatted clinical summary ready for review with your healthcare provider, naturopath, or FarmCeutica practitioner partner' },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results automatically sync to your ViaConnect dashboard, feeding your Bio Optimization Score, AI Wellness Analytics, and protocol engine' },
        ],
      },
    ],
  },

  // ── 2. GeneX-M™ Methylation Panel (SKU 57) ───────────────────
  {
    sku: '57',
    slug: 'genex-m-methylation',
    name: 'GeneX-M™ Methylation Panel',
    subtitle: '20 Targeted SNPs',
    icon: 'GitBranch',
    badge: 'METHYLATION CORE',
    marketingDescription:
      `GeneX-M™ analyzes 20 of the most clinically significant methylation-pathway SNPs, including MTHFR, COMT, CBS, MTR, MTRR, BHMT, MAOA, ACHY, ACAT, VDR, DAO, GST, SOD, NOS, SUOX, NAT, TCN2, RFC1, SHMT, and ADO, to reveal exactly how your body processes B-vitamins, clears neurotransmitters, detoxifies environmental compounds, and manages homocysteine.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'MTHFR (C677T & A1298C)', detail: 'Methylenetetrahydrofolate reductase, the gateway enzyme for folate metabolism. Variants reduce 5-MTHF production by 30 to 70%, impacting homocysteine clearance and DNA methylation' },
          { title: 'COMT (Val158Met)', detail: 'Catechol-O-methyltransferase, governs dopamine, norepinephrine, and estrogen clearance speed. Slow COMT = higher catecholamine levels, anxiety proneness' },
          { title: 'CBS (C699T & A360A)', detail: 'Cystathionine beta-synthase, controls transsulfuration pathway. Upregulations drive excess sulfur metabolites, ammonia, and taurine production' },
          { title: 'MTR / MTRR', detail: 'Methionine synthase and its reductase, the B12-dependent remethylation pathway converting homocysteine back to methionine for SAMe production' },
          { title: 'BHMT', detail: 'Betaine-homocysteine methyltransferase, the backup remethylation pathway using betaine (TMG) instead of folate. Critical when MTHFR is compromised' },
          { title: 'MAOA', detail: 'Monoamine oxidase A, breaks down serotonin, norepinephrine, and dopamine. Variants affect mood stability, impulse control, and carbohydrate cravings' },
          { title: 'VDR / DAO / GST / SOD', detail: 'Vitamin D receptor activation, diamine oxidase histamine clearance, glutathione transferase detox, and superoxide dismutase antioxidant defense' },
          { title: 'NOS / SUOX / NAT / TCN2 / RFC1 / SHMT / ADO / ACHY / ACAT', detail: 'Nitric oxide synthase, sulfite oxidase, N-acetyltransferase, B12 transport, folate transport, glycine-folate balance, purine metabolism, acetylcholine, and mitochondrial acetyl-CoA variants' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Methylation-Focused Individuals', detail: 'Anyone with known or suspected MTHFR variants, elevated homocysteine, or a history of poor response to standard B-vitamin supplements' },
          { title: 'Mood & Neurotransmitter Concerns', detail: 'Individuals experiencing anxiety, depression, brain fog, or mood instability that may have a methylation-pathway genetic component' },
          { title: 'Detoxification Support', detail: 'Those with chemical sensitivities, histamine intolerance, sulfite reactions, or difficulty clearing environmental toxins' },
          { title: 'Family Planning', detail: 'Women planning pregnancy who want to understand their folate metabolism and methylation capacity before conception' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: '20-SNP Methylation Report', detail: 'Each variant classified as homozygous, heterozygous, or wild-type with clinical significance and pathway impact explanation' },
          { title: 'Pathway-Specific Protocol', detail: `Direct mapping to FarmCeutica's 20 methylation support formulas (MTHFR+™, COMT+™, CBS Support+™, etc.), your genetics determine which formulas you need` },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results sync to your dashboard, unlocking Tier 3 (96%) protocol confidence in the Genetics Portal and Your Variants Explorer' },
        ],
      },
    ],
  },

  // ── 3. NutrigenDX™ Genetic Nutrition Panel (SKU 58) ──────────
  {
    sku: '58',
    slug: 'nutrigendx-nutrition',
    name: 'NutrigenDX™ Genetic Nutrition Panel',
    subtitle: 'Nutrient Metabolism & Absorption',
    icon: 'Apple',
    marketingDescription:
      `NutrigenDX™ maps the genetic variants that determine how your body absorbs, transports, converts, and utilizes essential vitamins, minerals, fatty acids, and antioxidants, revealing hidden inefficiencies that no blood test alone can explain.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'Vitamin D Metabolism', detail: 'VDR receptor sensitivity, CYP2R1 hydroxylation efficiency, GC protein binding and transport, determines your true D3 requirement and optimal form' },
          { title: 'Omega-3 Conversion', detail: 'FADS1/FADS2 desaturase variants controlling ALA-to-EPA/DHA conversion, reveals whether plant-based omega-3s are sufficient or direct DHA supplementation is needed' },
          { title: 'Iron Absorption & Storage', detail: 'HFE, TMPRSS6, and TFR2 variants affecting iron uptake, transferrin saturation, and ferritin storage, explains chronic deficiency or overload risk' },
          { title: 'B-Vitamin Utilization', detail: 'FUT2 (B12 absorption), NBPF3 (B6 metabolism), SLC19A1 (folate transport), identifies which B-vitamins need enhanced delivery forms' },
          { title: 'Fat-Soluble Vitamin Transport', detail: 'BCMO1 (beta-carotene to vitamin A conversion), APOA5/LPL (fat absorption), SCARB1 (vitamin E transport)' },
          { title: 'Mineral Metabolism', detail: 'SLC30A8 (zinc transport), ATP2B1 (calcium handling), SLC6A19 (amino acid absorption), TRPM6 (magnesium absorption)' },
          { title: 'Antioxidant Capacity', detail: 'SOD2, CAT, GPX1, endogenous antioxidant enzyme efficiency. Determines supplemental antioxidant requirements for oxidative stress management' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Persistent Nutrient Deficiencies', detail: 'Individuals whose blood work shows chronic low vitamin D, iron, B12, or other nutrients despite adequate dietary intake and standard supplementation' },
          { title: 'Dietary Optimization', detail: 'Those wanting to understand which nutrients their genetics struggle with so they can target diet and supplement choices precisely' },
          { title: 'Vegetarians & Vegans', detail: 'Plant-based individuals who need to know their conversion efficiency for nutrients like omega-3, B12, iron, and vitamin A from non-animal sources' },
          { title: 'Athletes & High-Performers', detail: 'Anyone with elevated nutrient turnover who wants to ensure their body is actually absorbing and utilizing what they consume' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: 'Nutrient Metabolism Report', detail: 'Each variant analyzed with absorption efficiency rating, recommended delivery forms (liposomal vs. micellar vs. standard), and optimal dosing guidance' },
          { title: 'Ultrathink™ AI Nutrition Protocol', detail: `Personalized supplement recommendations calibrated to your genetic nutrient bottlenecks, powered by FarmCeutica's AI engine` },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results feed directly into your AI Wellness Analytics and supplement protocol recommendations' },
        ],
      },
    ],
  },

  // ── 4. HormoneIQ™ Genetic Hormone Panel (SKU 59) ─────────────
  {
    sku: '59',
    slug: 'hormoneiq-hormone',
    name: 'HormoneIQ™ Genetic Hormone Panel',
    subtitle: 'Hormonal Pathway Genetics',
    icon: 'Activity',
    marketingDescription:
      `HormoneIQ™ decodes the genetic architecture governing your hormonal ecosystem, analyzing SNPs that influence testosterone and estrogen metabolism, cortisol stress response, thyroid hormone conversion, insulin sensitivity, and reproductive hormone clearance pathways.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'Estrogen Metabolism', detail: 'CYP1A1, CYP1B1, CYP3A4, COMT, the Phase I/II estrogen detoxification cascade. Determines 2-OH vs. 4-OH vs. 16-OH estrogen metabolite ratios and clearance speed' },
          { title: 'Testosterone Pathway', detail: 'SRD5A2 (5-alpha reductase / DHT conversion), AR (androgen receptor CAG repeat length), UGT2B17 (testosterone glucuronidation and clearance)' },
          { title: 'Cortisol & HPA Axis', detail: 'NR3C1 (glucocorticoid receptor sensitivity), FKBP5 (cortisol feedback regulation), CRHR1 (CRH receptor responsiveness), stress response genetics' },
          { title: 'Thyroid Conversion', detail: 'DIO1/DIO2 (deiodinase T4→T3 conversion), TSHR (TSH receptor sensitivity), TPO (thyroid peroxidase antibody risk)' },
          { title: 'Insulin Sensitivity', detail: 'TCF7L2 (beta-cell function), PPARG (insulin sensitization), IRS1 (insulin receptor signaling), metabolic hormone response' },
          { title: 'Reproductive Hormones', detail: 'SHBG (sex hormone binding globulin levels), ESR1/ESR2 (estrogen receptor variants), FSHR (follicle-stimulating hormone receptor sensitivity)' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Hormonal Imbalance Symptoms', detail: 'Men and women experiencing fatigue, weight resistance, low libido, mood swings, hair loss, or temperature sensitivity despite normal blood work' },
          { title: 'Age-Related Hormonal Shifts', detail: 'Individuals in perimenopause, menopause, or andropause seeking to understand the genetic factors influencing their hormonal transition' },
          { title: 'Fertility & Reproductive Health', detail: 'Couples planning pregnancy or individuals with unexplained fertility challenges wanting genetic hormone pathway insights' },
          { title: 'Athletic Performance', detail: 'Athletes seeking to understand their genetic testosterone, cortisol recovery, and thyroid metabolism profiles for training optimization' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: 'Hormonal Pathway Report', detail: 'Estrogen, testosterone, cortisol, thyroid, and insulin pathway analysis with genetic risk stratification and metabolite pathway diagrams' },
          { title: 'Targeted Hormone Protocol', detail: `Matched recommendations from FarmCeutica's hormonal product line, RISE+, DESIRE+, CycleSync+, MenoBalance+, ThyroBalance+, calibrated to your SNP profile` },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results integrated into your Bio Optimization Score and AI-driven hormone wellness analytics' },
        ],
      },
    ],
  },

  // ── 5. EpigenHQ™ Epigenetic Aging Panel (SKU 60) ─────────────
  {
    sku: '60',
    slug: 'epigenhq-aging',
    name: 'EpigenHQ™ Epigenetic Aging Panel',
    subtitle: 'Telomeres & Biological Aging',
    icon: 'Clock',
    marketingDescription:
      `EpigenHQ™ goes beyond chronological age to measure what truly matters, your biological age, by analyzing the genetic variants that influence telomere maintenance, DNA methylation clock markers, mitochondrial function, oxidative stress defense, and cellular senescence pathways.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'Telomere Maintenance', detail: 'TERT (telomerase reverse transcriptase), TERC (telomerase RNA component), POT1 (shelterin complex), your genetic capacity to maintain chromosome end-cap length' },
          { title: 'DNA Methylation Clock', detail: 'Epigenetic age acceleration markers based on CpG methylation patterns at key genomic loci, reveals biological vs. chronological age discrepancy' },
          { title: 'Mitochondrial Function', detail: 'PPARGC1A (PGC-1α mitochondrial biogenesis), TFAM (mitochondrial transcription), MT-ND variants (electron transport chain efficiency)' },
          { title: 'Oxidative Stress Defense', detail: 'SOD2 (manganese superoxide dismutase), CAT (catalase), GPX1 (glutathione peroxidase), endogenous antioxidant enzyme capacity' },
          { title: 'Cellular Senescence', detail: 'CDKN2A/p16 (senescence trigger), SIRT1/SIRT3 (sirtuin longevity pathways), FOXO3 (forkhead box longevity gene, one of the most replicated longevity associations)' },
          { title: 'NAD+ Metabolism', detail: 'NAMPT (NAD+ salvage pathway rate-limiting enzyme), PARP1 (NAD+ consumer for DNA repair), determines baseline NAD+ turnover and supplementation need' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Longevity-Focused Individuals', detail: 'Anyone proactively investing in healthspan extension who wants to understand their genetic aging vulnerabilities before symptoms appear' },
          { title: 'Accelerated Aging Concerns', detail: 'Those who feel or look older than their chronological age, or whose biomarkers suggest faster-than-expected biological aging' },
          { title: 'Existing Longevity Protocol Users', detail: 'Individuals already taking NMN, resveratrol, or other longevity compounds who want genetic data to optimize their regimen' },
          { title: 'Post-40 Health Optimization', detail: 'Men and women entering the decade where age-related decline accelerates, seeking a genetic roadmap for targeted intervention' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: 'Biological Age Report', detail: 'Your estimated biological age vs. chronological age, with breakdown by telomere, mitochondrial, oxidative, and senescence domains' },
          { title: 'Longevity Protocol Recommendations', detail: `Direct mapping to FarmCeutica's Teloprime+ Telomere Support, Replenish NAD+, and targeted antioxidant formulas based on your genetic aging profile` },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results power your Bio Optimization Score aging component and enable longitudinal biological age tracking over time' },
        ],
      },
    ],
  },

  // ── 6. PeptideIQ™ Genetic Peptide Response Panel (SKU 67) ────
  {
    sku: '67',
    slug: 'peptideiq-peptide',
    name: 'PeptideIQ™ Genetic Peptide Response Panel',
    subtitle: 'Peptide Metabolism & Sensitivity',
    icon: 'FlaskConical',
    marketingDescription:
      `PeptideIQ™ is the first consumer genetic panel designed specifically to predict individual response to therapeutic peptides, analyzing the SNPs that govern peptide receptor density, GLP-1 pathway sensitivity, growth hormone secretagogue response, BPC-157 tissue repair capacity, and neuropeptide metabolism.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'GLP-1 Pathway Sensitivity', detail: 'GLP1R receptor variants, DPP4 enzyme activity (incretin degradation speed), TCF7L2 (beta-cell response), predicts metabolic peptide efficacy' },
          { title: 'Growth Hormone Axis', detail: 'GHRHR (GH-releasing hormone receptor), GHR (growth hormone receptor sensitivity), IGF1 (insulin-like growth factor response)' },
          { title: 'BPC-157 Tissue Repair Capacity', detail: 'VEGF (vascular endothelial growth factor production), EGF receptor variants, NO synthase activity, determines healing peptide response potential' },
          { title: 'Neuropeptide Metabolism', detail: 'OPRM1 (opioid receptor), BDNF (brain-derived neurotrophic factor), NPY (neuropeptide Y stress response), cognitive and mood peptide targeting' },
          { title: 'Peptide Clearance Rate', detail: 'CYP3A4/CYP2D6 metabolizer status, ACE (angiotensin-converting enzyme), COMT, how quickly your body processes and clears therapeutic peptides' },
          { title: 'Delivery Form Optimization', detail: 'Gut permeability markers, first-pass metabolism genetics, and mucosal absorption variants, determines optimal route: liposomal, micellar, injectable, or nasal spray' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Peptide Therapy Candidates', detail: 'Anyone considering therapeutic peptides (BPC-157, GLP-1 agonists, growth hormone secretagogues) who wants genetic guidance before starting' },
          { title: 'Current Peptide Users', detail: 'Individuals already using peptides who want to optimize dosing, delivery form selection, and stacking strategies based on their genetics' },
          { title: 'Practitioners Prescribing Peptides', detail: 'Clinicians who want objective genetic data to guide peptide protocol design for their patients, moving beyond trial-and-error dosing' },
          { title: 'Weight Management', detail: 'Those exploring GLP-1 pathway activation who want to understand their genetic sensitivity to metabolic peptides before committing' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: 'Peptide Response Profile', detail: `Receptor sensitivity scores, metabolizer status, and delivery form recommendations across FarmCeutica's 29-peptide portfolio (113 total SKUs)` },
          { title: 'Matched Peptide Protocol', detail: 'AI-generated recommendations selecting from 28 oral peptides × 4 delivery forms + Retatrutide injectable, calibrated to your genetic response profile' },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results integrated into your supplement protocol engine, unlocking peptide-specific AI recommendations in the Recommended Supplements tab' },
        ],
      },
    ],
  },

  // ── 7. CannabisIQ™ Genetic Cannabinoid Panel (SKU 68) ────────
  {
    sku: '68',
    slug: 'cannabisiq-cannabinoid',
    name: 'CannabisIQ™ Genetic Cannabinoid Panel',
    subtitle: 'Cannabis & Cannabinoid Response',
    icon: 'Leaf',
    marketingDescription:
      `CannabisIQ™ analyzes the genetic variants that determine your unique endocannabinoid system, including CB1 and CB2 receptor density, FAAH enzyme activity governing anandamide breakdown, cytochrome P450 THC metabolism speed, and COMT-mediated sensitivity to cannabis-induced anxiety.`,
    sections: [
      {
        id: 'whats-tested',
        label: "What's Tested",
        icon: 'Search',
        items: [
          { title: 'CB1 Receptor Density (CNR1)', detail: 'Central nervous system cannabinoid receptor variants, determines baseline sensitivity to THC psychoactivity, appetite stimulation, and pain modulation' },
          { title: 'CB2 Receptor Variants (CNR2)', detail: 'Immune system cannabinoid receptor, influences anti-inflammatory response to CBD, immune modulation, and peripheral pain relief capacity' },
          { title: 'FAAH Enzyme Activity', detail: 'Fatty acid amide hydrolase, breaks down anandamide (the "bliss molecule"). Low FAAH activity = naturally higher endocannabinoid tone = different response to exogenous cannabinoids' },
          { title: 'THC Metabolism (CYP2C9 / CYP3A4)', detail: 'Cytochrome P450 enzyme variants controlling THC-to-11-OH-THC conversion speed. Slow metabolizers experience stronger, longer-lasting effects from the same dose' },
          { title: 'COMT Cannabis Anxiety', detail: 'Val158Met variant interaction with THC, slow COMT individuals have higher dopamine and are significantly more prone to THC-induced anxiety and paranoia' },
          { title: 'AKT1 Psychosis Risk', detail: 'AKT1 rs2494732 variant, associated with increased sensitivity to cannabis-induced psychotic symptoms, particularly in heavy users with the C/C genotype' },
          { title: 'Terpene Sensitivity', detail: 'TRPV1 (capsaicin receptor / beta-caryophyllene response), OR (olfactory receptor) variants, influences which terpene profiles produce optimal therapeutic effects' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Therapeutic Cannabis Users', detail: 'Patients using cannabinoids for pain, sleep, anxiety, inflammation, or neurological conditions who want genetically optimized ratios and dosing' },
          { title: 'Cannabis-Naive Individuals', detail: 'Those considering cannabis therapeutics for the first time who want to understand their genetic predisposition before their first experience' },
          { title: 'Adverse Reaction History', detail: 'Anyone who has experienced anxiety, paranoia, or excessive sedation from cannabis and wants to understand the genetic reasons and find better-suited products' },
          { title: 'Cannabis Practitioners', detail: 'Dispensary consultants and cannabis-friendly clinicians seeking objective genetic data to guide product selection and dosing for patients' },
        ],
      },
      {
        id: 'what-you-get',
        label: 'What You Get',
        icon: 'Package',
        items: [
          { title: 'At-Home Saliva Collection Kit', detail: 'Simple, painless saliva sample with prepaid return shipping. Results in 3 to 4 weeks.' },
          { title: 'Cannabinoid Sensitivity Report', detail: 'Personal THC sensitivity score, CBD response profile, metabolizer status (fast/normal/slow), anxiety risk assessment, and optimal THC:CBD ratio recommendation' },
          { title: 'Terpene Matching Profile', detail: 'Genetic terpene sensitivity analysis guiding selection of optimal cannabis cultivar profiles, myrcene, limonene, linalool, beta-caryophyllene, pinene' },
          { title: 'ViaConnect™ Portal Integration', detail: 'Results feed into your wellness profile, informing cannabinoid-related protocol recommendations and interaction warnings in the Medical & Herbal Interactions agent' },
        ],
      },
    ],
  },

  // ── 8. 30-Day Custom Vitamin Package (SKU 62) ────────────────
  {
    sku: '62',
    slug: '30-day-custom-vitamin',
    name: '30-Day Custom Vitamin Package',
    subtitle: 'Genome-Matched Daily Protocol',
    icon: 'Package',
    badge: 'PERSONALIZED',
    marketingDescription:
      `The culmination of FarmCeutica's precision wellness platform, your 30-Day Custom Vitamin Package is a fully personalized, pre-portioned daily supplement protocol built entirely from your GeneX360™ genetic test results and processed through the Ultrathink™ AI recommendation engine.`,
    sections: [
      {
        id: 'whats-included',
        label: "What's Included",
        icon: 'ListChecks',
        items: [
          { title: '30 Individual Daily Packets', detail: 'Pre-portioned, labeled daily packets containing your exact supplement combination, tear, pour, take. No pill organizers or guesswork required.' },
          { title: 'Methylation Support Formulas', detail: `Genetically matched selection from FarmCeutica's 20 methylation support products (MTHFR+™, COMT+™, etc.) based on your GeneX-M™ panel results` },
          { title: 'Targeted Advanced Formulas', detail: 'Personalized picks from FOCUS+, RELAX+, CATALYST+, Clean+, Balance+, Replenish NAD+, and other advanced formulas matched to your nutrient and pathway genetics' },
          { title: 'Precision Peptide Inclusion', detail: 'If your PeptideIQ™ results indicate benefit, targeted peptides from the 29-peptide portfolio in your genetically optimal delivery form (liposomal, micellar, injectable, or nasal spray)' },
          { title: 'Hormonal & Specialty Add-Ons', detail: 'Gender-specific and condition-specific formulas (RISE+, CycleSync+, ThyroBalance+, etc.) included when your HormoneIQ™ data warrants them' },
        ],
      },
      {
        id: 'how-it-works',
        label: 'How It Works',
        icon: 'Workflow',
        items: [
          { title: 'Step 1: Complete Your Genetic Test', detail: 'Any GeneX360™ panel (or the Complete Panel) provides the genetic data the AI engine needs. More panels = more precise protocol.' },
          { title: 'Step 2: Ultrathink™ AI Builds Your Protocol', detail: `FarmCeutica's AI engine analyzes your SNP data, cross-references with CAQ health questionnaire responses, and generates your personalized daily supplement stack` },
          { title: 'Step 3: Monthly Delivery', detail: 'Your custom 30-day packet arrives at your door. Protocol is recalibrated monthly as your Bio Optimization Score evolves and new health data enters the system.' },
          { title: 'Step 4: Track & Optimize', detail: 'Monitor your progress through ViaConnect™, Bio Optimization Score, AI Wellness Analytics, and daily protocol adherence tracking through Helix Rewards gamification' },
        ],
      },
      {
        id: 'who-its-for',
        label: "Who It's For",
        icon: 'Users',
        items: [
          { title: 'Supplement Simplifiers', detail: 'Anyone overwhelmed by choosing from 60+ products who wants the AI to select exactly what they need, no more, no less, in a single convenient daily packet' },
          { title: 'Maximum Personalization', detail: `Individuals who've completed genetic testing and want the highest level of protocol precision, every capsule in your packet is there because your genome says it should be` },
          { title: 'Compliance Optimizers', detail: 'Those who struggle with complex supplement regimens and want pre-portioned daily packets that eliminate decision fatigue and ensure consistent adherence' },
          { title: 'Ongoing Wellness Members', detail: 'ViaConnect™ platform users who want their protocol to evolve automatically as their Bio Optimization Score and health data change over time' },
        ],
      },
    ],
  },
];

export const getTestingProductBySlug = (slug: string): TestingProductInfo | undefined =>
  TESTING_DIAGNOSTICS_INFO.find((p) => p.slug === slug);

export const getTestingProductBySku = (sku: string): TestingProductInfo | undefined =>
  TESTING_DIAGNOSTICS_INFO.find((p) => p.sku === sku);
