-- Prompt 221 Phase 2: competitive_sources allowlist expansion.
-- Gary-approved 2026-08-17 (operator: expand from competitor database seed docs).
-- Append-only INSERT. Does NOT bulk-seed product rows.

INSERT INTO public.competitive_sources (
  domain, label, source_kind, category_tags, base_url,
  approval_status, proposed_by, approved_by, notes
) VALUES
  ('codeage.com', 'Codeage', 'brand',
    ARRAY['advanced-formulas','liposomal','base-formulations'],
    'https://www.codeage.com', 'approved', 'hounddog', 'gary',
    'Liposomal / longevity DTC competitor (docx seed)'),
  ('metagenics.com', 'Metagenics', 'brand',
    ARRAY['base-formulations','advanced-formulas','methylation-snp'],
    'https://www.metagenics.com', 'approved', 'hounddog', 'gary',
    'Practitioner medical foods / clinical competitor'),
  ('organika.com', 'Organika', 'brand',
    ARRAY['base-formulations','womens-health','advanced-formulas'],
    'https://organika.com', 'approved', 'hounddog', 'gary',
    'Canadian collagen / NHP competitor'),
  ('aor.ca', 'AOR', 'brand',
    ARRAY['base-formulations','advanced-formulas','methylation-snp'],
    'https://www.aor.ca', 'approved', 'hounddog', 'gary',
    'Canadian research-grade competitor (MyBlueprint adjacency)'),
  ('canprev.ca', 'CanPrev', 'brand',
    ARRAY['womens-health','base-formulations','advanced-formulas'],
    'https://canprev.ca', 'approved', 'hounddog', 'gary',
    'Canadian practitioner / women health competitor'),
  ('solgar.com', 'Solgar', 'brand',
    ARRAY['base-formulations','advanced-formulas'],
    'https://www.solgar.com', 'approved', 'hounddog', 'gary',
    'Legacy gold-standard retail competitor'),
  ('orthomolecularproducts.com', 'Ortho Molecular Products', 'brand',
    ARRAY['advanced-formulas','base-formulations','methylation-snp'],
    'https://www.orthomolecularproducts.com', 'approved', 'hounddog', 'gary',
    'Practitioner-only immune / GI competitor'),
  ('integrativepro.com', 'Integrative Therapeutics', 'brand',
    ARRAY['advanced-formulas','base-formulations'],
    'https://www.integrativepro.com', 'approved', 'hounddog', 'gary',
    'Enzyme / cortisol / curcumin competitor'),
  ('doctorsbest.com', 'Doctor''s Best', 'brand',
    ARRAY['base-formulations','advanced-formulas'],
    'https://www.doctorsbest.com', 'approved', 'hounddog', 'gary',
    'Branded-ingredient consumer competitor'),
  ('cymbiotika.com', 'Cymbiotika', 'brand',
    ARRAY['advanced-formulas','liposomal','base-formulations'],
    'https://cymbiotika.com', 'approved', 'hounddog', 'gary',
    'Liposomal DTC competitor'),
  ('renuebyscience.com', 'Renue by Science', 'brand',
    ARRAY['advanced-formulas','base-formulations'],
    'https://renuebyscience.com', 'approved', 'hounddog', 'gary',
    'NAD / longevity competitor'),
  ('seed.com', 'Seed Health', 'brand',
    ARRAY['advanced-formulas','base-formulations','womens-health'],
    'https://seed.com', 'approved', 'hounddog', 'gary',
    'Synbiotic / ViaCap competitor'),
  ('sisu.com', 'SISU', 'brand',
    ARRAY['base-formulations','advanced-formulas'],
    'https://www.sisu.com', 'approved', 'hounddog', 'gary',
    'Canadian Ester-C / NHP competitor'),
  ('im8health.com', 'IM8 Health', 'brand',
    ARRAY['advanced-formulas','base-formulations'],
    'https://im8health.com', 'approved', 'hounddog', 'gary',
    'All-in-one / longevity DTC competitor'),
  ('innosupps.com', 'Inno Supps', 'brand',
    ARRAY['advanced-formulas','base-formulations'],
    'https://www.innosupps.com', 'approved', 'hounddog', 'gary',
    'Fitness DTC / fat burner competitor')
ON CONFLICT (domain) DO UPDATE SET
  approval_status = 'approved',
  is_active = true,
  approved_by = 'gary',
  label = EXCLUDED.label,
  category_tags = EXCLUDED.category_tags,
  base_url = EXCLUDED.base_url,
  notes = EXCLUDED.notes,
  updated_at = now();
