-- Prompt 192 (2026-06-12): persisted Nutrition Insights store. Generated by
-- the Gordon insight engine (deterministic detectors + LLM copy composition,
-- Kelsey compliance lint before display). Append only. Consumers SELECT and
-- UPDATE (status changes) their own rows only; INSERTs come from the service
-- role inside the scheduled runs and the on demand refresh. No practitioner
-- or naturopath access in this prompt. No delete policy.
-- Applied to live via MCP 2026-06-12.

create table public.nutrition_insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  insight_type text not null check (insight_type in (
    'macro_gap','micronutrient_gap','meal_timing_pattern','hydration_correlation',
    'supplement_meal_alignment','quality_trend','consistency_streak','score_mover'
  )),
  horizon text not null check (horizon in ('meal','daily','weekly')),
  title text not null,
  body text not null,
  severity text not null default 'info' check (severity in ('info','attention','positive')),
  confidence text not null check (confidence in ('high','medium','low')),
  data_snapshot jsonb not null,
  product_suggestion jsonb,
  status text not null default 'active' check (status in ('active','read','dismissed','saved','expired')),
  generated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  compliance_passed boolean not null default false
);

comment on table public.nutrition_insights is
  'Prompt 192: Gordon generated nutrition insights. data_snapshot holds the exact computed facts the copy was written from (auditable, drives the Why am I seeing this panel). Only compliance_passed rows are ever displayed.';

create index idx_nutrition_insights_user_active
  on public.nutrition_insights (user_id, status, generated_at desc);

alter table public.nutrition_insights enable row level security;

create policy "ni_select_own" on public.nutrition_insights
  for select to authenticated
  using (auth.uid() = user_id);

create policy "ni_update_own" on public.nutrition_insights
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Thumbs up / down feedback per insight.
create table public.nutrition_insight_feedback (
  id uuid primary key default gen_random_uuid(),
  insight_id uuid not null references public.nutrition_insights(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  helpful boolean not null,
  created_at timestamptz not null default now()
);

create index idx_nutrition_insight_feedback_insight
  on public.nutrition_insight_feedback (insight_id, created_at desc);

alter table public.nutrition_insight_feedback enable row level security;

create policy "nif_select_own" on public.nutrition_insight_feedback
  for select to authenticated
  using (auth.uid() = user_id);

create policy "nif_insert_own" on public.nutrition_insight_feedback
  for insert to authenticated
  with check (auth.uid() = user_id);

-- Engine run ledger: powers the 202 run id response, the 10 minute on demand
-- rate limit window, and run observability. Service role writes; owner reads.
create table public.nutrition_insight_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  trigger text not null check (trigger in ('daily','weekly','manual')),
  status text not null default 'running' check (status in ('running','done','failed')),
  inserted_count integer not null default 0,
  failure_reason text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index idx_nutrition_insight_runs_user_started
  on public.nutrition_insight_runs (user_id, trigger, started_at desc);

alter table public.nutrition_insight_runs enable row level security;

create policy "nir_select_own" on public.nutrition_insight_runs
  for select to authenticated
  using (auth.uid() = user_id);
