-- =============================================================================
-- Prompt 210f Task F3b: practitioner_invitations ADDITIVE slice (plan-gap closure)
-- =============================================================================
-- Gary Decision 2 (2026-07-07): F3b closes the practitioner_invitations gap
-- omitted from the F3 coverage list. The source migration
-- (20260418000030_practitioner_invitations.sql) was excluded from F3 because
-- the 210f execution plan listed five tables only and _030 was not among them.
-- Live-referenced phantoms that remain broken without this slice:
--   practitioner_invitations write at src/lib/practitioner/invitations.ts:52
--   validate_practitioner_invitation rpc call at :92
--
-- Assembled from the single source migration, in its original order:
--   1. 20260418000030_practitioner_invitations.sql
--
-- Destructive statements found in the source: ONE (DROP POLICY IF EXISTS
-- "invitations_admin_all" on public.practitioner_invitations). This is an
-- adjacent idempotent recreate pair and is converted to a pg_policies-guarded
-- DO block per the 210f F1/F3 extraction convention. No DROP carried. Not
-- recorded in the evidence pack (handled inline, not deferred).
--
-- Conversions applied during extraction, mirroring F1/F3:
--   * DROP POLICY IF EXISTS + CREATE POLICY adjacency pair becomes a DO block
--     gated on pg_policies (no DROP carried). Original policy name kept.
--   * Bare auth.uid() in the policy body wrapped to (select auth.uid()) per
--     the repo initplan remediation (see 20260622180000).
--   * validate_practitioner_invitation RPC emitted as CREATE OR REPLACE,
--     retaining its source SECURITY DEFINER, SET search_path = public, pg_temp
--     pin, and REVOKE/GRANT pair verbatim.
--   * No seeds in this source; no seed block added.
--
-- Code-consumer column cross-check (src/lib/practitioner/invitations.ts):
--   Insert payload (line 52): token, invited_by, target_email,
--     expected_credential_type, personal_note, expires_at -- all present in
--     the source table. No gap; STOP not triggered.
--   RPC args (line 92): p_token TEXT, p_claim BOOLEAN DEFAULT false -- match
--     the function signature exactly.
--   RPC return columns (lines 102-112): ok, target_email,
--     expected_credential_type, personal_note, invited_by_display -- all
--     present in the RETURNS TABLE clause. No gap.
--
-- Shape test: src/lib/__tests__/practitioner-invitations-migration-shape.test.ts
-- parses this file. DO NOT add destructive statements here; the test fails on
-- any DROP token.
-- =============================================================================

-- =============================================================================
-- SECTION 1 of 1: from 20260418000030_practitioner_invitations.sql
-- =============================================================================
-- VIP invitation tokens generated by admins. Each token has a 60-day expiry,
-- one-time use semantics, and an optional personal note that renders on the
-- invited landing page.

CREATE TABLE IF NOT EXISTS public.practitioner_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT NOT NULL UNIQUE,
  invited_by UUID NOT NULL REFERENCES auth.users(id),
  target_email TEXT,
  expected_credential_type TEXT CHECK (
    expected_credential_type IS NULL OR expected_credential_type IN (
      'md', 'do', 'nd', 'dc', 'np', 'pa', 'rd', 'lac', 'other'
    )
  ),
  personal_note TEXT,
  used_at TIMESTAMPTZ,
  used_by UUID REFERENCES auth.users(id),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.practitioner_invitations IS
  'VIP practitioner invitation tokens. Generated by admins, single-use, 60-day expiry by default.';

CREATE INDEX IF NOT EXISTS idx_practitioner_invitations_open
  ON public.practitioner_invitations(token) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_practitioner_invitations_invited_by
  ON public.practitioner_invitations(invited_by);

ALTER TABLE public.practitioner_invitations ENABLE ROW LEVEL SECURITY;

-- Admin-only writes. Token validation happens via a security-definer RPC so
-- anonymous users can verify a token without seeing the rest of the table.
-- Source DROP POLICY IF EXISTS + CREATE POLICY pair converted to a pg_policies
-- guard per the 210f extraction convention (no DROP carried).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'practitioner_invitations'
      AND policyname = 'invitations_admin_all'
  ) THEN
    CREATE POLICY "invitations_admin_all"
      ON public.practitioner_invitations FOR ALL
      TO authenticated
      USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = (select auth.uid()) AND role = 'admin')
      )
      WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = (select auth.uid()) AND role = 'admin')
      );
  END IF;
END $$;

-- Public token validator. Returns invitation context to anon callers without
-- exposing the bulk of the table. Only valid (unused, unexpired) tokens
-- return a row. Marks the token used when claim=true is passed.
CREATE OR REPLACE FUNCTION public.validate_practitioner_invitation(
  p_token TEXT,
  p_claim BOOLEAN DEFAULT false
)
RETURNS TABLE (
  ok BOOLEAN,
  target_email TEXT,
  expected_credential_type TEXT,
  personal_note TEXT,
  invited_by_display TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  r record;
  v_rows INTEGER;
BEGIN
  SELECT i.id, i.target_email, i.expected_credential_type, i.personal_note,
         coalesce(p.first_name || ' ' || p.last_name, 'A ViaCura founder') AS invited_by_display
  INTO r
  FROM public.practitioner_invitations i
  LEFT JOIN public.profiles p ON p.id = i.invited_by
  WHERE i.token = p_token
    AND i.used_at IS NULL
    AND i.expires_at > now()
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
    RETURN;
  END IF;

  IF p_claim THEN
    -- Atomic claim: only one concurrent caller wins. The losing caller sees
    -- ROW_COUNT = 0 and is told the invitation is no longer valid.
    UPDATE public.practitioner_invitations
       SET used_at = now()
     WHERE id = r.id AND used_at IS NULL;
    GET DIAGNOSTICS v_rows = ROW_COUNT;

    IF v_rows = 0 THEN
      RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
      RETURN;
    END IF;
  END IF;

  RETURN QUERY SELECT true, r.target_email, r.expected_credential_type, r.personal_note, r.invited_by_display;
END;
$$;

REVOKE ALL ON FUNCTION public.validate_practitioner_invitation(TEXT, BOOLEAN) FROM public;
GRANT EXECUTE ON FUNCTION public.validate_practitioner_invitation(TEXT, BOOLEAN) TO anon, authenticated;
