-- Prompt 223 location reference seeds.
-- Sources and licenses:
--   ISO 3166-1/2 country and subdivision codes: ISO standard codes with English short names.
--   Natural Earth 10m populated places: public domain, https://www.naturalearthdata.com
--   US Census Gazetteer / incorporated places: public domain, https://www.census.gov
-- is_free_entry_origin is false on all seed rows.
-- No coordinates are stored.

-- Countries: full ISO 3166-1 alpha-2 English short names.

INSERT INTO public.ref_countries (code, name, name_normalized)
VALUES
  ('AD', 'Andorra', 'andorra'),
  ('AE', 'United Arab Emirates', 'united arab emirates'),
  ('AF', 'Afghanistan', 'afghanistan'),
  ('AG', 'Antigua and Barbuda', 'antigua and barbuda'),
  ('AI', 'Anguilla', 'anguilla'),
  ('AL', 'Albania', 'albania'),
  ('AM', 'Armenia', 'armenia'),
  ('AO', 'Angola', 'angola'),
  ('AQ', 'Antarctica', 'antarctica'),
  ('AR', 'Argentina', 'argentina'),
  ('AS', 'American Samoa', 'american samoa'),
  ('AT', 'Austria', 'austria'),
  ('AU', 'Australia', 'australia'),
  ('AW', 'Aruba', 'aruba'),
  ('AX', 'Aland Islands', 'aland islands'),
  ('AZ', 'Azerbaijan', 'azerbaijan'),
  ('BA', 'Bosnia and Herzegovina', 'bosnia and herzegovina'),
  ('BB', 'Barbados', 'barbados'),
  ('BD', 'Bangladesh', 'bangladesh'),
  ('BE', 'Belgium', 'belgium'),
  ('BF', 'Burkina Faso', 'burkina faso'),
  ('BG', 'Bulgaria', 'bulgaria'),
  ('BH', 'Bahrain', 'bahrain'),
  ('BI', 'Burundi', 'burundi'),
  ('BJ', 'Benin', 'benin'),
  ('BL', 'Saint Barthelemy', 'saint barthelemy'),
  ('BM', 'Bermuda', 'bermuda'),
  ('BN', 'Brunei Darussalam', 'brunei darussalam'),
  ('BO', 'Bolivia', 'bolivia'),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'bonaire, sint eustatius and saba'),
  ('BR', 'Brazil', 'brazil'),
  ('BS', 'Bahamas', 'bahamas'),
  ('BT', 'Bhutan', 'bhutan'),
  ('BV', 'Bouvet Island', 'bouvet island'),
  ('BW', 'Botswana', 'botswana'),
  ('BY', 'Belarus', 'belarus'),
  ('BZ', 'Belize', 'belize'),
  ('CA', 'Canada', 'canada'),
  ('CC', 'Cocos (Keeling) Islands', 'cocos (keeling) islands'),
  ('CD', 'Congo (the Democratic Republic of the)', 'congo (the democratic republic of the)'),
  ('CF', 'Central African Republic', 'central african republic'),
  ('CG', 'Congo', 'congo'),
  ('CH', 'Switzerland', 'switzerland'),
  ('CI', 'Cote d''Ivoire', 'cote d''ivoire'),
  ('CK', 'Cook Islands', 'cook islands'),
  ('CL', 'Chile', 'chile'),
  ('CM', 'Cameroon', 'cameroon'),
  ('CN', 'China', 'china'),
  ('CO', 'Colombia', 'colombia'),
  ('CR', 'Costa Rica', 'costa rica'),
  ('CU', 'Cuba', 'cuba'),
  ('CV', 'Cabo Verde', 'cabo verde'),
  ('CW', 'Curacao', 'curacao'),
  ('CX', 'Christmas Island', 'christmas island'),
  ('CY', 'Cyprus', 'cyprus'),
  ('CZ', 'Czechia', 'czechia'),
  ('DE', 'Germany', 'germany'),
  ('DJ', 'Djibouti', 'djibouti'),
  ('DK', 'Denmark', 'denmark'),
  ('DM', 'Dominica', 'dominica'),
  ('DO', 'Dominican Republic', 'dominican republic'),
  ('DZ', 'Algeria', 'algeria'),
  ('EC', 'Ecuador', 'ecuador'),
  ('EE', 'Estonia', 'estonia'),
  ('EG', 'Egypt', 'egypt'),
  ('EH', 'Western Sahara', 'western sahara'),
  ('ER', 'Eritrea', 'eritrea'),
  ('ES', 'Spain', 'spain'),
  ('ET', 'Ethiopia', 'ethiopia'),
  ('FI', 'Finland', 'finland'),
  ('FJ', 'Fiji', 'fiji'),
  ('FK', 'Falkland Islands', 'falkland islands'),
  ('FM', 'Micronesia', 'micronesia'),
  ('FO', 'Faroe Islands', 'faroe islands'),
  ('FR', 'France', 'france'),
  ('GA', 'Gabon', 'gabon'),
  ('GB', 'United Kingdom of Great Britain and Northern Ireland', 'united kingdom of great britain and northern ireland'),
  ('GD', 'Grenada', 'grenada'),
  ('GE', 'Georgia', 'georgia'),
  ('GF', 'French Guiana', 'french guiana'),
  ('GG', 'Guernsey', 'guernsey'),
  ('GH', 'Ghana', 'ghana'),
  ('GI', 'Gibraltar', 'gibraltar'),
  ('GL', 'Greenland', 'greenland'),
  ('GM', 'Gambia', 'gambia'),
  ('GN', 'Guinea', 'guinea'),
  ('GP', 'Guadeloupe', 'guadeloupe'),
  ('GQ', 'Equatorial Guinea', 'equatorial guinea'),
  ('GR', 'Greece', 'greece'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'south georgia and the south sandwich islands'),
  ('GT', 'Guatemala', 'guatemala'),
  ('GU', 'Guam', 'guam'),
  ('GW', 'Guinea-Bissau', 'guinea-bissau'),
  ('GY', 'Guyana', 'guyana'),
  ('HK', 'Hong Kong', 'hong kong'),
  ('HM', 'Heard Island and McDonald Islands', 'heard island and mcdonald islands'),
  ('HN', 'Honduras', 'honduras'),
  ('HR', 'Croatia', 'croatia'),
  ('HT', 'Haiti', 'haiti'),
  ('HU', 'Hungary', 'hungary'),
  ('ID', 'Indonesia', 'indonesia'),
  ('IE', 'Ireland', 'ireland'),
  ('IL', 'Israel', 'israel'),
  ('IM', 'Isle of Man', 'isle of man'),
  ('IN', 'India', 'india'),
  ('IO', 'British Indian Ocean Territory', 'british indian ocean territory'),
  ('IQ', 'Iraq', 'iraq'),
  ('IR', 'Iran', 'iran'),
  ('IS', 'Iceland', 'iceland'),
  ('IT', 'Italy', 'italy'),
  ('JE', 'Jersey', 'jersey'),
  ('JM', 'Jamaica', 'jamaica'),
  ('JO', 'Jordan', 'jordan'),
  ('JP', 'Japan', 'japan'),
  ('KE', 'Kenya', 'kenya'),
  ('KG', 'Kyrgyzstan', 'kyrgyzstan'),
  ('KH', 'Cambodia', 'cambodia'),
  ('KI', 'Kiribati', 'kiribati'),
  ('KM', 'Comoros', 'comoros'),
  ('KN', 'Saint Kitts and Nevis', 'saint kitts and nevis'),
  ('KP', 'North Korea', 'north korea'),
  ('KR', 'South Korea', 'south korea'),
  ('KW', 'Kuwait', 'kuwait'),
  ('KY', 'Cayman Islands', 'cayman islands'),
  ('KZ', 'Kazakhstan', 'kazakhstan'),
  ('LA', 'Laos', 'laos'),
  ('LB', 'Lebanon', 'lebanon'),
  ('LC', 'Saint Lucia', 'saint lucia'),
  ('LI', 'Liechtenstein', 'liechtenstein'),
  ('LK', 'Sri Lanka', 'sri lanka'),
  ('LR', 'Liberia', 'liberia'),
  ('LS', 'Lesotho', 'lesotho'),
  ('LT', 'Lithuania', 'lithuania'),
  ('LU', 'Luxembourg', 'luxembourg'),
  ('LV', 'Latvia', 'latvia'),
  ('LY', 'Libya', 'libya'),
  ('MA', 'Morocco', 'morocco'),
  ('MC', 'Monaco', 'monaco'),
  ('MD', 'Moldova', 'moldova'),
  ('ME', 'Montenegro', 'montenegro'),
  ('MF', 'Saint Martin', 'saint martin'),
  ('MG', 'Madagascar', 'madagascar'),
  ('MH', 'Marshall Islands', 'marshall islands'),
  ('MK', 'North Macedonia', 'north macedonia'),
  ('ML', 'Mali', 'mali'),
  ('MM', 'Myanmar', 'myanmar'),
  ('MN', 'Mongolia', 'mongolia'),
  ('MO', 'Macao', 'macao'),
  ('MP', 'Northern Mariana Islands', 'northern mariana islands'),
  ('MQ', 'Martinique', 'martinique'),
  ('MR', 'Mauritania', 'mauritania'),
  ('MS', 'Montserrat', 'montserrat'),
  ('MT', 'Malta', 'malta'),
  ('MU', 'Mauritius', 'mauritius'),
  ('MV', 'Maldives', 'maldives'),
  ('MW', 'Malawi', 'malawi'),
  ('MX', 'Mexico', 'mexico'),
  ('MY', 'Malaysia', 'malaysia'),
  ('MZ', 'Mozambique', 'mozambique'),
  ('NA', 'Namibia', 'namibia'),
  ('NC', 'New Caledonia', 'new caledonia'),
  ('NE', 'Niger', 'niger'),
  ('NF', 'Norfolk Island', 'norfolk island'),
  ('NG', 'Nigeria', 'nigeria'),
  ('NI', 'Nicaragua', 'nicaragua'),
  ('NL', 'Netherlands', 'netherlands'),
  ('NO', 'Norway', 'norway'),
  ('NP', 'Nepal', 'nepal'),
  ('NR', 'Nauru', 'nauru'),
  ('NU', 'Niue', 'niue'),
  ('NZ', 'New Zealand', 'new zealand'),
  ('OM', 'Oman', 'oman'),
  ('PA', 'Panama', 'panama'),
  ('PE', 'Peru', 'peru'),
  ('PF', 'French Polynesia', 'french polynesia'),
  ('PG', 'Papua New Guinea', 'papua new guinea'),
  ('PH', 'Philippines', 'philippines'),
  ('PK', 'Pakistan', 'pakistan'),
  ('PL', 'Poland', 'poland'),
  ('PM', 'Saint Pierre and Miquelon', 'saint pierre and miquelon'),
  ('PN', 'Pitcairn', 'pitcairn'),
  ('PR', 'Puerto Rico', 'puerto rico'),
  ('PS', 'Palestine', 'palestine'),
  ('PT', 'Portugal', 'portugal'),
  ('PW', 'Palau', 'palau'),
  ('PY', 'Paraguay', 'paraguay'),
  ('QA', 'Qatar', 'qatar'),
  ('RE', 'Reunion', 'reunion'),
  ('RO', 'Romania', 'romania'),
  ('RS', 'Serbia', 'serbia'),
  ('RU', 'Russian Federation', 'russian federation'),
  ('RW', 'Rwanda', 'rwanda'),
  ('SA', 'Saudi Arabia', 'saudi arabia'),
  ('SB', 'Solomon Islands', 'solomon islands'),
  ('SC', 'Seychelles', 'seychelles'),
  ('SD', 'Sudan', 'sudan'),
  ('SE', 'Sweden', 'sweden'),
  ('SG', 'Singapore', 'singapore'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'saint helena, ascension and tristan da cunha'),
  ('SI', 'Slovenia', 'slovenia'),
  ('SJ', 'Svalbard and Jan Mayen', 'svalbard and jan mayen'),
  ('SK', 'Slovakia', 'slovakia'),
  ('SL', 'Sierra Leone', 'sierra leone'),
  ('SM', 'San Marino', 'san marino'),
  ('SN', 'Senegal', 'senegal'),
  ('SO', 'Somalia', 'somalia'),
  ('SR', 'Suriname', 'suriname'),
  ('SS', 'South Sudan', 'south sudan'),
  ('ST', 'Sao Tome and Principe', 'sao tome and principe'),
  ('SV', 'El Salvador', 'el salvador'),
  ('SX', 'Sint Maarten', 'sint maarten'),
  ('SY', 'Syria', 'syria'),
  ('SZ', 'Eswatini', 'eswatini'),
  ('TC', 'Turks and Caicos Islands', 'turks and caicos islands'),
  ('TD', 'Chad', 'chad'),
  ('TF', 'French Southern Territories', 'french southern territories'),
  ('TG', 'Togo', 'togo'),
  ('TH', 'Thailand', 'thailand'),
  ('TJ', 'Tajikistan', 'tajikistan'),
  ('TK', 'Tokelau', 'tokelau'),
  ('TL', 'Timor-Leste', 'timor-leste'),
  ('TM', 'Turkmenistan', 'turkmenistan'),
  ('TN', 'Tunisia', 'tunisia'),
  ('TO', 'Tonga', 'tonga'),
  ('TR', 'Turkiye', 'turkiye'),
  ('TT', 'Trinidad and Tobago', 'trinidad and tobago'),
  ('TV', 'Tuvalu', 'tuvalu'),
  ('TW', 'Taiwan', 'taiwan'),
  ('TZ', 'Tanzania', 'tanzania'),
  ('UA', 'Ukraine', 'ukraine'),
  ('UG', 'Uganda', 'uganda'),
  ('UM', 'United States Minor Outlying Islands', 'united states minor outlying islands'),
  ('US', 'United States of America', 'united states of america'),
  ('UY', 'Uruguay', 'uruguay'),
  ('UZ', 'Uzbekistan', 'uzbekistan'),
  ('VA', 'Holy See', 'holy see'),
  ('VC', 'Saint Vincent and the Grenadines', 'saint vincent and the grenadines'),
  ('VE', 'Venezuela', 'venezuela'),
  ('VG', 'Virgin Islands (British)', 'virgin islands (british)'),
  ('VI', 'Virgin Islands (U.S.)', 'virgin islands (u.s.)'),
  ('VN', 'Viet Nam', 'viet nam'),
  ('VU', 'Vanuatu', 'vanuatu'),
  ('WF', 'Wallis and Futuna', 'wallis and futuna'),
  ('WS', 'Samoa', 'samoa'),
  ('XK', 'Kosovo', 'kosovo'),
  ('YE', 'Yemen', 'yemen'),
  ('YT', 'Mayotte', 'mayotte'),
  ('ZA', 'South Africa', 'south africa'),
  ('ZM', 'Zambia', 'zambia'),
  ('ZW', 'Zimbabwe', 'zimbabwe')
ON CONFLICT (code) DO NOTHING;
