-- =============================================================================
-- Prompt #91, Phase 1.5: Practitioner invitations
-- =============================================================================
-- Append-only. VIP invitation tokens generated by admins. Each token has a
-- 60-day expiry, one-time use semantics, and an optional personal note that
-- renders on the invited landing page.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.practitioner_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT NOT NULL UNIQUE,
  invited_by UUID NOT NULL REFERENCES auth.users(id),
  target_email TEXT,
  expected_credential_type TEXT CHECK (
    expected_credential_type IS NULL OR expected_credential_type IN (
      'md', 'do', 'nd', 'dc', 'np', 'pa', 'rd', 'lac', 'other'
    )
  ),
  personal_note TEXT,
  used_at TIMESTAMPTZ,
  used_by UUID REFERENCES auth.users(id),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.practitioner_invitations IS
  'VIP practitioner invitation tokens. Generated by admins, single-use, 60-day expiry by default.';

CREATE INDEX IF NOT EXISTS idx_practitioner_invitations_open
  ON public.practitioner_invitations(token) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_practitioner_invitations_invited_by
  ON public.practitioner_invitations(invited_by);

ALTER TABLE public.practitioner_invitations ENABLE ROW LEVEL SECURITY;

-- Admin-only writes. Token validation happens via a security-definer RPC so
-- anonymous users can verify a token without seeing the rest of the table.
DROP POLICY IF EXISTS "invitations_admin_all" ON public.practitioner_invitations;
CREATE POLICY "invitations_admin_all"
  ON public.practitioner_invitations FOR ALL
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Public token validator. Returns invitation context to anon callers without
-- exposing the bulk of the table. Only valid (unused, unexpired) tokens
-- return a row. Marks the token used when claim=true is passed.
CREATE OR REPLACE FUNCTION public.validate_practitioner_invitation(
  p_token TEXT,
  p_claim BOOLEAN DEFAULT false
)
RETURNS TABLE (
  ok BOOLEAN,
  target_email TEXT,
  expected_credential_type TEXT,
  personal_note TEXT,
  invited_by_display TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  r record;
  v_rows INTEGER;
BEGIN
  SELECT i.id, i.target_email, i.expected_credential_type, i.personal_note,
         coalesce(p.first_name || ' ' || p.last_name, 'A ViaCura founder') AS invited_by_display
  INTO r
  FROM public.practitioner_invitations i
  LEFT JOIN public.profiles p ON p.id = i.invited_by
  WHERE i.token = p_token
    AND i.used_at IS NULL
    AND i.expires_at > now()
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
    RETURN;
  END IF;

  IF p_claim THEN
    -- Atomic claim: only one concurrent caller wins. The losing caller sees
    -- ROW_COUNT = 0 and is told the invitation is no longer valid.
    UPDATE public.practitioner_invitations
       SET used_at = now()
     WHERE id = r.id AND used_at IS NULL;
    GET DIAGNOSTICS v_rows = ROW_COUNT;

    IF v_rows = 0 THEN
      RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
      RETURN;
    END IF;
  END IF;

  RETURN QUERY SELECT true, r.target_email, r.expected_credential_type, r.personal_note, r.invited_by_display;
END;
$$;

REVOKE ALL ON FUNCTION public.validate_practitioner_invitation(TEXT, BOOLEAN) FROM public;
GRANT EXECUTE ON FUNCTION public.validate_practitioner_invitation(TEXT, BOOLEAN) TO anon, authenticated;
