-- Prompt #62i — genetics nutritional guide storage.
-- Stores the full personalized guide JSON per consumer.
-- Versioned; only one current guide per user at a time.

CREATE TABLE IF NOT EXISTS genetics_nutritional_guides (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  confidence_tier INTEGER NOT NULL CHECK (confidence_tier BETWEEN 1 AND 3),
  confidence_percent INTEGER NOT NULL,
  data_sources TEXT[] NOT NULL,
  guide_data JSONB NOT NULL,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  regeneration_trigger TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_genetics_guide_current
  ON genetics_nutritional_guides (user_id) WHERE is_current = TRUE;

CREATE INDEX IF NOT EXISTS idx_genetics_guide_user
  ON genetics_nutritional_guides (user_id, generated_at DESC);

ALTER TABLE genetics_nutritional_guides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own nutritional guide" ON genetics_nutritional_guides;
CREATE POLICY "Users can view own nutritional guide"
  ON genetics_nutritional_guides FOR SELECT
  USING (auth.uid() = user_id);

-- Service role writes guides (generated by Gordan API route)
DROP POLICY IF EXISTS "Service insert nutritional guide" ON genetics_nutritional_guides;
CREATE POLICY "Service insert nutritional guide"
  ON genetics_nutritional_guides FOR INSERT
  WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Service update nutritional guide" ON genetics_nutritional_guides;
CREATE POLICY "Service update nutritional guide"
  ON genetics_nutritional_guides FOR UPDATE
  USING (TRUE);
