// Tables discovered from src/lib/supabase/types.ts columns user_id /
// profile_id and nearby owner columns (patient_user_id, sender_id, and
// similar). There is no DSAR deletion handler to reuse: POST /api/marshall/dsar
// only inserts dsar_requests and compliance_audit_log.
//
// Retained rows are anonymized in delete-user-data.ts. They are omitted here.

// Child tables are listed before parents that reference them.
const CHILD_FIRST = [
  'meal_items',
  'meal_items_hydration_backup_172e',
  'photo_meal_blobs',
  'meals',
  'meal_logs',
  'ultrathink_advisor_ratings',
  'ultrathink_advisor_query_log',
  'ultrathink_advisor_conversations',
  'ultrathink_recommendations',
  'ultrathink_agent_log',
  'ultrathink_protocols',
  'user_supplement_schedule',
  'user_current_supplements',
  'user_supplements',
  'user_epigenetic_markers',
  'epigenetic_uploads',
  'user_variants',
  'dna_uploads',
  'variant_calls',
  'genotype_uploads',
  'lab_biomarkers',
  'lab_report_uploads',
  'body_scan_composition',
  'body_scan_measurements',
  'body_scan_quality',
  'body_scan_tier_log',
  'body_tracker_circumference',
  'body_tracker_activity',
  'body_tracker_metabolic',
  'body_tracker_segmental_fat',
  'body_tracker_segmental_muscle',
  'body_tracker_weight',
  'body_photo_sessions',
  'body_tracker_entries',
  'body_goal_recalibrations',
  'body_goal_targets',
  'body_goals',
  'body_tracker_journey_events',
  'body_tracker_journeys',
  'nutrition_insight_feedback',
  'nutrition_insights',
  'peptide_stack_recommendations',
  'peptide_stack_protocols',
  'user_interactions',
  'user_interaction_cache',
  'research_hub_alerts',
  'research_hub_user_items',
  'helix_achievement_unlocks',
  'helix_challenge_participants',
  'helix_leaderboard',
  'helix_transactions',
  'caq_supplement_extraction_log',
  'caq_assessment_versions',
  'customer_price_bindings',
  'practitioners',
  'naturopath_profiles',
] as const;

const OTHER_USER_TABLES = [
  'active_compound_load',
  'adverse_events',
  'agent_conflict_log',
  'ai_insights',
  'ai_route_audit',
  'analytics_category_history',
  'analytics_events',
  'ancestry_context',
  'apple_health_imports',
  'approver_assignments',
  'assessment_results',
  'bio_optimization_history',
  'biomarker_trends',
  'biometric_consents',
  'body_composition_readings',
  'body_graphic_interactions',
  'body_graphics_preferences',
  'body_scan_inclusivity_waitlist',
  'body_scan_personal_baselines',
  'body_tracker_chronic_risk',
  'body_tracker_connections',
  'body_tracker_milestones',
  'body_tracker_photo_scans',
  'body_tracker_recommendations',
  'body_tracker_scores',
  'body_tracker_user_state',
  'bos_compute_queue',
  'bos_write_telemetry',
  'caq_demographics_updates',
  'caq_paths',
  'clinical_assessments',
  'connected_sources',
  'consent_ledger',
  'converter_disclaimer_acks',
  'converter_sessions',
  'customs_counsel_sessions',
  'daily_checkins',
  'daily_scores',
  'daily_tasks',
  'data_events',
  'diplotype_calls',
  'elysium_upload_coverage',
  'energy_balance_signals',
  'engagement_score_snapshots',
  'farma_tokens',
  'genetic_profiles',
  'genotype_phenotype_concordance',
  'goal_shape_targets',
  'hannah_accelerator_insights',
  'hannah_compile_runs',
  'hannah_daily_notes',
  'health_metrics',
  'health_scores',
  'helix_balances',
  'helix_redemptions',
  'helix_referral_codes',
  'helix_streaks',
  'hormone_marker_review_queue',
  'hormone_reports',
  'hydration_reconciliation',
  'interaction_notifications',
  'kit_registrations',
  'knowledge_queries',
  'lab_results_normalized',
  'medication_interactions',
  'notifications',
  'nutrient_intake_ledger',
  'nutrition_genetic_findings',
  'nutrition_insight_runs',
  'nutrition_logs',
  'nutrition_targets',
  'nutrition_test_uploads',
  'outcome_events',
  'pathway_scores',
  'peptide_detected_patterns',
  'platform_events',
  'practitioner_license_verification_requests',
  'product_genetic_scores',
  'protocol_adherence_log',
  'protocols',
  'recipe_suggestion_events',
  'recipes',
  'recommendation_audit',
  'recommendations',
  'regulatory_disclaimer_events',
  'research_hub_user_sources',
  'research_hub_user_tabs',
  'retest_schedule',
  'reward_redemptions',
  'scan_cadence_reminders',
  'scan_calibration_nudges',
  'scan_streak',
  'scoring_audit_log',
  'sherlock_activity_log',
  'sherlock_escalations',
  'sherlock_task_queue',
  'shop_cart_items',
  'suggestion_sessions',
  'supplement_adherence',
  'token_transactions',
  'user_addresses',
  'user_consents',
  'user_context_canonical',
  'user_feature_opt_ins',
  'user_health_context',
  'user_notification_preferences',
  'user_notifications',
  'user_nutrivision_settings',
  'user_off_lookups',
  'user_peptide_prescriptions',
  'user_prescribed_peptides',
  'user_protocol_synthesis',
  'user_protocols',
  'user_safety_preferences',
  'user_streaks',
  'user_tiers',
  'user_weight_goals',
  'wearable_audit_log',
  'wearable_body_composition',
  'wearable_daily_vitals',
  'wearable_events',
  'wearable_integrations',
  'wearable_metric_precedence',
  'wearable_oauth_states',
  'wearable_oauth_tokens',
  'wearable_recovery',
  'wearable_sleep_sessions',
  'wearable_workouts',
  'wellness_analytics',
  'white_label_compliance_reviewer_roles',
] as const;

export const DELETE_USER_ID_TABLES: readonly string[] = [...CHILD_FIRST, ...OTHER_USER_TABLES];

export const DELETE_BY_COLUMN: readonly { table: string; column: string }[] = [
  { table: 'family_members', column: 'primary_user_id' },
  { table: 'family_members', column: 'member_user_id' },
  { table: 'photo_share_permissions', column: 'photo_session_user_id' },
  { table: 'body_scan_practitioner_notes', column: 'patient_user_id' },
  { table: 'body_scan_practitioner_notes', column: 'practitioner_user_id' },
  { table: 'patient_practitioner_relationships', column: 'patient_user_id' },
  { table: 'interaction_overrides', column: 'patient_user_id' },
  { table: 'interaction_overrides', column: 'practitioner_user_id' },
  { table: 'helix_transactions', column: 'source_user_id' },
  { table: 'helix_referrals', column: 'referred_user_id' },
  { table: 'helix_family_pool_config', column: 'primary_user_id' },
  { table: 'portal_messages', column: 'sender_id' },
  { table: 'portal_messages', column: 'recipient_id' },
  { table: 'conversations', column: 'patient_id' },
  { table: 'practitioner_peptide_protocols', column: 'recipient_user_id' },
  { table: 'practitioner_peptide_protocols', column: 'author_user_id' },
  { table: 'prescription_tokens', column: 'patient_user_id' },
  { table: 'protocols', column: 'patient_id' },
  { table: 'constitutional_assessments', column: 'patient_user_id' },
  { table: 'consumer_counterfeit_reports', column: 'submitted_by_user_id' },
  { table: 'governance_notifications_queue', column: 'recipient_user_id' },
];

// Nullable actor columns. The row stays. A missing column or NOT NULL
// constraint is skipped; it does not delete the row.
export const NULL_ACTOR_COLUMNS: readonly { table: string; column: string }[] = [
  { table: 'board_members', column: 'auth_user_id' },
  { table: 'competitor_pricing', column: 'observed_by_user_id' },
  { table: 'custom_formulation_medical_reviews', column: 'reviewer_user_id' },
  { table: 'custom_formulation_regulatory_reviews', column: 'reviewer_user_id' },
  { table: 'custom_formulation_stability_tests', column: 'conducted_by_user_id' },
  { table: 'executive_reporting_audit_log', column: 'actor_user_id' },
  { table: 'international_audit_log', column: 'actor_user_id' },
  { table: 'international_market_config', column: 'updated_by_user_id' },
  { table: 'international_refunds', column: 'refunded_by_user_id' },
  { table: 'legal_case_timeline', column: 'actor_user_id' },
  { table: 'legal_operations_audit_log', column: 'actor_user_id' },
  { table: 'legal_privilege_grants', column: 'user_id' },
  { table: 'marketing_copy_variant_events', column: 'actor_user_id' },
  { table: 'master_skus_market_pricing', column: 'price_approved_by_user_id' },
  { table: 'master_skus_market_pricing', column: 'price_set_by_user_id' },
  { table: 'notification_legal_ops_preferences', column: 'opt_out_cosigned_by_user_id' },
  { table: 'notification_legal_ops_recipients', column: 'user_id' },
  { table: 'notification_legal_ops_recipients', column: 'designated_alternate_user_id' },
  { table: 'notification_phi_redaction_failures', column: 'resolved_by_user_id' },
  { table: 'outcome_timeline_events', column: 'actor_user_id' },
  { table: 'practitioner_operations_audit_log', column: 'actor_user_id' },
  { table: 'practitioner_waitlist', column: 'converted_to_user_id' },
  { table: 'practitioner_waitlist', column: 'invited_by_user_id' },
  { table: 'prescription_tokens', column: 'revoked_by_user_id' },
  { table: 'prescription_tokens', column: 'practitioner_user_id' },
  { table: 'price_change_history', column: 'applied_by_user_id' },
  { table: 'proposal_approvals', column: 'approver_user_id' },
  { table: 'proposal_comments', column: 'author_user_id' },
  { table: 'scenario_events', column: 'actor_user_id' },
  { table: 'shop_refresh_audit_log', column: 'actor_user_id' },
  { table: 'shop_refresh_reconciliation_findings', column: 'resolved_by_user_id' },
  { table: 'supplement_photo_bindings', column: 'bound_by_user_id' },
  { table: 'trust_band_events', column: 'actor_user_id' },
  { table: 'white_label_compliance_reviews', column: 'reviewer_user_id' },
  { table: 'white_label_recalls', column: 'initiated_by_user_id' },
  { table: 'white_label_reviewer_assignments', column: 'completed_by_user_id' },
];

export const CLEAR_SELF_REFERENCE: readonly { table: string; column: string }[] = [
  { table: 'caq_assessment_versions', column: 'previous_version_id' },
  { table: 'body_composition_readings', column: 'superseded_by' },
  { table: 'customer_price_bindings', column: 'superseded_by_binding_id' },
];
