"use client";

import { ShieldAlert, User, Leaf } from "lucide-react";

export function PractitionerDisclaimer({ hasLabs = false, hasGenetics = false }: { hasLabs?: boolean; hasGenetics?: boolean }) {
  return (
    <div className="rounded-xl bg-orange-400/5 border border-orange-400/15 p-4 md:p-5 mt-6">
      <div className="flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-orange-400 flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-sm text-orange-400 font-medium mb-1">Consult Before Starting</p>
          <p className="text-xs text-white/50 leading-relaxed">
            This protocol is generated by AI based on your assessment data
            {hasLabs && ", lab results"}
            {hasGenetics && ", and genetic profile"}.
            Please consult with a practitioner or naturopath before starting any new supplement regimen. Individual results may vary.
          </p>
          <div className="flex flex-col sm:flex-row gap-2 mt-3">
            <a href="/messages" className="min-h-[44px] px-4 py-2 rounded-lg bg-teal-400/10 border border-teal-400/30 text-teal-400 text-xs font-medium hover:bg-teal-400/15 transition-all flex items-center justify-center gap-1.5 w-full sm:w-auto">
              <User className="w-3.5 h-3.5" /> Find a Practitioner
            </a>
            <a href="/messages" className="min-h-[44px] px-4 py-2 rounded-lg bg-white/5 border border-white/10 text-white/50 text-xs font-medium hover:border-white/20 transition-all flex items-center justify-center gap-1.5 w-full sm:w-auto">
              <Leaf className="w-3.5 h-3.5" /> Find a Naturopath
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
