'use client';

import { useState } from 'react';
import { ClipboardCopy, Mail, Check } from 'lucide-react';
import type { PeptideProduct } from '@/config/peptide-database/categories-1-3';

interface SharePeptideButtonProps {
  peptide: PeptideProduct;
  /** Compact = single icon button (catalog card). Full = both copy + email actions side by side. */
  compact?: boolean;
}

const FORM_LABELS: Record<string, string> = {
  liposomal: 'Liposomal',
  micellar: 'Micellar',
  injectable: 'Injectable',
  nasal_spray: 'Nasal Spray',
};

function buildProfileText(peptide: PeptideProduct): string {
  const lines: string[] = [];
  lines.push(`PEPTIDE PROFILE — ${peptide.name}`);
  lines.push('='.repeat(60));
  lines.push(`Category:          ${peptide.category}`);
  lines.push(`Type:              ${peptide.type}`);
  lines.push(`Mechanism:         ${peptide.mechanism}`);
  lines.push(`Evidence Level:    ${peptide.evidenceLevel}`);
  lines.push('');

  lines.push('HOW IT WORKS');
  lines.push('-'.repeat(60));
  lines.push(peptide.howItWorks);
  lines.push('');

  if (peptide.keyHighlights.length > 0) {
    lines.push('KEY HIGHLIGHTS');
    lines.push('-'.repeat(60));
    peptide.keyHighlights.forEach((h) => lines.push(`  - ${h}`));
    lines.push('');
  }

  if (peptide.performanceProfile.length > 0) {
    lines.push('PERFORMANCE PROFILE');
    lines.push('-'.repeat(60));
    peptide.performanceProfile.forEach((m) =>
      lines.push(`  ${m.metric}: ${m.value}`),
    );
    lines.push('');
  }

  lines.push('DELIVERY FORMS & PROTOCOLS');
  lines.push('-'.repeat(60));
  peptide.dosingForms.forEach((df) => {
    lines.push(`  ${FORM_LABELS[df.form] ?? df.form}: ${df.protocol}`);
  });
  lines.push('');

  lines.push(`Cycle Protocol:    ${peptide.cycleProtocol}`);
  lines.push(`Onset Timeline:    ${peptide.onsetTimeline}`);
  lines.push('');

  if (peptide.targetVariants.length > 0) {
    lines.push('GENEX360 GENETIC SYNERGY');
    lines.push('-'.repeat(60));
    lines.push(`Panel:             ${peptide.genexPanel}`);
    lines.push(`Target Variants:   ${peptide.targetVariants.join(', ')}`);
    lines.push(`Synergy:           ${peptide.genexSynergy}`);
    lines.push('');
  }

  lines.push('IMPORTANT DISCLAIMER');
  lines.push('-'.repeat(60));
  lines.push(
    'This information is for educational and wellness purposes only. It is not',
  );
  lines.push(
    'a prescription, diagnosis, or medical treatment. Statements have not been',
  );
  lines.push(
    'evaluated by the FDA. Consult a licensed healthcare practitioner before',
  );
  lines.push('beginning any peptide protocol.');
  lines.push('');
  lines.push('Generated by ViaConnect™ GeneX360™ Platform');
  lines.push('FarmCeutica Wellness LLC');

  return lines.join('\n');
}

export function SharePeptideButton({
  peptide,
  compact = false,
}: SharePeptideButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = buildProfileText(peptide);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard failed (e.g., insecure context). Fallback: open mailto.
      handleEmail();
    }
  };

  const handleEmail = () => {
    const subject = `Peptide Profile: ${peptide.name} — ViaConnect™`;
    const body = buildProfileText(peptide);
    const url = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, '_blank');
  };

  if (compact) {
    return (
      <button
        type="button"
        onClick={handleCopy}
        title={copied ? 'Copied to clipboard' : 'Copy peptide profile to share with practitioner'}
        className="inline-flex min-h-[36px] items-center justify-center gap-1 rounded-xl border border-[rgba(255,255,255,0.10)] bg-[rgba(255,255,255,0.04)] px-3 py-2 text-xs font-medium text-[rgba(255,255,255,0.65)] transition-all duration-200 hover:border-[rgba(255,255,255,0.20)] hover:bg-[rgba(255,255,255,0.08)] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2DA5A0]/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#1A2744]"
      >
        {copied ? (
          <>
            <Check className="h-3.5 w-3.5 text-[#2DA5A0]" strokeWidth={1.5} />
            <span className="text-[#2DA5A0]">Copied</span>
          </>
        ) : (
          <>
            <ClipboardCopy className="h-3.5 w-3.5" strokeWidth={1.5} />
            Share
          </>
        )}
      </button>
    );
  }

  return (
    <div className="flex flex-col gap-2 sm:flex-row">
      <button
        type="button"
        onClick={handleCopy}
        className="inline-flex min-h-[44px] flex-1 items-center justify-center gap-2 rounded-xl border border-[rgba(45,165,160,0.30)] bg-[rgba(45,165,160,0.15)] px-5 py-3 text-sm font-semibold text-[#2DA5A0] transition-all duration-200 hover:border-[rgba(45,165,160,0.50)] hover:bg-[rgba(45,165,160,0.25)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2DA5A0]/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#1A2744]"
      >
        {copied ? (
          <>
            <Check className="h-4 w-4" strokeWidth={1.5} />
            Copied to clipboard
          </>
        ) : (
          <>
            <ClipboardCopy className="h-4 w-4" strokeWidth={1.5} />
            Copy Peptide Profile
          </>
        )}
      </button>
      <button
        type="button"
        onClick={handleEmail}
        className="inline-flex min-h-[44px] flex-1 items-center justify-center gap-2 rounded-xl border border-[rgba(255,255,255,0.10)] bg-[rgba(255,255,255,0.04)] px-5 py-3 text-sm font-semibold text-[rgba(255,255,255,0.75)] transition-all duration-200 hover:border-[rgba(255,255,255,0.20)] hover:bg-[rgba(255,255,255,0.08)] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2DA5A0]/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#1A2744]"
      >
        <Mail className="h-4 w-4" strokeWidth={1.5} />
        Email to Provider
      </button>
    </div>
  );
}
