"use client";

// ShareWithPractitionerButton — twin actions ("Copy" / "Email") for
// Prompt #53 peptide profiles. Generates a plain-text summary of a
// peptide profile and either copies it to the clipboard or hands it to
// the user's mail client via mailto:. There is no "Add to Cart" or
// "Buy Now" anywhere in the catalog — these buttons are the only CTAs.

import { useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Check, ClipboardCopy, Mail } from "lucide-react";
import toast from "react-hot-toast";
import type { PeptideProduct } from "@/data/peptideCatalog";

interface ShareWithPractitionerButtonProps {
  peptide: PeptideProduct;
  /** "compact" — single Copy button used on grid cards.
   *  "full"    — Copy + Email side-by-side used on detail pages. */
  variant?: "compact" | "full";
}

function buildProfileText(peptide: PeptideProduct): string {
  const benefits = peptide.primaryBenefits.map((b) => `- ${b}`).join("\n");
  const lines = [
    `PEPTIDE PROFILE — ${peptide.name}`,
    `Category: ${peptide.category}`,
    `Research Status: ${peptide.researchStatus[0].toUpperCase()}${peptide.researchStatus.slice(1)}`,
    `Delivery Forms: ${peptide.deliveryForms.join(", ")}`,
    "",
    "Description:",
    peptide.description,
    "",
    "Mechanism of Action:",
    peptide.mechanismOfAction,
    "",
    "Primary Benefits:",
    benefits,
  ];
  if (peptide.contraindications) {
    lines.push("", "Contraindications:", peptide.contraindications);
  }
  if (peptide.practitionerNotes) {
    lines.push("", "Practitioner Notes:", peptide.practitionerNotes);
  }
  lines.push(
    "",
    "Generated by ViaConnect™ GeneX360™ Platform",
    "FarmCeutica Wellness LLC — farmceutica.com",
  );
  return lines.join("\n");
}

export function ShareWithPractitionerButton({
  peptide,
  variant = "full",
}: ShareWithPractitionerButtonProps) {
  const reduce = useReducedMotion();
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    const text = buildProfileText(peptide);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success(`${peptide.name} profile copied to clipboard`);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy to clipboard");
    }
  }

  function handleEmail() {
    const text = buildProfileText(peptide);
    const subject = encodeURIComponent(
      `Peptide Profile: ${peptide.name} — ViaConnect™`,
    );
    const body = encodeURIComponent(text);
    if (typeof window !== "undefined") {
      window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
    }
  }

  if (variant === "compact") {
    return (
      <motion.button
        type="button"
        onClick={handleCopy}
        whileHover={reduce ? undefined : { scale: 1.01 }}
        whileTap={reduce ? undefined : { scale: 0.98 }}
        className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-[#2DA5A0] bg-[#2DA5A0]/10 border border-[#2DA5A0]/30 hover:bg-[#2DA5A0]/15 hover:border-[#2DA5A0]/50 transition-all min-h-[40px]"
      >
        {copied ? (
          <>
            <Check className="w-3.5 h-3.5" strokeWidth={1.5} />
            Profile copied
          </>
        ) : (
          <>
            <ClipboardCopy className="w-3.5 h-3.5" strokeWidth={1.5} />
            Share with Practitioner
          </>
        )}
      </motion.button>
    );
  }

  return (
    <div className="flex flex-col sm:flex-row gap-2">
      <motion.button
        type="button"
        onClick={handleCopy}
        whileHover={reduce ? undefined : { scale: 1.01 }}
        whileTap={reduce ? undefined : { scale: 0.98 }}
        className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-semibold text-[#2DA5A0] bg-[#2DA5A0]/10 border border-[#2DA5A0]/30 hover:bg-[#2DA5A0]/15 hover:border-[#2DA5A0]/50 transition-all min-h-[44px]"
      >
        {copied ? (
          <>
            <Check className="w-4 h-4" strokeWidth={1.5} />
            Copied to clipboard
          </>
        ) : (
          <>
            <ClipboardCopy className="w-4 h-4" strokeWidth={1.5} />
            Copy Peptide Profile
          </>
        )}
      </motion.button>
      <motion.button
        type="button"
        onClick={handleEmail}
        whileHover={reduce ? undefined : { scale: 1.01 }}
        whileTap={reduce ? undefined : { scale: 0.98 }}
        className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-semibold text-[#2DA5A0] bg-[#2DA5A0]/10 border border-[#2DA5A0]/30 hover:bg-[#2DA5A0]/15 hover:border-[#2DA5A0]/50 transition-all min-h-[44px]"
      >
        <Mail className="w-4 h-4" strokeWidth={1.5} />
        Email to Provider
      </motion.button>
    </div>
  );
}
