// Prompt 193 (2026-06-12): shared types for the GENEX360 per panel description
// cards on the /shop/genex360 Your DNA section.
//
// Standing rules honored: no em or en dashes anywhere; consumer brand is Via
// Cura; bioavailability copy is locked at "Maximum Bioavailability"; the score is named
// "Bio Optimization". These types only describe shape; the copy lives in
// panels.ts, transcribed verbatim from the prompt Section 7.

export type PanelSlug =
  | "genex-m"
  | "nutrigen-dx"
  | "hormone-iq"
  | "epigen-hq"
  | "peptide-iq"
  | "cannabis-iq";

export interface PanelMarker {
  symbol: string; // gene symbol or analyte label, for example "MTHFR" or "Cortisol (free, diurnal)"
  fullName: string; // expanded name
  description: string; // function plus variant or marker effect plus health impact, no em or en dashes
  // Prompt 193a: optional comprehensive per SNP report shown in the expanded
  // disclosure. Present on the GeneXM SNP markers after the genex-m-deep merge;
  // absent on panels without per SNP reports.
  deepReport?: SnpDeepReport;
  // Prompt 204 (2026-06-20): optional epigenetic interpretation shown in the
  // expanded disclosure for an EpigenHQ marker. EpigenHQ is NOT a genotype panel,
  // so it has no deepReport; instead each marker carries this educational
  // interpretation (what it measures, what higher / lower suggests, a wellness
  // note). Attached at module load by the epigen-hq interpretation merge.
  epigeneticInterpretation?: EpigeneticInterpretation;
}

// Prompt 204 (2026-06-20): the educational interpretation for one EpigenHQ marker.
// EpigenHQ markers are MEASURED epigenetic readouts (methylation age, indices,
// exposure signatures), not genotypes, so there is no allele, no genotype table,
// and no severity tier. This is the validated, non-diagnostic wellness reading of
// a marker. The member's actual result value is a separate future data source;
// this is the interpretation layer only.
export interface EpigeneticInterpretation {
  marker: string; // the display marker name, matching PanelMarker.symbol
  measures: string; // what this epigenetic readout measures
  higherSuggests: string; // what a higher-than-expected value suggests, wellness framed
  lowerSuggests: string; // what a lower-than-expected value suggests, wellness framed
  wellnessNote: string; // the practical, non-diagnostic takeaway and supportive levers
}

// Prompt 193a (2026-06-12): comprehensive per SNP deep report types for the
// GeneXM individual SNP reports. The rsid and genotype fields are DEFAULTS to
// reconcile with the live GENEX-M assay (see the genex-m-deep.ts header); the
// biology, health associations, and strategy copy is authoritative. No em or en
// dashes anywhere; bioavailability stays "Maximum Bioavailability"; score is "Bio Optimization".

export interface SnpGenotype {
  genotype: string; // for example "CC", "CT", "TT", "GG", or "Reference" / "Variant" for representative variants
  label: string; // short status, for example "Typical", "Intermediate", "Reduced function"
  interpretation: string; // what this genotype means functionally and for health, no em or en dashes
}

export interface SnpVariant {
  rsid: string; // for example "rs1801133"
  name: string; // common name, for example "C677T (Ala222Val)"
  genotypes: SnpGenotype[];
  // Prompt 193b: true when the genotype tiers for this variant are NOT yet
  // reconciled with the live GENEX-M assay. The UI then hides the genotype rows
  // and shows the variant identity plus a short pending note only. Used by SUOX
  // (confirm with assay) and ADO (defer to lab, no established common variant).
  // genotypes may be empty when this flag is set.
  pendingAssayDefinition?: boolean;
}

export interface SnpDeepReport {
  aliases: string[]; // alternate gene names, empty array if none
  pathway: string; // for example "Methylation"
  keyVariants: SnpVariant[]; // one or more variants with genotype interpretations
  biologicalRole: string; // what the gene or enzyme does
  functionalImpact: string; // consequence of reduced or altered function
  healthAssociations: string[]; // associative phenotype links, wellness framed (paragraph kept as one entry where the source is prose)
  nutrientStrategy: string[]; // cofactors and nutrient forms that support the pathway
  cautions: string[]; // what to watch or avoid, titration notes
  dietLifestyle: string[]; // food and lifestyle levers
  interactions: string[]; // gene to gene synergies relevant to this SNP (paragraph kept as one entry)
  protocolTieIn: string; // Via Cura protocol and Bio Optimization tie in
  // Prompt 204f (2026-06-19): optional plain-language summary for the Description
  // tab, one approachable paragraph per entry, written for a reader new to SNP
  // science. VALIDATED content only: a faithful simplification of this same deep
  // report that has passed the 204d clinical and compliance review. It is never
  // freehand generated by the build. When absent, the Description tab shows the
  // neutral interim orientation instead of any fabricated specifics.
  laySummary?: string[];
}

export interface PanelMarkerGroup {
  groupTitle: string; // for example "Methylation Pathway Efficiency"
  markers: PanelMarker[];
}

export type PanelType = "snp" | "biomarker" | "epigenetic" | "educational";

export interface Panel {
  slug: PanelSlug;
  pillLabel: string; // short label on the pill, for example "GeneXM"
  displayName: string; // full display name
  subtitle: string; // for example "Genetic Methylation and Detox Profile"
  tagline: string; // a short panel specific line
  panelType: PanelType;
  overview: string; // 2 to 4 sentence panel summary
  markerCount: number; // derived count for display, for example 20
  markerCountLabel: string; // for example "20 SNPs" or "12 epigenetic markers"
  groups: PanelMarkerGroup[];
  whatYoullLearn: string[];
  collection: string[]; // test kit and delivery bullets
  protocolTieIn: string; // one paragraph connecting results to the Via Cura protocol and Bio Optimization
}
