'use client';

import { useEffect, useState } from 'react';
import { Loader2, Sparkles, RefreshCw, Info, ShieldAlert } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import type { ScanInsight } from '@/lib/body-tracker/scan-types';
import type { PortalType } from './ScanResultsPanel';

// AI disclosure §13.4 verbatim
const AI_DISCLOSURE =
  'Insights are generated by an AI assistant (Arnold) based on your scan data and protocol context. Always validate clinically significant decisions with a qualified professional.';

const SEVERITY_COLOR: Record<ScanInsight['severity'], string> = {
  low:    '#2DA5A0',
  medium: '#E8803A',
  high:   '#EF4444',
};

const SEVERITY_BG: Record<ScanInsight['severity'], string> = {
  low:    'rgba(45,165,160,0.10)',
  medium: 'rgba(232,128,58,0.10)',
  high:   'rgba(239,68,68,0.10)',
};

const KIND_LABEL: Record<ScanInsight['kind'], string> = {
  recommendation: 'Recommendation',
  observation:    'Observation',
  flag:           'Flag',
};

interface ScanInsightsTabProps {
  sessionId: string;
  userId: string;
  portalType: PortalType;
}

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ??
  process.env.NEXT_PUBLIC_SUPABASE_PROJECT_URL ??
  '';

export function ScanInsightsTab({ sessionId, userId, portalType }: ScanInsightsTabProps) {
  const [insights, setInsights]   = useState<ScanInsight[]>([]);
  const [loading, setLoading]     = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError]         = useState<string | null>(null);

  // Load insights from body_tracker_recommendations (written by arnold-cross-reference-recommend).
  // Insights are user-scoped not session-scoped per Phase 1; scan-scoped insights deferred to Phase 2.
  useEffect(() => {
    let mounted = true;
    setLoading(true);
    setError(null);

    (async () => {
      try {
        const supabase = createClient();
        type RecommendationRow = {
          recommendation_text: string;
          confidence_tier: number;
          source_ids: string[];
        };
        type Loose = {
          from: (t: string) => {
            select: (cols: string) => {
              eq: (col: string, val: string) => {
                is: (col: string, val: null) => {
                  order: (col: string, opts: { ascending: boolean }) => {
                    limit: (n: number) => Promise<{ data: RecommendationRow[] | null; error: { message: string } | null }>;
                  };
                };
              };
            };
          };
        };
        const sb = supabase as unknown as Loose;
        const { data, error: dbErr } = await sb
          .from('body_tracker_recommendations')
          .select('recommendation_text, confidence_tier, source_ids')
          .eq('user_id', userId)
          .is('dismissed_at', null)
          .order('created_at', { ascending: false })
          .limit(3);

        if (!mounted) return;
        if (dbErr) throw new Error(dbErr.message);

        const rows = (data ?? []) as RecommendationRow[];

        const parsed: ScanInsight[] = rows.map((r) => ({
          kind:                 'recommendation' as ScanInsight['kind'],
          message:              r.recommendation_text,
          sourceProtocolItemId: null,
          // Map confidence_tier (1=low, 2=medium, 3=high) to severity
          severity:             r.confidence_tier >= 3 ? 'high' : r.confidence_tier === 2 ? 'medium' : 'low' as ScanInsight['severity'],
        }));

        setInsights(parsed);
        setLoading(false);
      } catch (e) {
        if (!mounted) return;
        setError(e instanceof Error ? e.message : 'Failed to load insights');
        setLoading(false);
      }
    })();

    return () => { mounted = false; };
  }, [userId]);

  async function generateInsights() {
    setGenerating(true);
    setError(null);
    try {
      const supabase = createClient();
      const { data: sessionData } = await supabase.auth.getSession();
      const token = sessionData?.session?.access_token;
      if (!token) throw new Error('Not signed in');
      const url = `${SUPABASE_URL.replace(/\/$/, '')}/functions/v1/arnold-cross-reference-recommend`;
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        // Insights are user-scoped not session-scoped per Phase 1; scan-scoped insights deferred to Phase 2.
        body: JSON.stringify({ regenerate: true }),
      });
      if (!res.ok) {
        const errBody = await res.json().catch(() => ({}));
        throw new Error((errBody as { error?: string }).error ?? `Generation failed (${res.status})`);
      }
      // Reload from body_tracker_recommendations after generation
      type RecommendationRow2 = {
        recommendation_text: string;
        confidence_tier: number;
        source_ids: string[];
      };
      const supabase2 = createClient();
      type Loose2 = {
        from: (t: string) => {
          select: (cols: string) => {
            eq: (col: string, val: string) => {
              is: (col: string, val: null) => {
                order: (col: string, opts: { ascending: boolean }) => {
                  limit: (n: number) => Promise<{ data: RecommendationRow2[] | null; error: unknown }>;
                };
              };
            };
          };
        };
      };
      const sb2 = supabase2 as unknown as Loose2;
      const { data } = await sb2
        .from('body_tracker_recommendations')
        .select('recommendation_text, confidence_tier, source_ids')
        .eq('user_id', userId)
        .is('dismissed_at', null)
        .order('created_at', { ascending: false })
        .limit(3);

      const rows = (data ?? []) as RecommendationRow2[];

      setInsights(rows.map((r) => ({
        kind:                 'recommendation' as ScanInsight['kind'],
        message:              r.recommendation_text,
        sourceProtocolItemId: null,
        severity:             r.confidence_tier >= 3 ? 'high' : r.confidence_tier === 2 ? 'medium' : 'low' as ScanInsight['severity'],
      })));
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Generation failed');
    } finally {
      setGenerating(false);
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-10">
        <Loader2 className="h-5 w-5 animate-spin text-white/50" strokeWidth={1.5} />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header row */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#E8803A]/15">
            <Sparkles className="h-4 w-4 text-[#E8803A]" strokeWidth={1.5} />
          </div>
          <span className="text-sm font-bold text-white">Arnold insights</span>
        </div>
        <button
          type="button"
          onClick={generateInsights}
          disabled={generating}
          className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs text-white/70 hover:bg-white/[0.06] disabled:opacity-50 min-h-[36px]"
        >
          {generating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={1.5} />
          ) : (
            <RefreshCw className="h-3.5 w-3.5" strokeWidth={1.5} />
          )}
          {generating ? 'Generating' : 'Refresh insights'}
        </button>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          {error}
        </div>
      )}

      {/* Insight cards */}
      {insights.length === 0 && !generating && (
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-6 text-center text-xs text-white/50">
          No insights yet. Tap Refresh insights to generate Arnold analysis for this scan.
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {insights.map((ins, idx) => (
          <div
            key={idx}
            className="rounded-xl border px-4 py-3 space-y-1.5"
            style={{
              borderColor: SEVERITY_COLOR[ins.severity] + '40',
              background: SEVERITY_BG[ins.severity],
            }}
          >
            <div className="flex items-center justify-between gap-2">
              <span
                className="text-[10px] font-semibold uppercase tracking-wider"
                style={{ color: SEVERITY_COLOR[ins.severity] }}
              >
                {KIND_LABEL[ins.kind]}
              </span>
              <span
                className="rounded-full px-2 py-0.5 text-[10px] font-medium"
                style={{
                  color: SEVERITY_COLOR[ins.severity],
                  background: SEVERITY_BG[ins.severity],
                }}
              >
                {ins.severity.charAt(0).toUpperCase() + ins.severity.slice(1)}
              </span>
            </div>
            <p className="text-sm text-white/85 leading-relaxed">{ins.message}</p>
          </div>
        ))}
      </div>

      {/* Practitioner-only peptide guidance placeholder */}
      {portalType === 'practitioner' && (
        <div className="rounded-xl border border-[#A78BFA]/25 bg-[#A78BFA]/5 px-4 py-3 space-y-1">
          <div className="flex items-center gap-2">
            <ShieldAlert className="h-4 w-4 text-[#A78BFA]" strokeWidth={1.5} />
            <span className="text-xs font-semibold text-[#A78BFA]">Practitioner guidance</span>
          </div>
          <p className="text-xs text-white/65 leading-relaxed">
            Injectable protocol guidance is available for qualified practitioners. Educational content on
            injectable options (practitioner-only) will appear here once protocol context is loaded.
          </p>
        </div>
      )}

      {/* AI disclosure §13.4 verbatim */}
      <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5 flex items-start gap-2">
        <Info className="h-3.5 w-3.5 text-white/40 shrink-0 mt-0.5" strokeWidth={1.5} />
        <p className="text-[11px] text-white/45 leading-relaxed">{AI_DISCLOSURE}</p>
      </div>
    </div>
  );
}
