// body-scan-export/copy.ts
// Static strings for the PDF report. All copy here must pass the Marshall
// dictionary scan. No diagnostic language, no em/en-dashes, no emojis.
// Verbatim text from the ViaConnect brand and compliance spec.

/** Tagline — §15.4 and §19 verbatim. */
export const TAGLINE = 'Built For Your Biology';

/** Report subtitle — wellness language only, no "diagnostic". */
export const REPORT_SUBTITLE = 'Body Composition Tracking Report';

/** Footer company name — exact spelling. */
export const COMPANY_NAME = 'Farmceutica Wellness Ltd';

/** BOS card label. */
export const BOS_LABEL = 'Bio Optimization Score';

/** Fallback BOS driver line when no computed drivers are available. */
export const BOS_DEFAULT_DRIVER = 'Lean mass and visceral fat both improving';

/**
 * General wellness disclaimer, §13.1 verbatim.
 * No diagnostic language. No em/en-dashes.
 */
export const DISCLAIMER_WELLNESS =
  'Body composition estimates from Via Cura Body Scan are intended for general ' +
  'wellness tracking and education. They are not a medical diagnosis and are not ' +
  'a substitute for clinical assessment. For medical evaluation of body composition, ' +
  'please consult a healthcare professional and consider clinical methods like DEXA scanning.';

/**
 * AI disclosure, §13.4 verbatim.
 */
export const DISCLAIMER_AI =
  'Insights are generated by an AI assistant (Arnold) based on your scan data and ' +
  'protocol context. Always validate clinically significant decisions with a qualified professional.';

/** Longitudinal chart placeholder note (Phase 1 deliberate limitation). */
export const CHART_PLACEHOLDER =
  'Trend chart available in the app; PDF export covers most recent scan only.';

/** Avatar placeholder when base64 not supplied. */
export const AVATAR_PLACEHOLDER = '3D avatar not available in this export';

/**
 * Human-readable labels for the 15 circumference columns pulled from
 * body_scan_measurements. Order mirrors the PDF table top-to-bottom.
 */
export const MEASUREMENT_LABELS: Record<string, string> = {
  neck_circ_cm:          'Neck',
  shoulder_circ_cm:      'Shoulders',
  chest_circ_cm:         'Chest',
  under_bust_circ_cm:    'Under Bust',
  waist_natural_circ_cm: 'Waist (Natural)',
  waist_navel_circ_cm:   'Waist (Navel)',
  hip_circ_cm:           'Hips',
  right_bicep_circ_cm:   'Right Bicep',
  left_bicep_circ_cm:    'Left Bicep',
  right_forearm_circ_cm: 'Right Forearm',
  left_forearm_circ_cm:  'Left Forearm',
  right_thigh_circ_cm:   'Right Thigh',
  left_thigh_circ_cm:    'Left Thigh',
  right_calf_circ_cm:    'Right Calf',
  left_calf_circ_cm:     'Left Calf',
};

/** Column keys in display order. */
export const MEASUREMENT_KEYS = Object.keys(MEASUREMENT_LABELS);
