// Prompt #127 P3: HIPAA Security Rule framework definition.
//
// Full HIPAA Security Rule control points covering 45 CFR 164.302-318.
// Each control point is tagged Required or Addressable per the regulation
// and cross-referenced to equivalent SOC 2 trust services criteria so
// shared evidence can flow through both frameworks without re-collection.
//
// HIPAA-specific: any control whose sole evidence source is a manual
// artifact (e.g., Facility Security Plan at 164.310(a)(2)(ii)) has an
// empty collector list but a declared manual-vault evidence path in the
// SpecialArtifactRequirement list on the framework.

import type {
  ControlPoint,
  CrossFrameworkReference,
  FrameworkDefinition,
  NarratorSectionSpec,
  SpecialArtifactRequirement,
} from '../types';

const REGISTRY_VERSION = 'v1.0.0';

// HIPAA narrator sections — mirror the spec §8.2 HIPAA section kinds.
const REQUIRED_SECTIONS: readonly NarratorSectionSpec[] = [
  { kind: 'safeguard_description',     required: true,  carryoverAllowed: true,  generatorTone: 'declarative' },
  { kind: 'implementation_summary',    required: true,  carryoverAllowed: false, generatorTone: 'outcome_based' },
  { kind: 'compliance_status',         required: true,  carryoverAllowed: false, generatorTone: 'declarative' },
];
const ADDRESSABLE_SECTIONS: readonly NarratorSectionSpec[] = [
  ...REQUIRED_SECTIONS,
  { kind: 'addressable_safeguard_determination', required: true, carryoverAllowed: false, generatorTone: 'declarative' },
];

// Shorthand builder
function ctl(
  id: string,
  category: string,
  name: string,
  description: string,
  requiredOrAddressable: 'required' | 'addressable',
  evidenceSources: readonly string[],
  crossFrameworkReferences: readonly CrossFrameworkReference[] = [],
): ControlPoint {
  return {
    id,
    framework: 'hipaa_security',
    category,
    name,
    description,
    requiredOrAddressable,
    evidenceSources,
    narratorSections: requiredOrAddressable === 'required' ? REQUIRED_SECTIONS : ADDRESSABLE_SECTIONS,
    crossFrameworkReferences,
  };
}

// Shorthand: SOC 2 equivalence reference
function soc2Eq(controlId: string): CrossFrameworkReference {
  return { framework: 'soc2', controlId, relationship: 'equivalent' };
}
function soc2Overlap(controlId: string): CrossFrameworkReference {
  return { framework: 'soc2', controlId, relationship: 'overlapping' };
}

// ─── Administrative Safeguards § 164.308 ──────────────────────────────────
const ADMINISTRATIVE: readonly ControlPoint[] = [
  ctl('164.308(a)(1)(i)',        'Administrative Safeguards — Security Management Process',
      'Security management process',
      'Implement policies and procedures to prevent, detect, contain, and correct security violations.',
      'required',
      ['marshall-audit-chain-collector'],
      [soc2Overlap('CC4.1'), soc2Eq('CC7.3')]),
  ctl('164.308(a)(1)(ii)(A)',    'Administrative Safeguards — Security Management Process',
      'Risk Analysis',
      'Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity, and availability of electronic protected health information.',
      'required',
      [],
      [soc2Overlap('CC4.1')]),
  ctl('164.308(a)(1)(ii)(B)',    'Administrative Safeguards — Security Management Process',
      'Risk Management',
      'Implement security measures sufficient to reduce risks and vulnerabilities to a reasonable and appropriate level.',
      'required',
      ['marshall-findings-collector'],
      [soc2Overlap('CC4.1')]),
  ctl('164.308(a)(1)(ii)(C)',    'Administrative Safeguards — Security Management Process',
      'Sanction Policy',
      'Apply appropriate sanctions against workforce members who fail to comply with the security policies and procedures of the covered entity.',
      'required',
      []),
  ctl('164.308(a)(1)(ii)(D)',    'Administrative Safeguards — Security Management Process',
      'Information System Activity Review',
      'Implement procedures to regularly review records of information system activity, such as audit logs, access reports, and security incident tracking reports.',
      'required',
      ['marshall-findings-collector', 'marshall-audit-chain-collector', 'supabase-advisor-collector'],
      [soc2Eq('CC4.1'), soc2Eq('CC4.2')]),
  ctl('164.308(a)(2)',           'Administrative Safeguards — Assigned Security Responsibility',
      'Assigned Security Responsibility',
      'Identify the security official who is responsible for the development and implementation of the policies and procedures required by this subpart.',
      'required',
      []),
  ctl('164.308(a)(3)(i)',        'Administrative Safeguards — Workforce Security',
      'Workforce Security',
      'Implement policies and procedures to ensure that all members of its workforce have appropriate access to electronic protected health information.',
      'required',
      ['users-roles-collector']),
  ctl('164.308(a)(3)(ii)(A)',    'Administrative Safeguards — Workforce Security',
      'Authorization and/or Supervision',
      'Implement procedures for the authorization and/or supervision of workforce members who work with electronic protected health information.',
      'addressable',
      ['privileged-actions-collector'],
      [soc2Eq('CC6.2')]),
  ctl('164.308(a)(3)(ii)(B)',    'Administrative Safeguards — Workforce Security',
      'Workforce Clearance Procedure',
      'Implement procedures to determine that the access of a workforce member to electronic protected health information is appropriate.',
      'addressable',
      ['users-roles-collector']),
  ctl('164.308(a)(3)(ii)(C)',    'Administrative Safeguards — Workforce Security',
      'Termination Procedures',
      'Implement procedures for terminating access to electronic protected health information when the employment of, or other arrangement with, a workforce member ends.',
      'addressable',
      ['users-roles-collector']),
  ctl('164.308(a)(4)(i)',        'Administrative Safeguards — Information Access Management',
      'Information Access Management',
      'Implement policies and procedures for authorizing access to electronic protected health information that are consistent with the applicable requirements of subpart E of this part.',
      'required',
      ['rls-policies-collector', 'users-roles-collector'],
      [soc2Eq('CC6.1')]),
  ctl('164.308(a)(4)(ii)(B)',    'Administrative Safeguards — Information Access Management',
      'Access Authorization',
      'Implement policies and procedures for granting access to electronic protected health information.',
      'addressable',
      ['users-roles-collector', 'privileged-actions-collector'],
      [soc2Eq('CC6.2')]),
  ctl('164.308(a)(4)(ii)(C)',    'Administrative Safeguards — Information Access Management',
      'Access Establishment and Modification',
      'Implement policies and procedures that document the access rights of workforce members.',
      'addressable',
      ['privileged-actions-collector']),
  ctl('164.308(a)(5)(i)',        'Administrative Safeguards — Security Awareness and Training',
      'Security Awareness and Training',
      'Implement a security awareness and training program for all members of its workforce.',
      'required',
      ['hipaa-workforce-training-collector']),
  ctl('164.308(a)(5)(ii)(A)',    'Administrative Safeguards — Security Awareness and Training',
      'Security Reminders',
      'Implement periodic security updates.',
      'addressable',
      ['hipaa-workforce-training-collector']),
  ctl('164.308(a)(5)(ii)(B)',    'Administrative Safeguards — Security Awareness and Training',
      'Protection from Malicious Software',
      'Implement procedures for guarding against, detecting, and reporting malicious software.',
      'addressable',
      ['dependabot-collector'],
      [soc2Eq('CC7.1')]),
  ctl('164.308(a)(5)(ii)(C)',    'Administrative Safeguards — Security Awareness and Training',
      'Log-in Monitoring',
      'Implement procedures for monitoring log-in attempts and reporting discrepancies.',
      'addressable',
      ['marshall-audit-chain-collector'],
      [soc2Eq('CC4.1')]),
  ctl('164.308(a)(5)(ii)(D)',    'Administrative Safeguards — Security Awareness and Training',
      'Password Management',
      'Implement procedures for creating, changing, and safeguarding passwords.',
      'addressable',
      ['mfa-enforcement-collector'],
      [soc2Eq('CC6.1')]),
  ctl('164.308(a)(6)(i)',        'Administrative Safeguards — Security Incident Procedures',
      'Security Incident Procedures',
      'Implement policies and procedures to address security incidents.',
      'required',
      ['marshall-incidents-collector'],
      [soc2Eq('CC7.3')]),
  ctl('164.308(a)(6)(ii)',       'Administrative Safeguards — Security Incident Procedures',
      'Response and Reporting',
      'Identify and respond to suspected or known security incidents; mitigate harmful effects; document incidents and their outcomes.',
      'required',
      ['marshall-incidents-collector', 'hipaa-breach-determinations-collector'],
      [soc2Eq('CC7.3')]),
  ctl('164.308(a)(7)(i)',        'Administrative Safeguards — Contingency Plan',
      'Contingency Plan',
      'Establish policies and procedures for responding to an emergency or other occurrence that damages systems containing ePHI.',
      'required',
      [],
      [soc2Eq('A1.2')]),
  ctl('164.308(a)(7)(ii)(A)',    'Administrative Safeguards — Contingency Plan',
      'Data Backup Plan',
      'Establish and implement procedures to create and maintain retrievable exact copies of electronic protected health information.',
      'required',
      [],
      [soc2Eq('A1.2')]),
  ctl('164.308(a)(7)(ii)(B)',    'Administrative Safeguards — Contingency Plan',
      'Disaster Recovery Plan',
      'Establish and implement as needed procedures to restore any loss of data.',
      'required',
      ['hipaa-contingency-plan-test-collector'],
      [soc2Eq('A1.2')]),
  ctl('164.308(a)(7)(ii)(C)',    'Administrative Safeguards — Contingency Plan',
      'Emergency Mode Operation Plan',
      'Establish and implement procedures to enable continuation of critical business processes while operating in emergency mode.',
      'required',
      ['hipaa-contingency-plan-test-collector']),
  ctl('164.308(a)(7)(ii)(D)',    'Administrative Safeguards — Contingency Plan',
      'Testing and Revision Procedures',
      'Implement procedures for periodic testing and revision of contingency plans.',
      'addressable',
      ['hipaa-contingency-plan-test-collector']),
  ctl('164.308(a)(7)(ii)(E)',    'Administrative Safeguards — Contingency Plan',
      'Applications and Data Criticality Analysis',
      'Assess the relative criticality of specific applications and data in support of other contingency plan components.',
      'addressable',
      []),
  ctl('164.308(a)(8)',           'Administrative Safeguards — Evaluation',
      'Evaluation',
      'Perform a periodic technical and non-technical evaluation.',
      'required',
      ['supabase-advisor-collector'],
      [soc2Eq('CC4.1')]),
  ctl('164.308(b)(1)',           'Administrative Safeguards — Business Associate Contracts',
      'Business Associate Contracts and Other Arrangements',
      'Obtain satisfactory assurances that business associates will appropriately safeguard ePHI.',
      'required',
      ['vendor-baas-collector'],
      [soc2Eq('CC9.2')]),
];

// ─── Physical Safeguards § 164.310 ────────────────────────────────────────
const PHYSICAL: readonly ControlPoint[] = [
  ctl('164.310(a)(1)',           'Physical Safeguards — Facility Access Controls',
      'Facility Access Controls',
      'Implement policies and procedures to limit physical access to electronic information systems and the facility in which they are housed.',
      'required',
      []),
  ctl('164.310(a)(2)(i)',        'Physical Safeguards — Facility Access Controls',
      'Contingency Operations',
      'Establish procedures that allow facility access in support of restoration of lost data.',
      'addressable',
      []),
  ctl('164.310(a)(2)(ii)',       'Physical Safeguards — Facility Access Controls',
      'Facility Security Plan',
      'Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft.',
      'addressable',
      []),
  ctl('164.310(a)(2)(iii)',      'Physical Safeguards — Facility Access Controls',
      'Access Control and Validation Procedures',
      `Implement procedures to control and validate a person's access to facilities based on their role or function.`,
      'addressable',
      []),
  ctl('164.310(a)(2)(iv)',       'Physical Safeguards — Facility Access Controls',
      'Maintenance Records',
      'Implement policies and procedures to document repairs and modifications to the physical components of a facility which are related to security.',
      'addressable',
      []),
  ctl('164.310(b)',              'Physical Safeguards — Workstation Use',
      'Workstation Use',
      'Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation or class of workstation.',
      'required',
      []),
  ctl('164.310(c)',              'Physical Safeguards — Workstation Security',
      'Workstation Security',
      'Implement physical safeguards for all workstations that access electronic protected health information.',
      'required',
      []),
  ctl('164.310(d)(1)',           'Physical Safeguards — Device and Media Controls',
      'Device and Media Controls',
      'Implement policies and procedures that govern the receipt and removal of hardware and electronic media that contain electronic protected health information.',
      'required',
      ['hipaa-device-media-control-collector']),
  ctl('164.310(d)(2)(i)',        'Physical Safeguards — Device and Media Controls',
      'Disposal',
      'Implement policies and procedures to address the final disposition of electronic protected health information, and the hardware or electronic media on which it is stored.',
      'required',
      ['hipaa-device-media-control-collector']),
  ctl('164.310(d)(2)(ii)',       'Physical Safeguards — Device and Media Controls',
      'Media Re-use',
      'Implement procedures for removal of electronic protected health information from electronic media before the media are made available for re-use.',
      'required',
      ['hipaa-device-media-control-collector']),
  ctl('164.310(d)(2)(iii)',      'Physical Safeguards — Device and Media Controls',
      'Accountability',
      'Maintain a record of the movements of hardware and electronic media and any person responsible therefore.',
      'addressable',
      ['hipaa-device-media-control-collector']),
  ctl('164.310(d)(2)(iv)',       'Physical Safeguards — Device and Media Controls',
      'Data Backup and Storage',
      'Create a retrievable, exact copy of electronic protected health information, when needed, before movement of equipment.',
      'addressable',
      []),
];

// ─── Technical Safeguards § 164.312 ──────────────────────────────────────
const TECHNICAL: readonly ControlPoint[] = [
  ctl('164.312(a)(1)',           'Technical Safeguards — Access Control',
      'Access Control',
      'Implement technical policies and procedures for electronic information systems that maintain electronic protected health information to allow access only to those persons or software programs that have been granted access rights.',
      'required',
      ['rls-policies-collector', 'users-roles-collector'],
      [soc2Eq('CC6.1')]),
  ctl('164.312(a)(2)(i)',        'Technical Safeguards — Access Control',
      'Unique User Identification',
      'Assign a unique name and/or number for identifying and tracking user identity.',
      'required',
      ['users-roles-collector'],
      [soc2Eq('CC6.1')]),
  ctl('164.312(a)(2)(ii)',       'Technical Safeguards — Access Control',
      'Emergency Access Procedure',
      'Establish (and implement as needed) procedures for obtaining necessary electronic protected health information during an emergency.',
      'required',
      ['hipaa-emergency-access-collector']),
  ctl('164.312(a)(2)(iii)',      'Technical Safeguards — Access Control',
      'Automatic Logoff',
      'Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity.',
      'addressable',
      []),
  ctl('164.312(a)(2)(iv)',       'Technical Safeguards — Access Control',
      'Encryption and Decryption',
      'Implement a mechanism to encrypt and decrypt electronic protected health information.',
      'addressable',
      ['key-rotation-collector', 'cert-expiry-collector'],
      [soc2Eq('C1.1'), soc2Eq('CC6.7')]),
  ctl('164.312(b)',              'Technical Safeguards — Audit Controls',
      'Audit Controls',
      'Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use electronic protected health information.',
      'required',
      ['marshall-audit-chain-collector'],
      [soc2Eq('CC4.1')]),
  ctl('164.312(c)(1)',           'Technical Safeguards — Integrity',
      'Integrity',
      'Implement policies and procedures to protect electronic protected health information from improper alteration or destruction.',
      'required',
      ['marshall-audit-chain-collector']),
  ctl('164.312(c)(2)',           'Technical Safeguards — Integrity',
      'Mechanism to Authenticate Electronic Protected Health Information',
      'Implement electronic mechanisms to corroborate that electronic protected health information has not been altered or destroyed in an unauthorized manner.',
      'addressable',
      ['marshall-audit-chain-collector']),
  ctl('164.312(d)',              'Technical Safeguards — Person or Entity Authentication',
      'Person or Entity Authentication',
      'Implement procedures to verify that a person or entity seeking access to electronic protected health information is the one claimed.',
      'required',
      ['mfa-enforcement-collector'],
      [soc2Eq('CC6.1')]),
  ctl('164.312(e)(1)',           'Technical Safeguards — Transmission Security',
      'Transmission Security',
      'Implement technical security measures to guard against unauthorized access to electronic protected health information that is being transmitted over an electronic communications network.',
      'required',
      ['cert-expiry-collector'],
      [soc2Eq('CC6.7')]),
  ctl('164.312(e)(2)(i)',        'Technical Safeguards — Transmission Security',
      'Integrity Controls',
      'Implement security measures to ensure that electronically transmitted electronic protected health information is not improperly modified without detection until disposed of.',
      'addressable',
      []),
  ctl('164.312(e)(2)(ii)',       'Technical Safeguards — Transmission Security',
      'Encryption',
      'Implement a mechanism to encrypt electronic protected health information whenever deemed appropriate.',
      'addressable',
      ['cert-expiry-collector', 'key-rotation-collector'],
      [soc2Eq('C1.1')]),
];

// ─── Organizational Requirements § 164.314 ───────────────────────────────
const ORGANIZATIONAL: readonly ControlPoint[] = [
  ctl('164.314(a)(1)',           'Organizational Requirements — Business Associate Contracts',
      'Business Associate Contracts or Other Arrangements',
      'Implement the requirements for business associate contracts.',
      'required',
      ['vendor-baas-collector'],
      [soc2Eq('CC9.2')]),
  ctl('164.314(a)(2)(i)',        'Organizational Requirements — Business Associate Contracts',
      'Business Associate Contracts — specific content',
      'Business associate contracts must provide that the business associate will comply with the applicable requirements of this subpart.',
      'required',
      ['vendor-baas-collector']),
  ctl('164.314(b)(1)',           'Organizational Requirements — Group Health Plans',
      'Requirements for Group Health Plans',
      'Except as provided under paragraph (b)(2) of this section, the plan documents of the group health plan must be amended to incorporate provisions to safeguard ePHI.',
      'required',
      []),
];

// ─── Documentation Requirements § 164.316 ────────────────────────────────
const DOCUMENTATION: readonly ControlPoint[] = [
  ctl('164.316(a)',              'Documentation Requirements — Policies and Procedures',
      'Policies and Procedures',
      'Implement reasonable and appropriate policies and procedures to comply with the standards, implementation specifications, or other requirements of this subpart.',
      'required',
      []),
  ctl('164.316(b)(1)',           'Documentation Requirements — Documentation',
      'Documentation — maintain in written or electronic form',
      'Maintain the policies and procedures implemented to comply with this subpart in written (which may be electronic) form.',
      'required',
      []),
  ctl('164.316(b)(2)(i)',        'Documentation Requirements — Documentation',
      'Time Limit',
      'Retain the documentation for 6 years from the date of its creation or the date when it last was in effect, whichever is later.',
      'required',
      []),
  ctl('164.316(b)(2)(ii)',       'Documentation Requirements — Documentation',
      'Availability',
      'Make documentation available to those persons responsible for implementing the procedures to which the documentation pertains.',
      'required',
      []),
  ctl('164.316(b)(2)(iii)',      'Documentation Requirements — Documentation',
      'Updates',
      'Review documentation periodically, and update as needed, in response to environmental or operational changes affecting the security of the electronic protected health information.',
      'required',
      []),
];

export const HIPAA_CONTROL_POINTS: readonly ControlPoint[] = [
  ...ADMINISTRATIVE,
  ...PHYSICAL,
  ...TECHNICAL,
  ...ORGANIZATIONAL,
  ...DOCUMENTATION,
];

// Manual-vault artifacts (each a specific HIPAA document requirement)
const SPECIAL_ARTIFACTS: readonly SpecialArtifactRequirement[] = [
  { id: 'hipaa_risk_analysis',       displayName: 'Risk Analysis (45 CFR 164.308(a)(1)(ii)(A))',
    required: true, evidenceSource: 'manual_vault', maxAgeDays: 365, attestationRequired: true },
  { id: 'hipaa_sanction_policy',     displayName: 'Sanction Policy (45 CFR 164.308(a)(1)(ii)(C))',
    required: true, evidenceSource: 'manual_vault', maxAgeDays: 730, attestationRequired: true },
  { id: 'hipaa_contingency_plan',    displayName: 'Contingency Plan (Data Backup + DR + Emergency Mode)',
    required: true, evidenceSource: 'manual_vault', maxAgeDays: 365, attestationRequired: true },
  { id: 'hipaa_facility_security',   displayName: 'Facility Security Plan (45 CFR 164.310(a)(2)(ii))',
    required: false, evidenceSource: 'manual_vault', maxAgeDays: 730, attestationRequired: false },
  { id: 'hipaa_security_officer_designation', displayName: 'Security Officer Designation (45 CFR 164.308(a)(2))',
    required: true, evidenceSource: 'manual_vault', maxAgeDays: 1095, attestationRequired: true },
  { id: 'hipaa_annual_evaluation',   displayName: 'Annual Security Evaluation (45 CFR 164.308(a)(8))',
    required: true, evidenceSource: 'manual_vault', maxAgeDays: 365, attestationRequired: true },
];

export const HIPAA_FRAMEWORK: FrameworkDefinition = {
  id: 'hipaa_security',
  version: 'hipaa-security-rule-45cfr164',
  displayName: 'HIPAA Security Rule (45 CFR 164.302-318)',
  registryVersion: REGISTRY_VERSION,
  attestationType: 'continuous_with_annual_risk_analysis',
  attestorRole: 'security_officer',
  attestationLanguage:
    `I, the undersigned Security Officer of FarmCeutica Wellness LLC as designated under 45 CFR 164.308(a)(2), attest that the foregoing safeguard descriptions accurately describe FarmCeutica's implementation of the identified HIPAA Security Rule safeguards during the period specified.`,
  controlPoints: HIPAA_CONTROL_POINTS,
  specialArtifacts: SPECIAL_ARTIFACTS,
  scopeDeclaration: { shape: 'hipaa_covered_entity', label: 'Covered entity scope' },
  categoryDirs: {
    administrative: 'administrative-safeguards',
    physical:       'physical-safeguards',
    technical:      'technical-safeguards',
    organizational: 'organizational-requirements',
    documentation:  'documentation-requirements',
    breach:         'breach-records',
  },
  narratorPromptAddendum:
    'HIPAA voice: cite 45 CFR sections in the form 164.xxx(y)(z). Distinguish Required vs. Addressable safeguards explicitly. For Addressable safeguards state which of the three paths was taken (implemented, implemented-with-equivalent-measures, documented-as-not-reasonable). Avoid legal conclusions; describe implementation state factually.',
};
