// Prompt #127 P5: ISO/IEC 27001:2022 framework definition.
//
// Full population of Annex A (93 controls across 4 themes) plus the
// mandatory ISMS clauses (4-10) that drive certification-audit evidence.
//
// ISO 27001 differs from SOC 2 and HIPAA in two load-bearing ways:
//   1. Statement of Applicability (SoA): every Annex A control is either
//      'applicable' (default) or 'excluded' with justification. The SoA
//      status drives whether the narrator emits implementation prose or
//      exclusion rationale.
//   2. Mandatory Clauses 4-10 carry their own evidence distinct from
//      Annex A; they describe the ISMS management system itself
//      (context, leadership, planning, support, operation, performance
//      evaluation, improvement).
//
// Many Annex A controls overlap with SOC 2 CC / HIPAA 164.xxx controls
// and carry crossFrameworkReferences so evidence already collected by
// #122 or the #127 P3 HIPAA collectors satisfies ISO too.

import type {
  ControlPoint,
  CrossFrameworkReference,
  FrameworkDefinition,
  NarratorSectionSpec,
  SpecialArtifactRequirement,
} from '../types';

const REGISTRY_VERSION = 'v1.0.0';

// ─── Narrator sections ────────────────────────────────────────────────────
// ISO voice: objective -> implementation -> effectiveness, plus an
// always-present SoA applicability determination (which doubles as the
// exclusion-justification section when the control is excluded).

const STANDARD_SECTIONS: readonly NarratorSectionSpec[] = [
  { kind: 'control_objective',              required: true,  carryoverAllowed: true,  generatorTone: 'declarative' },
  { kind: 'implementation_description',     required: true,  carryoverAllowed: false, generatorTone: 'outcome_based' },
  { kind: 'effectiveness_assessment',       required: true,  carryoverAllowed: false, generatorTone: 'outcome_based' },
  { kind: 'soa_applicability_determination', required: true, carryoverAllowed: false, generatorTone: 'declarative' },
];

// Clause-level sections drop the SoA determination (clauses are always applicable).
const CLAUSE_SECTIONS: readonly NarratorSectionSpec[] = [
  { kind: 'clause_objective',           required: true, carryoverAllowed: true,  generatorTone: 'declarative' },
  { kind: 'clause_implementation',      required: true, carryoverAllowed: false, generatorTone: 'outcome_based' },
  { kind: 'clause_effectiveness',       required: true, carryoverAllowed: false, generatorTone: 'outcome_based' },
];

// ─── Helpers ──────────────────────────────────────────────────────────────

function soc2Eq(controlId: string): CrossFrameworkReference {
  return { framework: 'soc2', controlId, relationship: 'equivalent' };
}
function soc2Overlap(controlId: string): CrossFrameworkReference {
  return { framework: 'soc2', controlId, relationship: 'overlapping' };
}
function hipaaEq(controlId: string): CrossFrameworkReference {
  return { framework: 'hipaa_security', controlId, relationship: 'equivalent' };
}
function hipaaOverlap(controlId: string): CrossFrameworkReference {
  return { framework: 'hipaa_security', controlId, relationship: 'overlapping' };
}

function annexA(
  id: string,
  category: string,
  name: string,
  description: string,
  evidenceSources: readonly string[],
  crossFrameworkReferences: readonly CrossFrameworkReference[] = [],
  defaultApplicability: 'applicable' | 'excluded' = 'applicable',
): ControlPoint {
  return {
    id,
    framework: 'iso_27001_2022',
    category,
    name,
    description,
    defaultApplicability,
    evidenceSources,
    narratorSections: STANDARD_SECTIONS,
    crossFrameworkReferences,
  };
}

function clause(
  id: string,
  category: string,
  name: string,
  description: string,
  evidenceSources: readonly string[] = [],
  crossFrameworkReferences: readonly CrossFrameworkReference[] = [],
): ControlPoint {
  return {
    id,
    framework: 'iso_27001_2022',
    category,
    name,
    description,
    evidenceSources,
    narratorSections: CLAUSE_SECTIONS,
    crossFrameworkReferences,
  };
}

// ─── ISMS Clauses (4-10) ──────────────────────────────────────────────────

const ISMS_CLAUSES: readonly ControlPoint[] = [
  clause('Clause 4.1', 'ISMS Clause 4: Context',
    'Understanding the organization and its context',
    'Determine external and internal issues relevant to the ISMS purpose that affect its ability to achieve intended outcomes.',
    []),
  clause('Clause 4.2', 'ISMS Clause 4: Context',
    'Needs and expectations of interested parties',
    'Identify interested parties relevant to the ISMS and their information security requirements.',
    []),
  clause('Clause 4.3', 'ISMS Clause 4: Context',
    'Scope of the ISMS',
    'Determine the boundaries and applicability of the ISMS; documented in the ISMS Scope Statement.',
    ['iso-isms-scope-collector']),
  clause('Clause 4.4', 'ISMS Clause 4: Context',
    'Information security management system',
    'Establish, implement, maintain and continually improve the ISMS in accordance with the standard.',
    []),
  clause('Clause 5.1', 'ISMS Clause 5: Leadership',
    'Leadership and commitment',
    'Top management demonstrates leadership and commitment to the ISMS via policy, resources, and direction.',
    ['iso-management-review-collector']),
  clause('Clause 5.2', 'ISMS Clause 5: Leadership',
    'Information security policy',
    'Establish, communicate, and maintain an information security policy appropriate to the organization.',
    []),
  clause('Clause 5.3', 'ISMS Clause 5: Leadership',
    'Roles, responsibilities and authorities',
    'Assign and communicate responsibilities and authorities for the ISMS.',
    [], [hipaaEq('164.308(a)(2)')]),
  clause('Clause 6.1', 'ISMS Clause 6: Planning',
    'Actions to address risks and opportunities',
    'Perform information security risk assessment and risk treatment; document results; produce the Statement of Applicability.',
    ['iso-risk-register-collector', 'iso-soa-coverage-collector']),
  clause('Clause 6.2', 'ISMS Clause 6: Planning',
    'Information security objectives',
    'Establish measurable information security objectives at relevant functions and levels, aligned with the policy.',
    []),
  clause('Clause 7.2', 'ISMS Clause 7: Support',
    'Competence',
    'Determine necessary competence and ensure persons are competent based on education, training, or experience.',
    []),
  clause('Clause 7.3', 'ISMS Clause 7: Support',
    'Awareness',
    'Ensure persons doing work under the organization are aware of the policy, their contribution, and implications of nonconformity.',
    [], [hipaaEq('164.308(a)(5)(i)')]),
  clause('Clause 7.5', 'ISMS Clause 7: Support',
    'Documented information',
    'Control creation, update, retention, and access of documented information required by the ISMS.',
    []),
  clause('Clause 8.1', 'ISMS Clause 8: Operation',
    'Operational planning and control',
    'Plan, implement, and control processes to meet ISMS requirements; keep documented information for confidence.',
    []),
  clause('Clause 8.2', 'ISMS Clause 8: Operation',
    'Information security risk assessment',
    'Perform information security risk assessments at planned intervals or when significant changes occur.',
    ['iso-risk-register-collector']),
  clause('Clause 8.3', 'ISMS Clause 8: Operation',
    'Information security risk treatment',
    'Implement the risk treatment plan; keep documented information of results.',
    ['iso-risk-register-collector', 'iso-soa-coverage-collector']),
  clause('Clause 9.1', 'ISMS Clause 9: Performance Evaluation',
    'Monitoring, measurement, analysis and evaluation',
    'Evaluate the ISMS performance and effectiveness of information security through selected methods and metrics.',
    [], [soc2Eq('CC4.1')]),
  clause('Clause 9.2', 'ISMS Clause 9: Performance Evaluation',
    'Internal audit',
    'Conduct internal audits at planned intervals to provide information on whether the ISMS conforms to requirements.',
    ['iso-internal-audit-collector']),
  clause('Clause 9.3', 'ISMS Clause 9: Performance Evaluation',
    'Management review',
    'Top management reviews the ISMS at planned intervals to ensure its continuing suitability, adequacy, and effectiveness.',
    ['iso-management-review-collector']),
  clause('Clause 10.1', 'ISMS Clause 10: Improvement',
    'Continual improvement',
    'Continually improve the suitability, adequacy, and effectiveness of the ISMS.',
    []),
  clause('Clause 10.2', 'ISMS Clause 10: Improvement',
    'Nonconformity and corrective action',
    'React to nonconformity, evaluate need for action to prevent recurrence, implement corrective action, retain documented evidence.',
    ['iso-nonconformity-collector'], [soc2Overlap('CC4.2')]),
];

// ─── Annex A.5 Organizational (37 controls) ──────────────────────────────

const ORGANIZATIONAL: readonly ControlPoint[] = [
  annexA('A.5.1', 'Annex A.5: Organizational', 'Policies for information security',
    'Define, approve, publish, communicate and review information security policies at planned intervals and when significant changes occur.',
    []),
  annexA('A.5.2', 'Annex A.5: Organizational', 'Information security roles and responsibilities',
    'Define and allocate information security roles and responsibilities according to the organization needs.',
    [], [hipaaEq('164.308(a)(2)')]),
  annexA('A.5.3', 'Annex A.5: Organizational', 'Segregation of duties',
    'Segregate conflicting duties and areas of responsibility.',
    [], [soc2Overlap('CC6.1')]),
  annexA('A.5.4', 'Annex A.5: Organizational', 'Management responsibilities',
    'Require all personnel to apply information security in accordance with established policies and procedures.',
    []),
  annexA('A.5.5', 'Annex A.5: Organizational', 'Contact with authorities',
    'Establish and maintain contact with relevant authorities.',
    []),
  annexA('A.5.6', 'Annex A.5: Organizational', 'Contact with special interest groups',
    'Establish and maintain contact with special interest groups or other specialist security forums.',
    []),
  annexA('A.5.7', 'Annex A.5: Organizational', 'Threat intelligence',
    'Collect and analyze information relating to information security threats to produce threat intelligence.',
    ['hounddog-findings-collector', 'hounddog-signals-collector']),
  annexA('A.5.8', 'Annex A.5: Organizational', 'Information security in project management',
    'Integrate information security into project management.',
    []),
  annexA('A.5.9', 'Annex A.5: Organizational', 'Inventory of information and other associated assets',
    'Develop and maintain an inventory of information and other associated assets with owners identified.',
    []),
  annexA('A.5.10', 'Annex A.5: Organizational', 'Acceptable use of information and other associated assets',
    'Identify, document, and implement rules for acceptable use and procedures for handling information and other associated assets.',
    []),
  annexA('A.5.11', 'Annex A.5: Organizational', 'Return of assets',
    'Require personnel to return all of the organization assets in their possession upon termination.',
    ['hipaa-device-media-control-collector'], [hipaaEq('164.310(d)(1)')]),
  annexA('A.5.12', 'Annex A.5: Organizational', 'Classification of information',
    'Classify information according to information security needs based on confidentiality, integrity, availability, and relevant interested party requirements.',
    []),
  annexA('A.5.13', 'Annex A.5: Organizational', 'Labelling of information',
    'Develop and implement an appropriate set of procedures for information labelling in accordance with the classification scheme.',
    []),
  annexA('A.5.14', 'Annex A.5: Organizational', 'Information transfer',
    'Establish information transfer rules, procedures, or agreements for all types of transfer facilities within the organization and between the organization and external parties.',
    []),
  annexA('A.5.15', 'Annex A.5: Organizational', 'Access control',
    'Establish and implement rules to control physical and logical access to information and other associated assets based on business and information security requirements.',
    ['mfa-enforcement-collector'], [soc2Eq('CC6.1'), hipaaEq('164.312(a)(1)')]),
  annexA('A.5.16', 'Annex A.5: Organizational', 'Identity management',
    'Manage the full life cycle of identities.',
    [], [soc2Overlap('CC6.2'), hipaaOverlap('164.308(a)(4)(i)')]),
  annexA('A.5.17', 'Annex A.5: Organizational', 'Authentication information',
    'Properly manage the allocation and management of authentication information.',
    ['mfa-enforcement-collector'], [hipaaEq('164.312(d)')]),
  annexA('A.5.18', 'Annex A.5: Organizational', 'Access rights',
    'Provision, review, modify and remove access rights to information and other associated assets in accordance with the topic-specific policy.',
    [], [hipaaOverlap('164.308(a)(4)(i)')]),
  annexA('A.5.19', 'Annex A.5: Organizational', 'Information security in supplier relationships',
    'Define and implement processes and procedures to manage information security risks associated with the use of supplier products or services.',
    ['vendor-baas-collector'], [soc2Eq('CC9.2'), hipaaEq('164.308(b)(1)')]),
  annexA('A.5.20', 'Annex A.5: Organizational', 'Addressing information security within supplier agreements',
    'Establish and agree relevant information security requirements with each supplier based on the type of supplier relationship.',
    ['vendor-baas-collector'], [soc2Overlap('CC9.2'), hipaaEq('164.314(a)(1)')]),
  annexA('A.5.21', 'Annex A.5: Organizational', 'Managing information security in the ICT supply chain',
    'Define and implement processes and procedures to manage information security risks associated with the ICT products and services supply chain.',
    ['vendor-baas-collector']),
  annexA('A.5.22', 'Annex A.5: Organizational', 'Monitoring, review and change management of supplier services',
    'Regularly monitor, review, evaluate and manage changes in supplier information security practices and service delivery.',
    ['vendor-baas-collector']),
  annexA('A.5.23', 'Annex A.5: Organizational', 'Information security for use of cloud services',
    'Establish processes for the acquisition, use, management, and exit from cloud services in accordance with information security requirements.',
    ['vendor-baas-collector']),
  annexA('A.5.24', 'Annex A.5: Organizational', 'Information security incident management planning and preparation',
    'Plan and prepare for managing information security incidents by defining, establishing, and communicating processes, roles, and responsibilities.',
    ['marshall-incidents-collector'], [hipaaEq('164.308(a)(6)(i)')]),
  annexA('A.5.25', 'Annex A.5: Organizational', 'Assessment and decision on information security events',
    'Assess information security events and decide if they are to be categorized as information security incidents.',
    ['marshall-incidents-collector', 'hipaa-breach-determinations-collector'], [hipaaOverlap('164.308(a)(6)(ii)')]),
  annexA('A.5.26', 'Annex A.5: Organizational', 'Response to information security incidents',
    'Respond to information security incidents in accordance with documented procedures.',
    ['marshall-incidents-collector'], [hipaaEq('164.308(a)(6)(ii)')]),
  annexA('A.5.27', 'Annex A.5: Organizational', 'Learning from information security incidents',
    'Use knowledge gained from information security incidents to strengthen and improve information security controls.',
    ['marshall-incidents-collector', 'iso-nonconformity-collector']),
  annexA('A.5.28', 'Annex A.5: Organizational', 'Collection of evidence',
    'Establish procedures for identification, collection, acquisition, and preservation of evidence related to information security events.',
    ['marshall-audit-chain-collector'], [soc2Eq('CC4.3')]),
  annexA('A.5.29', 'Annex A.5: Organizational', 'Information security during disruption',
    'Plan how to maintain information security at an appropriate level during disruption.',
    ['hipaa-contingency-plan-test-collector'], [hipaaOverlap('164.308(a)(7)(i)')]),
  annexA('A.5.30', 'Annex A.5: Organizational', 'ICT readiness for business continuity',
    'Plan, implement, maintain, and test ICT readiness based on business continuity objectives and ICT continuity requirements.',
    ['hipaa-contingency-plan-test-collector']),
  annexA('A.5.31', 'Annex A.5: Organizational', 'Legal, statutory, regulatory and contractual requirements',
    'Identify, document, and keep up to date legal, statutory, regulatory and contractual requirements relevant to information security.',
    []),
  annexA('A.5.32', 'Annex A.5: Organizational', 'Intellectual property rights',
    'Implement appropriate procedures to protect intellectual property rights.',
    []),
  annexA('A.5.33', 'Annex A.5: Organizational', 'Protection of records',
    'Protect records from loss, destruction, falsification, unauthorized access, and unauthorized release.',
    [], [hipaaOverlap('164.310(d)(1)')]),
  annexA('A.5.34', 'Annex A.5: Organizational', 'Privacy and protection of PII',
    'Identify and meet requirements regarding the preservation of privacy and protection of PII according to applicable laws, regulations, and contractual requirements.',
    []),
  annexA('A.5.35', 'Annex A.5: Organizational', 'Independent review of information security',
    'Review information security and its management, including people, processes, and technology, independently at planned intervals or when significant changes occur.',
    ['iso-internal-audit-collector']),
  annexA('A.5.36', 'Annex A.5: Organizational', 'Compliance with policies, rules and standards for information security',
    'Regularly review compliance with information security policies, rules, standards, and other requirements applicable to the organization.',
    ['iso-internal-audit-collector']),
  annexA('A.5.37', 'Annex A.5: Organizational', 'Documented operating procedures',
    'Document and make available operating procedures for information processing facilities to personnel who need them.',
    []),
];

// ─── Annex A.6 People (8 controls) ───────────────────────────────────────

const PEOPLE: readonly ControlPoint[] = [
  annexA('A.6.1', 'Annex A.6: People', 'Screening',
    'Carry out background verification checks on all candidates for employment prior to joining, proportional to business requirements, classification of information accessed, and perceived risks.',
    []),
  annexA('A.6.2', 'Annex A.6: People', 'Terms and conditions of employment',
    'State responsibilities of personnel for information security in employment contractual agreements.',
    []),
  annexA('A.6.3', 'Annex A.6: People', 'Information security awareness, education and training',
    'Provide awareness, education, and training relevant to personnel job functions and updated regularly.',
    ['hipaa-workforce-training-collector'], [hipaaEq('164.308(a)(5)(i)')]),
  annexA('A.6.4', 'Annex A.6: People', 'Disciplinary process',
    'Formalize and communicate a disciplinary process to take action against personnel who have committed an information security policy violation.',
    [], [hipaaEq('164.308(a)(1)(ii)(C)')]),
  annexA('A.6.5', 'Annex A.6: People', 'Responsibilities after termination or change of employment',
    'Define, enforce, and communicate information security responsibilities and duties that remain valid after termination or change of employment.',
    []),
  annexA('A.6.6', 'Annex A.6: People', 'Confidentiality or non-disclosure agreements',
    'Identify, document, regularly review, and require personnel and other interested parties to sign confidentiality or non-disclosure agreements reflecting organization needs.',
    []),
  annexA('A.6.7', 'Annex A.6: People', 'Remote working',
    'Implement security measures when personnel work remotely to protect information accessed, processed, or stored outside the organization premises.',
    []),
  annexA('A.6.8', 'Annex A.6: People', 'Information security event reporting',
    'Provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.',
    ['marshall-incidents-collector']),
];

// ─── Annex A.7 Physical (14 controls) ────────────────────────────────────

const PHYSICAL: readonly ControlPoint[] = [
  annexA('A.7.1', 'Annex A.7: Physical', 'Physical security perimeters',
    'Define and use security perimeters to protect areas containing information and other associated assets.',
    []),
  annexA('A.7.2', 'Annex A.7: Physical', 'Physical entry',
    'Protect secure areas by appropriate entry controls and access points.',
    []),
  annexA('A.7.3', 'Annex A.7: Physical', 'Securing offices, rooms and facilities',
    'Design and implement physical security for offices, rooms, and facilities.',
    []),
  annexA('A.7.4', 'Annex A.7: Physical', 'Physical security monitoring',
    'Continuously monitor premises for unauthorized physical access.',
    []),
  annexA('A.7.5', 'Annex A.7: Physical', 'Protecting against physical and environmental threats',
    'Design and implement protection against physical and environmental threats such as natural disasters and intentional physical attacks.',
    []),
  annexA('A.7.6', 'Annex A.7: Physical', 'Working in secure areas',
    'Design and implement security measures for working in secure areas.',
    []),
  annexA('A.7.7', 'Annex A.7: Physical', 'Clear desk and clear screen',
    'Define and enforce clear desk rules for papers and removable storage media and clear screen rules for information processing facilities.',
    []),
  annexA('A.7.8', 'Annex A.7: Physical', 'Equipment siting and protection',
    'Site and protect equipment securely.',
    []),
  annexA('A.7.9', 'Annex A.7: Physical', 'Security of assets off-premises',
    'Protect off-site assets.',
    ['hipaa-device-media-control-collector']),
  annexA('A.7.10', 'Annex A.7: Physical', 'Storage media',
    'Manage storage media through their life cycle of acquisition, use, transportation, and disposal in accordance with the classification scheme and handling requirements.',
    ['hipaa-device-media-control-collector'], [hipaaEq('164.310(d)(1)')]),
  annexA('A.7.11', 'Annex A.7: Physical', 'Supporting utilities',
    'Protect information processing facilities from power failures and other disruptions caused by failures in supporting utilities.',
    []),
  annexA('A.7.12', 'Annex A.7: Physical', 'Cabling security',
    'Protect cables carrying power, data, or supporting information services from interception, interference, or damage.',
    []),
  annexA('A.7.13', 'Annex A.7: Physical', 'Equipment maintenance',
    'Correctly maintain equipment to ensure availability, integrity, and confidentiality of information.',
    []),
  annexA('A.7.14', 'Annex A.7: Physical', 'Secure disposal or re-use of equipment',
    'Verify items of equipment containing storage media to ensure any sensitive data and licensed software have been removed or securely overwritten prior to disposal or re-use.',
    ['hipaa-device-media-control-collector'], [hipaaEq('164.310(d)(2)(i)')]),
];

// ─── Annex A.8 Technological (34 controls) ───────────────────────────────

const TECHNOLOGICAL: readonly ControlPoint[] = [
  annexA('A.8.1', 'Annex A.8: Technological', 'User end point devices',
    'Protect information stored on, processed by, or accessible via user end point devices.',
    ['hipaa-device-media-control-collector']),
  annexA('A.8.2', 'Annex A.8: Technological', 'Privileged access rights',
    'Restrict and manage the allocation and use of privileged access rights.',
    ['mfa-enforcement-collector'], [soc2Eq('CC6.1')]),
  annexA('A.8.3', 'Annex A.8: Technological', 'Information access restriction',
    'Restrict access to information and other associated assets in accordance with the established topic-specific policy on access control.',
    [], [soc2Eq('CC6.1'), hipaaEq('164.312(a)(1)')]),
  annexA('A.8.4', 'Annex A.8: Technological', 'Access to source code',
    'Manage read and write access to source code, development tools, and software libraries.',
    []),
  annexA('A.8.5', 'Annex A.8: Technological', 'Secure authentication',
    'Implement secure authentication technologies and procedures based on information access restrictions and the topic-specific policy on access control.',
    ['mfa-enforcement-collector'], [hipaaEq('164.312(d)')]),
  annexA('A.8.6', 'Annex A.8: Technological', 'Capacity management',
    'Monitor and adjust use of resources in line with current and expected capacity requirements.',
    ['supabase-advisor-collector']),
  annexA('A.8.7', 'Annex A.8: Technological', 'Protection against malware',
    'Implement protection against malware supported by appropriate user awareness.',
    []),
  annexA('A.8.8', 'Annex A.8: Technological', 'Management of technical vulnerabilities',
    'Obtain information about technical vulnerabilities of information systems in use, evaluate exposure, and take appropriate measures.',
    ['supabase-advisor-collector', 'hounddog-findings-collector'], [soc2Overlap('CC7.1')]),
  annexA('A.8.9', 'Annex A.8: Technological', 'Configuration management',
    'Establish, document, implement, monitor, and review configurations including security configurations of hardware, software, services, and networks.',
    ['supabase-advisor-collector']),
  annexA('A.8.10', 'Annex A.8: Technological', 'Information deletion',
    'Delete information stored in information systems, devices, or any other storage media when no longer required.',
    ['hipaa-device-media-control-collector']),
  annexA('A.8.11', 'Annex A.8: Technological', 'Data masking',
    'Use data masking in accordance with the topic-specific policy on access control, other related topic-specific policies, and business requirements, taking applicable legislation into consideration.',
    []),
  annexA('A.8.12', 'Annex A.8: Technological', 'Data leakage prevention',
    'Apply data leakage prevention measures to systems, networks, and any other devices that process, store, or transmit sensitive information.',
    []),
  annexA('A.8.13', 'Annex A.8: Technological', 'Information backup',
    'Maintain and regularly test backup copies of information, software, and systems in accordance with the agreed topic-specific policy on backup.',
    ['hipaa-contingency-plan-test-collector'], [hipaaEq('164.308(a)(7)(ii)(A)')]),
  annexA('A.8.14', 'Annex A.8: Technological', 'Redundancy of information processing facilities',
    'Implement information processing facilities with sufficient redundancy to meet availability requirements.',
    []),
  annexA('A.8.15', 'Annex A.8: Technological', 'Logging',
    'Produce, store, protect, and analyze logs of activities, exceptions, faults, and other relevant events.',
    ['marshall-audit-chain-collector'], [soc2Eq('CC4.3'), hipaaEq('164.312(b)')]),
  annexA('A.8.16', 'Annex A.8: Technological', 'Monitoring activities',
    'Monitor networks, systems, and applications for anomalous behaviour and take appropriate actions to evaluate potential information security incidents.',
    ['hounddog-signals-collector', 'marshall-findings-collector'], [soc2Eq('CC4.1')]),
  annexA('A.8.17', 'Annex A.8: Technological', 'Clock synchronization',
    'Synchronize clocks of information processing systems to approved time sources.',
    []),
  annexA('A.8.18', 'Annex A.8: Technological', 'Use of privileged utility programs',
    'Restrict and tightly control the use of utility programs that can be capable of overriding system and application controls.',
    []),
  annexA('A.8.19', 'Annex A.8: Technological', 'Installation of software on operational systems',
    'Implement procedures and measures to securely manage software installation on operational systems.',
    []),
  annexA('A.8.20', 'Annex A.8: Technological', 'Networks security',
    'Secure, manage, and control networks and network devices to protect information in systems and applications.',
    [], [hipaaEq('164.312(e)(1)')]),
  annexA('A.8.21', 'Annex A.8: Technological', 'Security of network services',
    'Identify and implement security mechanisms, service levels, and service requirements of network services.',
    []),
  annexA('A.8.22', 'Annex A.8: Technological', 'Segregation of networks',
    'Segregate groups of information services, users, and information systems in networks.',
    []),
  annexA('A.8.23', 'Annex A.8: Technological', 'Web filtering',
    'Manage access to external websites to reduce exposure to malicious content.',
    []),
  annexA('A.8.24', 'Annex A.8: Technological', 'Use of cryptography',
    'Define and implement rules for the effective use of cryptography, including cryptographic key management.',
    [], [hipaaEq('164.312(a)(2)(iv)')]),
  annexA('A.8.25', 'Annex A.8: Technological', 'Secure development life cycle',
    'Establish and apply rules for the secure development of software and systems.',
    ['github-prs-collector']),
  annexA('A.8.26', 'Annex A.8: Technological', 'Application security requirements',
    'Identify, specify, and approve information security requirements when developing or acquiring applications.',
    []),
  annexA('A.8.27', 'Annex A.8: Technological', 'Secure system architecture and engineering principles',
    'Establish, document, maintain, and apply principles for engineering secure systems.',
    []),
  annexA('A.8.28', 'Annex A.8: Technological', 'Secure coding',
    'Apply secure coding principles to software development.',
    ['github-prs-collector']),
  annexA('A.8.29', 'Annex A.8: Technological', 'Security testing in development and acceptance',
    'Define and implement security testing processes in the development life cycle.',
    ['github-prs-collector']),
  annexA('A.8.30', 'Annex A.8: Technological', 'Outsourced development',
    'Direct, monitor, and review activities related to outsourced system development.',
    []),
  annexA('A.8.31', 'Annex A.8: Technological', 'Separation of development, test and production environments',
    'Separate and secure development, test, and production environments.',
    []),
  annexA('A.8.32', 'Annex A.8: Technological', 'Change management',
    'Subject changes to information processing facilities and information systems to change management procedures.',
    ['github-prs-collector'], [soc2Eq('CC8.1')]),
  annexA('A.8.33', 'Annex A.8: Technological', 'Test information',
    'Select, protect, and manage test information appropriately.',
    []),
  annexA('A.8.34', 'Annex A.8: Technological', 'Protection of information systems during audit testing',
    'Plan and agree audit tests and other assurance activities involving assessment of operational systems between the tester and appropriate management.',
    []),
];

// ─── Combined control points ──────────────────────────────────────────────

export const ISO27001_CONTROL_POINTS: readonly ControlPoint[] = [
  ...ISMS_CLAUSES,
  ...ORGANIZATIONAL,
  ...PEOPLE,
  ...PHYSICAL,
  ...TECHNOLOGICAL,
];

// ─── Special artifacts ────────────────────────────────────────────────────

const SPECIAL_ARTIFACTS: readonly SpecialArtifactRequirement[] = [
  {
    id: 'iso_statement_of_applicability',
    displayName: 'Statement of Applicability (SoA)',
    required: true,
    evidenceSource: 'automated_collector',
    maxAgeDays: 365,
    attestationRequired: true,
  },
  {
    id: 'iso_isms_scope_document',
    displayName: 'ISMS Scope Statement',
    required: true,
    evidenceSource: 'manual_vault',
    maxAgeDays: 365,
    attestationRequired: true,
  },
  {
    id: 'iso_risk_assessment_report',
    displayName: 'Information Security Risk Assessment Report',
    required: true,
    evidenceSource: 'automated_collector',
    maxAgeDays: 365,
    attestationRequired: true,
  },
  {
    id: 'iso_risk_treatment_plan',
    displayName: 'Risk Treatment Plan',
    required: true,
    evidenceSource: 'automated_collector',
    maxAgeDays: 365,
    attestationRequired: true,
  },
  {
    id: 'iso_information_security_policy',
    displayName: 'Information Security Policy',
    required: true,
    evidenceSource: 'manual_vault',
    maxAgeDays: 365,
    attestationRequired: true,
  },
  {
    id: 'iso_management_review_minutes',
    displayName: 'Management Review Minutes',
    required: true,
    evidenceSource: 'automated_collector',
    maxAgeDays: 365,
    attestationRequired: true,
  },
];

// ─── Framework definition ─────────────────────────────────────────────────

export const ISO27001_FRAMEWORK: FrameworkDefinition = {
  id: 'iso_27001_2022',
  version: 'iso-27001-2022',
  displayName: 'ISO/IEC 27001:2022',
  registryVersion: REGISTRY_VERSION,
  attestationType: 'certification_audit',
  attestorRole: 'isms_manager',
  attestationLanguage:
    `I, the undersigned ISMS Manager of FarmCeutica Wellness LLC, attest that the foregoing descriptions accurately describe FarmCeutica's implementation and effectiveness of the identified ISO/IEC 27001:2022 controls during the period specified, and that the Statement of Applicability accurately reflects the applicability determinations for each Annex A control.`,
  controlPoints: ISO27001_CONTROL_POINTS,
  specialArtifacts: SPECIAL_ARTIFACTS,
  scopeDeclaration: { shape: 'iso_isms_scope', label: 'ISMS scope statement' },
  categoryDirs: {
    clause_4:     'isms-clauses/clause-4-context',
    clause_5:     'isms-clauses/clause-5-leadership',
    clause_6:     'isms-clauses/clause-6-planning',
    clause_7:     'isms-clauses/clause-7-support',
    clause_8:     'isms-clauses/clause-8-operation',
    clause_9:     'isms-clauses/clause-9-performance-evaluation',
    clause_10:    'isms-clauses/clause-10-improvement',
    annex_a_5:    'annex-a-controls/A-5-organizational',
    annex_a_6:    'annex-a-controls/A-6-people',
    annex_a_7:    'annex-a-controls/A-7-physical',
    annex_a_8:    'annex-a-controls/A-8-technological',
    soa:          'statement-of-applicability',
    risk:         'risk-management',
    isms:         'isms-management',
  },
  narratorPromptAddendum:
    `ISO voice: cite Annex A controls as A.x.y and ISMS clauses as Clause N.N. For each control describe objective, implementation mechanism, and effectiveness separately. Respect SoA exclusions: excluded controls receive justification text, not implementation narrative.`,
};
