// FarmCeutica Peptide Database — Categories 4-6
// Immune & Regenerative | Neuro/Cognitive & Mood | Hormonal Balance & Endocrine
// 13 products, 52 SKUs (4 delivery forms each)

import type { PeptideProduct } from "./categories-1-3";

// ═══════════════════════════════════════════════════════════════
// CATEGORY 4: IMMUNE & REGENERATIVE
// Icon: Shield · Color: #059669
// ═══════════════════════════════════════════════════════════════

export const IMMUNE_PEPTIDES: PeptideProduct[] = [
  {
    id: "immuneguard",
    name: "ImmuneGuard\u2122",
    category: "Immune & Regenerative",
    categoryIcon: "Shield",
    categoryColor: "#059669",
    type: "Thymosin Alpha-1 immunomodulatory peptide",
    mechanism: "Balanced immune surveillance modulation, training the immune system to be strong AND smart",
    evidenceLevel: "strong",
    howItWorks: "Your immune system is like a security team, it needs to be strong enough to catch threats but smart enough to not overreact. This peptide helps train the team, supporting balanced immune surveillance.",
    keyHighlights: [
      "Thymosin \u03b11 has extensive global trial data for immune modulation (hepatitis, sepsis, cancer adjunct)",
      "Regulatory approvals in multiple countries for immune support applications",
      "Decades of clinical safety data, one of the most well-studied peptides available",
    ],
    performanceProfile: [
      { metric: "Immune Modulation", value: "Balanced surveillance, not overstimulation" },
      { metric: "T-Cell Function", value: "Improved counts and activity" },
      { metric: "Safety Profile", value: "Decades of global clinical data" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1.5mg daily, AM" },
      { form: "micellar", protocol: "2mg daily, AM" },
      { form: "injectable", protocol: "1.5mg; 10mg vial + 2ml BAC water, 30 units; AM" },
      { form: "nasal_spray", protocol: "200mcg per nostril, AM" },
    ],
    cycleProtocol: "5 days on, 2 off; 8 weeks on, 8 off",
    onsetTimeline: "2-4 weeks immune marker changes",
    genexSynergy: "IL-6 inflammation variants -> immune calibration with NutrigenDX data",
    targetVariants: ["IL-6"],
    genexPanel: "NutrigenDX",
    priceRange: "$149-$199/month",
    marketLaunch: "Month 8",
  },
  {
    id: "regenbpc",
    name: "RegenBPC\u2122",
    category: "Immune & Regenerative",
    categoryIcon: "Shield",
    categoryColor: "#059669",
    type: "Pentadecapeptide (15-amino acid, gastric-derived); crosses blood-brain barrier",
    mechanism: "Multi-tissue repair across muscles, tendons, gut lining, ligaments, and nerves",
    evidenceLevel: "moderate",
    howItWorks: "BPC-157 is a fragment of a protein your stomach naturally produces. Research explores its remarkable ability to support tissue repair across muscles, tendons, gut lining, and more, like sending in a specialized repair crew.",
    keyHighlights: [
      "Phase I oral safety confirmed in 42 healthy volunteers, clean tolerability profile",
      "2025 IV pilot (20mg): no adverse effects on heart, liver, or kidney biomarkers",
      "Case series: 7/12 knee pain patients achieved >6-month relief; 12/12 bladder pain patients improved",
      "No adverse effects even at 50x therapeutic doses",
    ],
    performanceProfile: [
      { metric: "Tendon/Ligament Healing", value: "30-50% acceleration in tensile strength recovery" },
      { metric: "Muscle Tear Recovery", value: "2-3 week acceleration in return-to-activity" },
      { metric: "Gut Lining Repair", value: "Excellent for leaky gut, intestinal permeability" },
      { metric: "Nerve Regeneration", value: "Preliminary evidence for peripheral neuropathy" },
      { metric: "Safety", value: "No adverse effects even at 50x therapeutic doses" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "500mcg 2-3x daily" },
      { form: "micellar", protocol: "500mcg 2-3x daily" },
      { form: "injectable", protocol: "200-500mcg daily or 500mcg 2x daily (subcutaneous); BPC-157/TB-500 blend option: 5mg/5mg vial" },
      { form: "nasal_spray", protocol: "200mcg spray 2x daily" },
    ],
    cycleProtocol: "8-12 weeks for tissue repair; can run continuous for gut healing",
    onsetTimeline: "3-5 days pain reduction; 2-3 weeks structural repair",
    genexSynergy: "COL1A1/COL5A1 collagen variants -> tissue repair optimization with PeptideIQ data",
    targetVariants: ["COL1A1", "COL5A1"],
    genexPanel: "PeptideIQ",
    priceRange: "$149-$229/month",
    marketLaunch: "Month 5",
  },
  {
    id: "tb500-oral",
    name: "TB-500 Oral\u2122",
    category: "Immune & Regenerative",
    categoryIcon: "Shield",
    categoryColor: "#059669",
    type: "43-amino acid peptide (thymic-derived, endogenous); actin polymerization + angiogenesis + immune trafficking",
    mechanism: "First-responder inflammation calming + tissue rebuild, systemic recovery complement to BPC-157's local action",
    evidenceLevel: "moderate",
    howItWorks: "Thymosin \u03b24 is one of the first molecules your body sends to any injury site. TB-500 Oral supports this natural 'first responder' system, helping with the calming-down phase of inflammation and the building-back-up phase of repair.",
    keyHighlights: [
      "Thymosin \u03b24 Phase I for myocardial infarction confirmed cardiac safety + repair signals",
      "Extensive wound-healing and anti-inflammatory research in human pilots",
      "Complements BPC-157 for a comprehensive dual repair protocol (TB-500 = systemic; BPC-157 = local)",
    ],
    performanceProfile: [
      { metric: "Muscle Repair", value: "25-40% acceleration in myofibril regeneration" },
      { metric: "Angiogenesis", value: "Enhanced capillary density, improved tissue perfusion" },
      { metric: "Wound Healing", value: "2-3 week acceleration in epithelialization" },
      { metric: "Immune Recovery", value: "Improved T-cell counts + function" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "2mg daily" },
      { form: "micellar", protocol: "2.5mg daily" },
      { form: "injectable", protocol: "2-4mg per injection, 2x weekly; 2-4 week cycle then 4-week break" },
      { form: "nasal_spray", protocol: "500mcg per nostril, daily" },
    ],
    cycleProtocol: "2-4 week injection cycle, 4-week break; oral forms continuous",
    onsetTimeline: "5-7 days initial; 3-4 weeks maximal; 8-12 weeks post-discontinuation benefit persists",
    genexSynergy: "MMP1 matrix metalloproteinase variants -> tissue remodeling support",
    targetVariants: ["MMP1"],
    genexPanel: "PeptideIQ",
    priceRange: "$249-$349/month",
    marketLaunch: "Month 5",
  },
  {
    id: "antiinflam",
    name: "AntiInflam\u2122",
    category: "Immune & Regenerative",
    categoryIcon: "Shield",
    categoryColor: "#059669",
    type: "Anti-inflammatory bioregulator peptide",
    mechanism: "Inflammation resolution phase support, targets the 'all clear' signal, not suppression",
    evidenceLevel: "moderate",
    howItWorks: "Inflammation is your body's fire alarm. Sometimes the alarm keeps ringing after the fire is out. AntiInflam supports the 'all clear' signal, helping your system resolve inflammation and return to a calm, repair-focused state.",
    keyHighlights: [
      "Targets the resolution phase of inflammation (not suppression)",
      "Khavinson clinical data on immune and inflammatory bioregulation",
      "Designed to complement, not replace, anti-inflammatory nutraceuticals like curcumin and omega-3",
    ],
    performanceProfile: [
      { metric: "Inflammation Resolution", value: "Activates 'all clear' signaling" },
      { metric: "Complement", value: "Works alongside curcumin, omega-3, not as replacement" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily" },
      { form: "micellar", protocol: "1 capsule daily" },
      { form: "injectable", protocol: "2mg/day" },
      { form: "nasal_spray", protocol: "150mcg per nostril, daily" },
    ],
    cycleProtocol: "30 days on, 2 months off; or continuous during chronic inflammation",
    onsetTimeline: "2-4 weeks",
    genexSynergy: "IL-6/TNF-\u03b1 inflammation variants -> resolution pathway calibration",
    targetVariants: ["IL-6", "TNF-\u03b1"],
    genexPanel: "NutrigenDX",
    priceRange: "$119-$149/month",
    marketLaunch: "Month 9",
  },
  {
    id: "vilon",
    name: "Vilon\u2122",
    category: "Immune & Regenerative",
    categoryIcon: "Shield",
    categoryColor: "#059669",
    type: "Khavinson thymus dipeptide bioregulator",
    mechanism: "Thymus function support, immune cell maturation, like reopening classrooms in the immune training academy",
    evidenceLevel: "moderate",
    howItWorks: "Your thymus gland is like a training academy for immune cells, it shrinks with age, reducing your immune 'graduates.' This dipeptide is studied for supporting thymus function and immune cell maturation, like reopening more classrooms in the academy.",
    keyHighlights: [
      "Khavinson clinical data shows immune system restoration in elderly patients",
      "Reduced systemic inflammation markers in longitudinal follow-up",
      "Part of the thymus bioregulator series with lifespan benefits observed in clinical cohorts",
    ],
    performanceProfile: [
      { metric: "Thymus Function", value: "Restored immune cell training capacity" },
      { metric: "Inflammation", value: "Reduced systemic markers in longitudinal studies" },
      { metric: "Lifespan", value: "Benefits observed in clinical cohorts" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "2mg daily" },
      { form: "micellar", protocol: "2.5mg daily" },
      { form: "injectable", protocol: "2mg/day; 20mg vial + 2ml BAC water, 30 days" },
      { form: "nasal_spray", protocol: "150mcg per nostril, daily" },
    ],
    cycleProtocol: "30 days in a row, 2-3x/year",
    onsetTimeline: "4-6 weeks immune marker changes",
    genexSynergy: "Immune panel variants -> thymus-mediated immune calibration",
    targetVariants: ["Immune_panel"],
    genexPanel: "NutrigenDX",
    priceRange: "$129-$159/month",
    marketLaunch: "Month 9",
  },
];

// ═══════════════════════════════════════════════════════════════
// CATEGORY 5: NEURO/COGNITIVE & MOOD
// Icon: Brain · Color: #2563EB
// ═══════════════════════════════════════════════════════════════

export const NEURO_PEPTIDES: PeptideProduct[] = [
  {
    id: "pinealon",
    name: "Pinealon\u2122",
    category: "Neuro/Cognitive & Mood",
    categoryIcon: "Brain",
    categoryColor: "#2563EB",
    type: "3-amino acid bioregulator peptide (Ala-Glu-Asp); specifically addresses hypoxia-induced brain fog",
    mechanism: "Neuroplasticity support, cognitive clarity, excitotoxicity protection, clearing the 'buffering' so signals move faster",
    evidenceLevel: "moderate",
    howItWorks: "Your neurons are like a high-speed fiber network that can slow under chronic stress. Pinealon is studied for supporting neuroplasticity and cognitive clarity, helping clear the 'buffering' so signals move faster and cleaner.",
    keyHighlights: [
      "Neuroprotective effects confirmed in human pilots, cognitive improvement in elderly cohorts",
      "Neurogenesis stimulation without sedation or stimulation, supports natural brain repair",
      "Research on excitotoxicity protection (protecting neurons from 'burnout')",
    ],
    performanceProfile: [
      { metric: "Cerebral Oxygenation", value: "15-25% increase in cerebral blood flow" },
      { metric: "Brain Fog Reversal", value: "40-60% improvement in hypoxia-induced cognitive fog" },
      { metric: "Sleep Quality", value: "Improved melatonin rhythm; enhanced deep sleep" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "2mg daily, AM/PM" },
      { form: "micellar", protocol: "2.5mg daily, AM/PM" },
      { form: "injectable", protocol: "2mg/day; 20mg vial + 2ml BAC water, 20 units" },
      { form: "nasal_spray", protocol: "200mcg per nostril, 2x daily (preferred for neuro)" },
    ],
    cycleProtocol: "30 days in a row, 2-3x/year",
    onsetTimeline: "2-3 weeks cognitive clarity; 4-6 weeks full neuroprotective",
    genexSynergy: "COMT + MTHFR -> neurotransmitter synthesis optimization with GeneX-M data",
    targetVariants: ["COMT", "MTHFR"],
    genexPanel: "GeneX-M",
    priceRange: "$99-$129/month",
    marketLaunch: "Month 7",
  },
  {
    id: "neuroshield",
    name: "NeuroShield\u2122",
    category: "Neuro/Cognitive & Mood",
    categoryIcon: "Brain",
    categoryColor: "#2563EB",
    type: "Bioactive copper-peptide complex (GHK-Cu based); supports 4,000+ gene expression changes",
    mechanism: "Anti-oxidative neuronal protection + systemic gene regulation for tissue health",
    evidenceLevel: "moderate",
    howItWorks: "Your brain cells face constant oxidative stress, like rust forming on critical machinery. NeuroShield supports the anti-oxidative 'coating' that protects neurons from premature wear.",
    keyHighlights: [
      "GHK-Cu: multiple double-blind RCTs (skin) + systemic gene-regulation potential",
      "Emerging research on anti-oxidative neuroprotection pathways",
      "Supports over 4,000 gene expression changes related to tissue health",
    ],
    performanceProfile: [
      { metric: "Collagen Synthesis", value: "50-80% increase in Type I and III collagen" },
      { metric: "Skin (Topical)", value: "Measurable improvement in thickness, firmness, wrinkle reduction" },
      { metric: "Neuroprotection", value: "Emerging anti-oxidative pathways for brain health" },
      { metric: "Gene Regulation", value: "4,000+ gene expression changes" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily" },
      { form: "micellar", protocol: "1 capsule daily" },
      { form: "injectable", protocol: "100-300mcg daily; 50mg vial + 3ml BAC water, 1.7mg = 10 units" },
      { form: "nasal_spray", protocol: "100mcg per nostril, 2x daily" },
    ],
    cycleProtocol: "Continuous for topical; 8 weeks on, 4 off for injectable",
    onsetTimeline: "4-8 weeks visible (topical); 6-12 weeks collagen remodeling (systemic)",
    genexSynergy: "APOE \u03b54 -> neuroprotective strategy enhancement",
    targetVariants: ["APOE"],
    genexPanel: "EpigenHQ",
    priceRange: "$89-$249/month",
    marketLaunch: "Month 5",
  },
  {
    id: "cerebropeptide",
    name: "CerebroPeptide\u2122",
    category: "Neuro/Cognitive & Mood",
    categoryIcon: "Brain",
    categoryColor: "#2563EB",
    type: "Cerebral cortex bioregulator peptide",
    mechanism: "Executive function support, concentration, cognitive endurance, targeting the brain's executive suite",
    evidenceLevel: "moderate",
    howItWorks: "The cerebral cortex is the executive suite of your brain. CerebroPeptide targets the tissue running your highest-level thinking, supporting clarity, concentration, and cognitive endurance.",
    keyHighlights: [
      "Cerebral cortex tissue-specific gene expression bioregulation",
      "Part of the Khavinson organ-specific bioregulator series",
      "Multi-region brain support when paired with Pinealon",
    ],
    performanceProfile: [
      { metric: "Executive Function", value: "Enhanced higher-order thinking" },
      { metric: "Concentration", value: "Improved sustained focus" },
      { metric: "Cognitive Endurance", value: "Extended mental stamina" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily, AM" },
      { form: "micellar", protocol: "1 capsule daily, AM" },
      { form: "injectable", protocol: "2mg/day" },
      { form: "nasal_spray", protocol: "200mcg per nostril, AM (preferred)" },
    ],
    cycleProtocol: "30 days in a row, 2-3x/year",
    onsetTimeline: "2-3 weeks",
    genexSynergy: "BDNF variants -> neuroplasticity enhancement",
    targetVariants: ["BDNF"],
    genexPanel: "EpigenHQ",
    priceRange: "$99-$129/month",
    marketLaunch: "Month 7",
  },
  {
    id: "moodlift",
    name: "MoodLift\u2122",
    category: "Neuro/Cognitive & Mood",
    categoryIcon: "Brain",
    categoryColor: "#2563EB",
    type: "Anxiolytic heptapeptide (7-amino acid, Tuftsin analog, Selank-based)",
    mechanism: "Mood balance via natural neurochemistry pathways without sedation, tolerance, or dependence",
    evidenceLevel: "moderate",
    howItWorks: "Mood is like a boat on water, waves keep rocking it. MoodLift steadies the keel via natural mood chemistry, supporting emotional balance without sedation or dependence.",
    keyHighlights: [
      "Selank: anxiolytic effects comparable to benzodiazepines, with no sedation or dependence",
      "Russian clinical approval for anxiety and cognitive support",
      "No withdrawal, supports natural neurochemistry pathways",
    ],
    performanceProfile: [
      { metric: "Anxiety Reduction", value: "40-60% reduction in baseline anxiety scores" },
      { metric: "Onset", value: "5-10 minutes (intranasal); 30-60 min (subcutaneous)" },
      { metric: "Duration", value: "4-8 hours per dose" },
      { metric: "Cognitive Function", value: "No impairment; some report enhanced focus" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily or as needed" },
      { form: "micellar", protocol: "1 capsule daily or as needed" },
      { form: "injectable", protocol: "250-500mcg daily; 30mg vial + 3ml BAC water, 2-3 days/week" },
      { form: "nasal_spray", protocol: "100-200mcg per nostril, 1-3x daily (fastest onset ~5 min), PREFERRED" },
    ],
    cycleProtocol: "Daily or as-needed; no cycling required",
    onsetTimeline: "5-10 min (intranasal); 30-60 min (oral/injectable)",
    genexSynergy: "COMT Val/Val -> mood stability optimization",
    targetVariants: ["COMT"],
    genexPanel: "GeneX-M",
    priceRange: "$129-$189/month",
    marketLaunch: "Month 7",
  },
];

// ═══════════════════════════════════════════════════════════════
// CATEGORY 6: HORMONAL BALANCE & ENDOCRINE
// Icon: Heart · Color: #EC4899
// ═══════════════════════════════════════════════════════════════

export const HORMONAL_PEPTIDES: PeptideProduct[] = [
  {
    id: "ovapeptide",
    name: "OvaPeptide\u2122",
    category: "Hormonal Balance & Endocrine",
    categoryIcon: "Heart",
    categoryColor: "#EC4899",
    type: "Khavinson ovarian bioregulator (Ovagen-based)",
    mechanism: "Ovarian function support during hormonal transitions, maintaining balanced signaling between ovaries and brain",
    evidenceLevel: "moderate",
    howItWorks: "Your ovaries communicate with your brain via a hormonal conversation. OvaPeptide supports the clarity of that signal, helping maintain balanced ovarian function during hormonal transitions.",
    keyHighlights: [
      "Ovagen: normalized ovarian metabolites in dysregulation cohorts",
      "Tied to Epitalon's pineal-endocrine axis regulation for upstream support",
      "Designed for women in hormonal transitions (perimenopause, cycle irregularity)",
    ],
    performanceProfile: [
      { metric: "Ovarian Metabolites", value: "Normalized in dysregulation cohorts" },
      { metric: "Hormonal Signal", value: "Clearer brain-ovary communication" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily" },
      { form: "micellar", protocol: "1 capsule daily" },
      { form: "injectable", protocol: "2mg/day" },
      { form: "nasal_spray", protocol: "150mcg per nostril, daily" },
    ],
    cycleProtocol: "30 days on, 2 months off; or continuous during perimenopause",
    onsetTimeline: "4-8 weeks hormonal marker changes",
    genexSynergy: "CYP19A1/ESR1 (HormoneIQ) -> estrogen metabolism optimization",
    targetVariants: ["CYP19A1", "ESR1"],
    genexPanel: "HormoneIQ",
    priceRange: "$129-$159/month",
    marketLaunch: "Month 10",
  },
  {
    id: "thyroreg",
    name: "ThyroReg\u2122",
    category: "Hormonal Balance & Endocrine",
    categoryIcon: "Heart",
    categoryColor: "#EC4899",
    type: "Khavinson thyroid bioregulator peptide",
    mechanism: "Thyroid tissue calibration at the cellular level, for subclinical hypothyroid patterns",
    evidenceLevel: "moderate",
    howItWorks: "Your thyroid is the master thermostat of metabolism. When it runs cold, everything slows, energy, weight management, mood. ThyroReg supports thyroid tissue calibration at the cellular level.",
    keyHighlights: [
      "Thyroid function normalization in subclinical hypothyroid cohorts",
      "Tissue-specific gene expression bioregulation",
      "Complements selenium and iodine supplementation for comprehensive thyroid support",
    ],
    performanceProfile: [
      { metric: "Thyroid Function", value: "Normalization in subclinical hypothyroid" },
      { metric: "Metabolic Rate", value: "Supported through tissue calibration" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily, AM" },
      { form: "micellar", protocol: "1 capsule daily, AM" },
      { form: "injectable", protocol: "2mg/day" },
      { form: "nasal_spray", protocol: "150mcg per nostril, AM" },
    ],
    cycleProtocol: "30 days on, 2 months off",
    onsetTimeline: "4-8 weeks TSH/T4 changes",
    genexSynergy: "DIO2 T4->T3 conversion (HormoneIQ) -> thyroid optimization",
    targetVariants: ["DIO2"],
    genexPanel: "HormoneIQ",
    priceRange: "$129-$159/month",
    marketLaunch: "Month 10",
  },
  {
    id: "progestobalance",
    name: "ProgestoBalance\u2122",
    category: "Hormonal Balance & Endocrine",
    categoryIcon: "Heart",
    categoryColor: "#EC4899",
    type: "Hormonal bioregulation / progesterone pathway peptide",
    mechanism: "Progesterone-producing tissue support, optimizing the calming hormonal counterweight",
    evidenceLevel: "moderate",
    howItWorks: "Progesterone is the calming hormone, it balances estrogen, supports deep sleep, and steadies mood. ProgestoBalance supports the tissue that produces progesterone, optimizing this critical hormonal counterweight.",
    keyHighlights: [
      "Progesterone-producing tissue bioregulation",
      "Complements OvaPeptide for comprehensive female hormonal balance",
      "Part of the Khavinson endocrine bioregulator framework",
    ],
    performanceProfile: [
      { metric: "Progesterone Support", value: "Enhanced tissue production capacity" },
      { metric: "Sleep", value: "Supports deep sleep via calming hormone" },
      { metric: "Mood", value: "Steadied via hormonal balance" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily, PM" },
      { form: "micellar", protocol: "1 capsule daily, PM" },
      { form: "injectable", protocol: "2mg/day, PM" },
      { form: "nasal_spray", protocol: "150mcg per nostril, PM" },
    ],
    cycleProtocol: "Continuous or cycling with menstrual cycle",
    onsetTimeline: "4-8 weeks",
    genexSynergy: "ESR1/PGR -> progesterone signaling optimization",
    targetVariants: ["ESR1", "PGR"],
    genexPanel: "HormoneIQ",
    priceRange: "$129-$159/month",
    marketLaunch: "Month 10",
  },
  {
    id: "endoharmonize",
    name: "EndoHarmonize\u2122",
    category: "Hormonal Balance & Endocrine",
    categoryIcon: "Heart",
    categoryColor: "#EC4899",
    type: "Multi-endocrine bioregulation and metabolic balance peptide",
    mechanism: "Multi-gland coordination, tuning the whole endocrine orchestra rather than a single instrument",
    evidenceLevel: "moderate",
    howItWorks: "Your endocrine system is an orchestra of glands, thyroid, adrenals, pancreas, gonads. EndoHarmonize supports the coordination between them, tuning the whole orchestra rather than a single instrument.",
    keyHighlights: [
      "Multi-endocrine communication support between hormonal glands",
      "SS-31 cross-support: mitochondrial energetics benefit endocrine organ function",
      "For complex metabolic + hormonal patterns identified by Ultrathink engine",
      "Retatrutide investigational reference: clinical trials only, discuss with prescribing practitioner",
    ],
    performanceProfile: [
      { metric: "Multi-Gland Coordination", value: "Enhanced inter-organ hormonal communication" },
      { metric: "Metabolic Support", value: "SS-31 cross-support for endocrine energy" },
    ],
    dosingForms: [
      { form: "liposomal", protocol: "1 capsule daily" },
      { form: "micellar", protocol: "1 capsule daily" },
      { form: "injectable", protocol: "2mg/day" },
      { form: "nasal_spray", protocol: "150mcg per nostril, daily" },
    ],
    cycleProtocol: "30 days on, 2 months off",
    onsetTimeline: "6-8 weeks",
    genexSynergy: "AR/CYP19A1 (HormoneIQ) -> multi-endocrine calibration",
    targetVariants: ["AR", "CYP19A1"],
    genexPanel: "HormoneIQ",
    priceRange: "$149-$189/month",
    marketLaunch: "Month 10",
  },
];

// ═══════════════════════════════════════════════════════════════
// COMBINED EXPORT
// ═══════════════════════════════════════════════════════════════

export const ALL_CATEGORIES_4_6 = [
  ...IMMUNE_PEPTIDES,
  ...NEURO_PEPTIDES,
  ...HORMONAL_PEPTIDES,
];

export const CATEGORY_CONFIG_4_6 = [
  { id: "immune", label: "Immune & Regenerative", icon: "Shield", color: "#059669", products: IMMUNE_PEPTIDES },
  { id: "neuro", label: "Neuro/Cognitive & Mood", icon: "Brain", color: "#2563EB", products: NEURO_PEPTIDES },
  { id: "hormonal", label: "Hormonal Balance & Endocrine", icon: "Heart", color: "#EC4899", products: HORMONAL_PEPTIDES },
];
